/**
 * Landmark file in, `*.plate.ts` source out.
 *
 * The emitter owns the whole file, banner to closing brace, because
 * `plate:verify` compares bytes: anything it does not own is something a hand
 * could change without the check noticing. That includes the prose — the doc
 * comment and the per-part notes come out of the landmark file and are written
 * back as comments here.
 *
 * Formatting is Prettier's, run with the project's own config, so a generated
 * file is indistinguishable from a hand-written one and `npm run format:check`
 * has nothing to say about it. Doing it any other way means the emitter and
 * Prettier disagree about a trailing comma once and every plate is "modified"
 * for the rest of the project's life.
 */

import { format, resolveConfig } from 'prettier';

import { drawShape, type LandmarkPart, type LandmarkPlate } from './landmark.ts';

/**
 * The banner.
 *
 * Every generated file says so on its first line, because the failure this
 * prevents is somebody fixing a wing in the plate file, seeing the fix work in
 * the browser, and losing it to the next build.
 */
const BANNER = [
  '// Generated from ../landmarks/%SLUG%.json by `npm run plate:build`.',
  '//',
  '// Do not edit this file. Edit the landmarks and build again; `npm run',
  '// plate:verify` fails the check if the two drift apart.',
].join('\n');

const quote = (value: string): string => `'${value.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;

/** A run of lines as a `/** ... *\/` block, in the house style. */
function block(lines: readonly string[], indent = ''): string {
  const body = lines.map((line) => `${indent} *${line === '' ? '' : ` ${line}`}`).join('\n');

  return `${indent}/**\n${body}\n${indent} */`;
}

/** A run of lines as `//` comments. */
function slashes(lines: readonly string[], indent: string): string {
  return lines.map((line) => `${indent}//${line === '' ? '' : ` ${line}`}`).join('\n');
}

/** Every `PlatePart` one landmark entry produces. A fan produces several. */
function partsOf(entry: LandmarkPart): string[] {
  const shared = [
    `id: ${quote(entry.id)}`,
    `rank: ${quote(entry.rank)}`,
    `fill: ${quote(entry.fill)}`,
  ];

  return drawShape(entry.shape, entry.mirror !== false).map((d) => {
    const fields = [
      ...shared,
      `d: ${quote(d)}`,
      ...(entry.mirror === false ? ['mirror: false'] : []),
      ...(entry.opacity === undefined || entry.opacity === 'solid'
        ? []
        : [`opacity: ${quote(entry.opacity)}`]),
      ...(entry.clipTo === undefined ? [] : [`clipTo: ${quote(entry.clipTo)}`]),
    ];

    return `{\n${fields.map((field) => `      ${field},`).join('\n')}\n    }`;
  });
}

/** The `*.plate.ts` file for one landmark file, formatted. */
export async function emitPlate(plate: LandmarkPlate, cwd: string): Promise<string> {
  const body: string[] = [];

  for (const entry of plate.parts) {
    const drawn = partsOf(entry);

    for (const [index, part] of drawn.entries()) {
      // A note belongs to the measurement, so it is written once above the run
      // a fan expands into rather than repeated over every stroke of it.
      if (entry.note !== undefined && index === 0) body.push(slashes(entry.note, '    '));

      body.push(`    ${part},`);
    }
  }

  const reference = [
    `    title: ${quote(plate.reference.title)},`,
    `    artist: ${quote(plate.reference.artist)},`,
    ...(plate.reference.yearNote === undefined ? [] : [slashes(plate.reference.yearNote, '    ')]),
    `    year: ${String(plate.reference.year)},`,
    `    source: ${quote(plate.reference.source)},`,
    `    licence: ${quote(plate.reference.licence)},`,
  ];

  const source = [
    BANNER.replace('%SLUG%', plate.species),
    '',
    "import type { SpeciesPlate } from '@/lib/plate';",
    '',
    block(plate.doc),
    `export const ${plate.constant}: SpeciesPlate = {`,
    `  species: ${quote(plate.species)},`,
    `  order: ${quote(plate.order)},`,
    `  sex: ${quote(plate.sex)},`,
    ...(plate.hallmark === undefined ? [] : [`  hallmark: ${quote(plate.hallmark)},`]),
    '  reference: {',
    ...reference,
    '  },',
    '  parts: [',
    ...body,
    '  ],',
    '};',
    '',
  ].join('\n');

  const options = await resolveConfig(`${cwd}/src/data/species/x.plate.ts`);

  return format(source, { ...options, filepath: 'plate.ts', parser: 'typescript' });
}
