/**
 * `npm run prerender` — render every route to static HTML in `dist/`.
 *
 * Runs after both Vite builds: the client build, which writes `dist/` and the
 * `index.html` template this fills in, and the SSR build, which writes
 * `dist-ssr/entry-server.js`. `npm run build` chains all three.
 *
 * ## Why the site can be prerendered at all
 *
 * Nothing is fetched. The eighteen records, their plates, the five journal
 * entries, the reference provenance and the identification key are module
 * constants compiled into the bundle, so a page is a pure function of its URL
 * and there is no serialised state to hand the client. That is what makes this
 * a hundred lines rather than a framework.
 *
 * What it buys is the whole of the gap Lighthouse was reporting. The site
 * scored 88 on performance with an LCP of 3.8 s, 88% of which was *render
 * delay*: a throttled mobile connection downloading an empty `<div id="root">`,
 * then the entry, then the vendor chunk, then the plates, before anything could
 * be drawn. The first paint is now in the HTML.
 *
 * ## What is emitted
 *
 * One directory per path with an `index.html` inside it — `dist/calendar/index.html`,
 * `dist/specimen/lucanus-cervus/index.html` — which is the layout every static
 * host resolves as a "pretty URL", plus `dist/index.html` for `/` and
 * `dist/404.html` for everything unmatched. The path list comes from
 * `scripts/site-paths.ts`, the same module the sitemap is built from, so a
 * specimen cannot be listed for a crawler without a file behind it.
 *
 * ## What is checked rather than assumed
 *
 * Three things, all of which fail the build:
 *
 *   · **Class names resolve.** The prerendered markup carries CSS Module class
 *     names generated by the *SSR* build. They are deterministic — file path
 *     and content — so they match the client build's, but "so they match" is
 *     the kind of sentence that is true until a config diverges. Every distinct
 *     module class name emitted is looked up in the stylesheets the client
 *     build actually wrote.
 *   · **No inline styles.** `style-src 'self'` forbids them, and SSR is exactly
 *     where one would appear without anybody noticing: a component that renders
 *     fine in the browser can still emit a `style` attribute here.
 *   · **No inline scripts beyond the JSON-LD data blocks.** `hydrate={false}`
 *     in `entry-server.tsx` is what keeps react-router from writing one, and
 *     this is the assertion that the flag is still doing its job.
 *
 * ## The head
 *
 * `useRouteMeta` writes the head from an effect, and effects do not run here.
 * So each route records what it would have written (see
 * `src/features/meta/serverMeta.ts`) and this script writes it into the file:
 * title, description, canonical and the Open Graph pair. Without that, all
 * thirty-one files would ship the site-level title from `index.html` — to
 * exactly the consumers prerendering is for, the ones that run no JavaScript.
 */

import { mkdir, readdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import process from 'node:process';
import { pathToFileURL } from 'node:url';

/*
  React picks its development or production build off this, and Vite leaves it
  alone in an SSR bundle so that the process running it can decide. Unset, Node
  gets `react-dom-server-legacy.node.development.js`: slower, and noisy with
  warnings meant for a running server rather than for a build. Set here rather
  than in the npm script so it does not need `cross-env` on Windows, and before
  the entry is imported, which is the only moment it can still matter.
*/
process.env.NODE_ENV ??= 'production';

import { SITE, siteUrl } from '../../src/data/site.ts';
import type { RenderedRoute } from '../../src/features/meta/serverMeta.ts';
import { prerenderPaths, ROOT } from '../site-paths.ts';

const DIST = join(ROOT, 'dist');
const SSR_ENTRY = join(ROOT, 'dist-ssr', 'entry-server.js');

/**
 * The origin the static router is handed.
 *
 * A `Request` needs an absolute URL and react-router only reads the path and
 * the query off it, so any origin would do — but the site's own is the one that
 * cannot be mistaken for a leak of the build machine into the output.
 */
const ORIGIN = SITE.origin;

/** `<div id="root"></div>` in the built template, however Vite spelled it. */
const ROOT_DIV = /(<div id="root">)(\s*)(<\/div>)/;

/** A CSS Module class name as `generateScopedName` spells them. */
const MODULE_CLASS = /\b[A-Za-z][\w-]*__[\w-]+__[\w-]{5}\b/g;

/** `style="..."` on any element. Not `<style>`, which is a different sin. */
const INLINE_STYLE = /<[^>]+\sstyle=/i;

/** Every `<script>` opening tag, with its attributes. */
const SCRIPT_TAG = /<script\b[^>]*>/gi;

function escapeAttribute(value: string): string {
  return value.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/"/g, '&quot;');
}

/**
 * Replaces one tag's attribute in the head, in place.
 *
 * In place, and not by appending, for the reason `useRouteMeta` gives at
 * length: `index.html` already carries a description and a canonical so that a
 * consumer running no JavaScript sees something truthful, and every consumer
 * that reads a description reads the *first* one. A second copy after it would
 * never be seen.
 */
function replaceAttribute(
  html: string,
  selector: RegExp,
  attribute: string,
  value: string,
): string {
  const match = selector.exec(html);

  if (match === null) throw new Error(`prerender — no ${String(selector)} in the template`);

  const tag = match[0];
  const attributePattern = new RegExp(`(\\s${attribute}=")[^"]*(")`);

  if (!attributePattern.test(tag)) {
    throw new Error(`prerender — ${String(selector)} has no ${attribute} attribute`);
  }

  /*
    Function replacements, both of them, and not because it reads better. A
    replacement *string* gives `$1`, `$&` and `$'` special meaning, so a
    description containing a dollar sign rewrites itself — and, the first time
    round, escaping the value's dollars also escaped the `$1` and `$2` holding
    the tag together, which shipped thirty-one files reading
    `<meta property="og:type"$1website$2 />`. A function replacement has no such
    rule for either half.
  */
  const replaced = tag.replace(
    attributePattern,
    (_match, open: string, close: string) => `${open}${escapeAttribute(value)}${close}`,
  );

  return html.replace(tag, () => replaced);
}

/** Writes one route's recorded metadata into the template's head. */
function applyMeta(html: string, meta: RenderedRoute['meta'], path: string): string {
  if (meta === null) {
    throw new Error(
      `prerender — ${path} rendered without calling useRouteMeta, so it has no title of its own`,
    );
  }

  let out = html.replace(
    /<title>[^<]*<\/title>/,
    () => `<title>${escapeAttribute(meta.title)}</title>`,
  );

  out = replaceAttribute(out, /<meta\s+name="description"[^>]*>/, 'content', meta.description);
  out = replaceAttribute(out, /<meta\s+property="og:title"[^>]*>/, 'content', meta.title);
  out = replaceAttribute(
    out,
    /<meta\s+property="og:description"[^>]*>/,
    'content',
    meta.description,
  );
  out = replaceAttribute(out, /<meta\s+property="og:url"[^>]*>/, 'content', meta.canonical);
  out = replaceAttribute(out, /<meta\s+property="og:type"[^>]*>/, 'content', meta.ogType);
  out = replaceAttribute(out, /<link\s+rel="canonical"[^>]*>/, 'href', meta.canonical);

  return out;
}

interface Stylesheet {
  readonly href: string;
  readonly text: string;
}

/** Every `.css` file the client build emitted, kept apart so a page can pick. */
async function builtStylesheets(): Promise<readonly Stylesheet[]> {
  const assets = join(DIST, 'assets');
  const names = (await readdir(assets)).filter((name) => name.endsWith('.css'));

  return Promise.all(
    names.map(async (name) => ({
      href: `/assets/${name}`,
      text: await readFile(join(assets, name), 'utf8'),
    })),
  );
}

function checkNoInlineStyles(html: string, path: string): void {
  if (INLINE_STYLE.test(html)) {
    throw new Error(
      `prerender — ${path} emitted a style attribute, which \`style-src 'self'\` forbids`,
    );
  }
}

/**
 * The only `<script>` a rendered page may contain is a JSON-LD data block.
 *
 * A `<script>` whose type is neither a JavaScript MIME type nor
 * `module`/`importmap` is classified as a data block and never executed, which
 * is why `JsonLd` is allowed under `script-src 'self'` — see its own comment.
 * Anything else in the *rendered* markup would be a real inline script.
 */
function checkNoInlineScripts(html: string, path: string): void {
  for (const tag of html.match(SCRIPT_TAG) ?? []) {
    if (tag.includes('application/ld+json')) continue;

    throw new Error(`prerender — ${path} emitted an inline script: ${tag}`);
  }
}

/**
 * Which stylesheets this page's markup needs, and the check that every class in
 * it is defined somewhere.
 *
 * The check came first and the answer fell out of it. Only the **entry**
 * stylesheet is linked in `index.html`; a lazy route's CSS is a sibling of its
 * JS chunk and is injected by the browser when that chunk loads. That was
 * correct while the markup arrived with the chunk, and wrong the moment the
 * markup started arriving in the file: the prerendered calendar painted its
 * chart unstyled and restyled it two round trips later, and six of the eight
 * routes had it.
 *
 * Rather than mapping route paths to chunk names — a list to keep in step with
 * the router — each stylesheet is asked whether it defines a class the page
 * actually uses. It is the same string search the verification already does,
 * read the other way round, and it cannot drift because it is derived from the
 * markup itself.
 */
function stylesheetsFor(
  html: string,
  stylesheets: readonly Stylesheet[],
  path: string,
): { readonly hrefs: readonly string[]; readonly names: readonly string[] } {
  const names = [...new Set(html.match(MODULE_CLASS) ?? [])];
  const used = stylesheets.filter((sheet) => names.some((name) => sheet.text.includes(`.${name}`)));
  const missing = names.filter((name) => !used.some((sheet) => sheet.text.includes(`.${name}`)));

  if (missing.length > 0) {
    throw new Error(
      `prerender — ${path} carries ${String(missing.length)} class name(s) no stylesheet defines: ` +
        `${missing.slice(0, 5).join(', ')}.\n` +
        '  The SSR and client builds disagree about `css.modules.generateScopedName`.',
    );
  }

  return { hrefs: used.map((sheet) => sheet.href), names };
}

/**
 * Links the page's stylesheets, after the one the template already carries.
 *
 * After, not before: the entry sheet holds the reset, the tokens and the global
 * layer, and a route module that overrides one of them is relying on being
 * later in the cascade. It is also where the browser would have injected the
 * route's own sheet, so the order is the one that was always intended.
 */
function linkStylesheets(html: string, hrefs: readonly string[]): string {
  const anchor = /<link rel="stylesheet"[^>]*>/.exec(html);

  if (anchor === null) throw new Error('prerender — the template links no stylesheet');

  const extra = hrefs
    .filter((href) => !anchor[0].includes(href))
    .map((href) => `\n    <link rel="stylesheet" crossorigin href="${href}">`)
    .join('');

  return html.replace(anchor[0], () => `${anchor[0]}${extra}`);
}

/** `/` → `dist/index.html`; `/specimen/x` → `dist/specimen/x/index.html`. */
function fileFor(path: string): string {
  return path === '/' ? join(DIST, 'index.html') : join(DIST, path, 'index.html');
}

/**
 * Renders one route from a **fresh copy** of the server bundle.
 *
 * A query string Node has never seen is a different module specifier, so the
 * entry is evaluated again rather than served from the ESM cache — and this is
 * not fastidiousness, it is the difference between a correct build and a wrong
 * one.
 *
 * `SpecimenRow` puts its plate behind `React.lazy` inside a
 * `<Suspense fallback={null}>`, deliberately: the eighteen drawings are 258 kB
 * of path data on the landing route, and keeping them off the critical path is
 * what took the largest contentful paint down in the first place. A synchronous
 * `renderToString` cannot await a dynamic import, so a lazy component renders
 * its fallback — *the first time*. The import then resolves in the background,
 * and every later render in the same process gets the real thing.
 *
 * Sharing one module graph therefore produced two different files for the same
 * component: `dist/index.html` at 78 kB with no plates, because `/` was
 * rendered first, and `dist/catalogue/index.html` at 726 kB with all eighteen,
 * because it was rendered second. Which is which depended on the order the
 * loop happened to run in.
 *
 * The empty one is the correct one, and for a reason better than "it was
 * first". The browser's own first render is also the fallback — `React.lazy` is
 * unresolved at hydration on the client too — so a file with the plates baked
 * in is a file whose markup the client immediately contradicts. It also undoes
 * the split it is meant to preserve: 650 kB of beetle inlined into the document
 * has to arrive before anything at all can paint.
 *
 * For this to work the SSR bundle has to be a **single file** — see
 * `inlineDynamicImports` in vite.config.ts. Node re-evaluates only the
 * specifier it is handed, so a chunked build would give a half-fresh graph:
 * a new `ThemeContext` in the re-evaluated entry, and cached route chunks still
 * closing over the old one, at which point every lazy route renders outside the
 * provider and `useSeason` throws. React and react-dom stay external and stay
 * cached, which is correct — `renderToString` keeps no state between calls.
 */
async function renderFresh(entryUrl: string, path: string, nonce: number): Promise<RenderedRoute> {
  const { renderRoute } = (await import(`${entryUrl}?prerender=${String(nonce)}`)) as {
    renderRoute: (url: string) => Promise<RenderedRoute>;
  };

  return renderRoute(`${ORIGIN}${path}`);
}

async function main(): Promise<void> {
  const template = await readFile(join(DIST, 'index.html'), 'utf8').catch(() => null);

  if (template === null) {
    throw new Error('prerender — dist/index.html is missing. Run `vite build` first.');
  }

  /*
    `dist/index.html` is both the template every page is built from and the file
    `/` is written to, which means this step consumes its own input. Running it
    twice without a client build in between finds a root div that is already
    full, and rather than trying to empty it again — unpicking one prerender to
    make another, with the head already rewritten by the first — it stops. The
    build chains `vite build` ahead of this for exactly that reason.
  */
  if (!ROOT_DIV.test(template)) {
    throw new Error(
      'prerender — dist/index.html has no empty <div id="root">.\n' +
        '  It has most likely already been prerendered. `npm run prerender` needs a\n' +
        '  fresh client build under it; run `npm run build`, which does both in order.',
    );
  }

  const entryUrl = pathToFileURL(SSR_ENTRY).href;
  const stylesheets = await builtStylesheets();
  const paths = await prerenderPaths();
  const routes = [...paths, '/404'];
  let classNames = 0;
  let sheets = 0;
  let first = '';

  for (const [index, path] of routes.entries()) {
    const { html, meta } = await renderFresh(entryUrl, path, index);

    if (index === 0) first = html;

    checkNoInlineStyles(html, path);
    checkNoInlineScripts(html, path);

    const { hrefs, names } = stylesheetsFor(html, stylesheets, path);

    classNames = Math.max(classNames, names.length);
    sheets = Math.max(sheets, hrefs.length);

    /*
      `$&` and friends are special in a replacement string, and the rendered
      markup is full of `$`-free HTML today and could contain one tomorrow — a
      species name, a journal sentence. The function form has no such rule.
    */
    const document = linkStylesheets(applyMeta(template, meta, path), hrefs).replace(
      ROOT_DIV,
      (_match, open: string, _space: string, close: string) => `${open}${html}${close}`,
    );

    /*
      The 404 is written flat rather than as `dist/404/index.html`, because
      `404.html` at the publish root is the file every static host looks for —
      and it is where `public/_redirects` points its catch-all.
    */
    const file = path === '/404' ? join(DIST, '404.html') : fileFor(path);

    await mkdir(dirname(file), { recursive: true });
    await writeFile(file, document, 'utf8');
  }

  /**
   * The whole point of `renderFresh`, asserted rather than trusted.
   *
   * The first route is rendered once more, at the end, and must come out
   * identical. Anything the pages leave behind in module state — a resolved
   * `React.lazy`, a memo, a counter — shows up here as a difference, because
   * this render is the one with thirty other pages behind it. It is one extra
   * render and it is what stands between a build that is a function of the URL
   * and a build that is a function of the order the loop ran in.
   */
  const [firstPath] = routes;
  const again = await renderFresh(entryUrl, firstPath ?? '/', routes.length);

  if (again.html !== first) {
    throw new Error(
      `prerender — ${String(firstPath)} rendered differently the second time ` +
        `(${String(first.length)} bytes, then ${String(again.html.length)}).\n` +
        '  Something is leaking between routes: state that survives a render, or a\n' +
        '  module the pages share and mutate. The output is not a function of the URL.',
    );
  }

  console.log(
    `prerender — wrote ${String(paths.length + 1)} HTML files ` +
      `(${String(paths.length)} routes and 404.html); ` +
      `up to ${String(classNames)} module class names a page, all resolved against ` +
      `${String(stylesheets.length)} stylesheets, up to ${String(sheets)} linked`,
  );
  console.log(`prerender — canonical origin ${siteUrl('/')}`);
}

await main().catch((error: unknown) => {
  console.error(error);
  process.exitCode = 1;
});
