/**
 * `REFERENCE_SOURCES` in, `references/SOURCES.md` out.
 *
 * The emitter owns the whole document, banner to last full stop, because
 * `sources:verify` compares bytes: anything it does not own is something a hand
 * could change without the check noticing — and the thing being checked here is
 * a licence claim, which is the worst kind of fact to let drift.
 *
 * Two kinds of prose, split the way the plate builder splits them. Prose about
 * one reference lives in the data module, beside the reference. Prose about the
 * folder as a whole — what tracing is, what "committed" means here, what to do
 * with a reference whose licence forbids redistribution — belongs to the
 * document, and is `PREAMBLE` below.
 *
 * Formatting is Prettier's, run with the project's own config, so
 * `npm run format:check` has nothing to say about a generated file. Long prose
 * is hard-wrapped first, because the project's Prettier config sets
 * `proseWrap: preserve` for markdown: Prettier will keep whatever wrapping it
 * is given and rewrap nothing, so a paragraph stored as one long string would
 * otherwise be committed as one 400-character line.
 */

import { format, resolveConfig } from 'prettier';

import {
  publicationLine,
  REFERENCE_SOURCES,
  referenceFileName,
  type ReferenceSource,
} from '../../src/data/references/sources.ts';

/**
 * Where prose is wrapped. Narrower than the 100 columns Prettier gives code,
 * because this is a document rather than a file — and it is what the
 * hand-written version used.
 */
const PROSE_WIDTH = 78;

const BANNER = [
  '<!--',
  '  Generated from src/data/references/sources.ts by `npm run sources:build`.',
  '',
  '  Do not edit this file. Edit the data module and build again; `npm run',
  '  sources:verify` fails the check if the two drift apart. The About page',
  '  renders its credits list from the same module, so the provenance a reader',
  '  sees here and the provenance a visitor sees on the site are one list.',
  '-->',
].join('\n');

/**
 * The document's own prose: true of the folder, not of any one reference.
 */
const PREAMBLE = [
  '# Reference images',
  '',
  'Every plate is traced from a reference held here. The measurements taken from it live in `src/data/species/landmarks/*.json`; `src/data/species/*.plate.ts` is built from those. This file records where each one came from and on what terms, so the provenance travels with the drawing rather than living in someone’s memory.',
  '',
  '**These files are committed.** Every entry below is public domain — the author has been dead for more than a century, or the work was published long before 1923 — so redistributing them inside this repository is permitted. If a future reference arrives under terms that do **not** allow redistribution, add it to `.gitignore`, record the download URL here instead of the file, and say so in its entry.',
  '',
  'Tracing is our own work. A plate is a simplified engraving drawn _from_ the reference, not a copy of it: outlines, proportions and the arrangement of the limbs come from the reference, and the linework, hatching and colour are ours. The reference is not shipped to the browser — it appears only on the dev-only `/lab/plates` contact sheet, where it is credited on screen.',
];

/** Greedy wrap on spaces. Deterministic, and it never breaks a word. */
function wrap(text: string, width = PROSE_WIDTH): string {
  const lines: string[] = [];
  let line = '';

  for (const word of text.split(' ')) {
    if (line === '') line = word;
    else if (line.length + 1 + word.length <= width) line += ` ${word}`;
    else {
      lines.push(line);
      line = word;
    }
  }

  if (line !== '') lines.push(line);

  return lines.join('\n');
}

/** A markdown table row, with the cell text escaped for the pipe delimiter. */
function row(term: string, value: string): string {
  return `| **${term}** | ${value.replace(/\|/g, '\\|')} |`;
}

/** The provenance table for one reference. */
function table(source: ReferenceSource): string {
  const file = referenceFileName(source);
  const rows = [
    row('Species', source.subject),
    row('View', source.view),
    row('File', `[\`${file}\`](${file}) — ${source.pixels}, ${source.weight}`),
    row('Source page', `<${source.sourcePage}>`),
    ...(source.fileUrl === undefined ? [] : [row('File URL', `<${source.fileUrl}>`)]),
    row('Author', source.artistLine),
    row('Published in', publicationLine(source)),
    ...(source.dateNote === undefined ? [] : [row('Date', source.dateNote)]),
    row('Licence', source.licenceDetail),
    row('Downloaded', source.downloaded),
    // Derived rather than stored: the landmark file is what a reference is used
    // by now, and the hand-written version said `*.plate.ts` for the four
    // entries written before the builder existed and the landmarks for the
    // twelve after it. Both were true when written; neither was checkable.
    row('Used by', `\`src/data/species/landmarks/${source.species}.json\``),
  ];

  // An empty header row: every table here is a two-column term-and-value list,
  // and a header saying "Field | Value" is a header saying nothing.
  return ['|  |  |', '| --- | --- |', ...rows].join('\n');
}

/** One reference: heading, table, and why this figure. */
function entry(source: ReferenceSource): string {
  return [
    `## ${source.heading}`,
    '',
    table(source),
    '',
    source.notes.map((note) => wrap(note)).join('\n\n'),
  ].join('\n');
}

/** The whole document, formatted. */
export async function emitSources(cwd: string): Promise<string> {
  const document = [
    BANNER,
    '',
    PREAMBLE.map((line) => (line.startsWith('#') || line === '' ? line : wrap(line))).join('\n'),
    '',
    '---',
    '',
    REFERENCE_SOURCES.map(entry).join('\n\n---\n\n'),
    '',
  ].join('\n');

  const options = await resolveConfig(cwd);

  return format(document, { ...options, filepath: 'SOURCES.md', parser: 'markdown' });
}
