// Generated from ../landmarks/acherontia-atropos.json by `npm run plate:build`.
//
// Do not edit this file. Edit the landmarks and build again; `npm run
// plate:verify` fails the check if the two drift apart.

import type { SpeciesPlate } from '@/lib/plate';

/**
 * *Acherontia atropos*, upperside, wings spread — the death's-head hawkmoth.
 *
 * Traced from figure 1 of plate XIII of Kirby's *British and European
 * Butterflies and Moths*, the same book and the same hands as the peacock two
 * accessions earlier. `references/acherontia-atropos.jpg` is the plate; the
 * moth is the upper figure and 1a is its larva.
 *
 * Unlike the peacock, this figure is drawn square to the page and symmetric,
 * so the proportions came off it directly: 425 pixels from the front of the
 * head to the tip of the abdomen, 122 units across the thorax and a half-span
 * of 1150 — which is 1.15 body lengths, and matches the animal's 90 to 130
 * millimetres of wing against 55 of body.
 *
 * ## What the drawing has to get right
 *
 * The **skull**, obviously. It is a real marking and not a trick of the light:
 * a pale patch on the thorax with two dark sockets in it and a dark vertical
 * mouth below, and it is the reason the animal has been an omen in three
 * languages. Drawn as those three shapes clipped to the thorax — the pale
 * ground, the pair of sockets, the mouth — because one shape would be a patch
 * and the arrangement is the whole thing.
 *
 * Then the **abdomen**, which is the other half of the identification: broad,
 * banded across, and split lengthwise by a wide grey-blue dorsal stripe. Six
 * bands and a stripe, and the stripe drawn on the axis where it belongs.
 *
 * Then the **hindwing bands**. Two dark bands on an orange ground, both
 * following the outer margin, and they are drawn as three strips on one traced
 * edge at three depths — dark to 96, pigment over it to 52, dark again over
 * that to 20. What shows is band, ground, band. Offsetting three edges by hand
 * instead would put each of them a few units wrong all the way round.
 *
 * ## No legs
 *
 * A hawkmoth at rest holds its legs under the thorax and a spread figure shows
 * none, which is why `REQUIRED_PARTS.lepidoptera` does not ask for them. The
 * palps are drawn, because a Sphingid's are large, upturned and visible from
 * above.
 *
 * ## Plate space
 *
 * y = 0 at the front of the head, y = 1000 at the tip of the abdomen. The
 * forewing apex is at x = 1150, and the antennae reach above y = -180.
 */
export const ACHERONTIA_ATROPOS_PLATE: SpeciesPlate = {
  species: 'acherontia-atropos',
  order: 'lepidoptera',
  sex: 'unsexed',
  hallmark: 'the skull on the thorax, and the banded abdomen with its grey dorsal stripe',
  reference: {
    title: 'British and European Butterflies and Moths (Macrolepidoptera), plate XIII figure 1',
    artist: 'H. Deuchert and Shirley Slocombe',
    year: 1895,
    source:
      'https://commons.wikimedia.org/wiki/File:British_and_European_butterflies_and_moths_(Macrolepidoptera)_(Plate_XIII)_(6466294171).jpg',
    licence: 'Public domain (PD-old-70-expired)',
  },
  parts: [
    // The hind wing first, so the forewing overlaps its base — which is the way
    // round a spread moth is put together and the reason the orange only shows
    // below the forewing's trailing edge.
    {
      id: 'hindwing',
      rank: 'outline',
      fill: 'pigment',
      d: 'M100 356 C125.95 335.87 220.24 370.73 280 382 C340.24 393.36 404.57 405.44 460 424 C510.45 440.89 560.76 460.12 600 486 C634.37 508.67 673.04 536.24 686 566 C696.7 590.56 697.96 624.36 686 646 C672.52 670.38 633.04 687.41 600 700 C562.35 714.35 513.33 722 470 722 C426.67 722 381.31 714.39 340 700 C297.9 685.33 254.91 663.25 220 634 C183.89 603.75 149.89 557.38 128 520 C110.19 489.59 95.98 459.01 92 430 C88.51 404.58 83.4 368.88 100 356 Z',
    },
    // The two dark bands, as three strips on one edge.
    //
    // Deepest first: dark to 96 units in from the margin, the orange ground
    // over it to 52, dark again over that to 20. What is left showing is a
    // narrow band at the margin, the ground, and a second band inside — which
    // is what the reference has, and it is one measured edge rather than three.
    {
      id: 'wing-marking',
      rank: 'structure',
      fill: 'pigment-deep',
      d: 'M590 506 C612.89 504.34 652.61 545.09 664 570 C673.77 591.37 675.27 624.2 664 642 C651.82 661.24 616.91 668.68 588 678 C553.18 689.22 508.34 699.88 468 700 C427.02 700.12 383.19 691.89 344 678 C304.49 664 239.73 642.92 232 616 C225.3 592.69 255.99 538.34 278.49 532.01 C302.83 525.17 343.01 575.54 376.07 587.51 C406.18 598.42 437.26 604.17 467.73 604 C498.08 603.83 537.88 586.89 558.55 586.63 C569.22 586.5 580.22 586.31 582.88 590.66 C585.29 594.61 581.58 608.15 576.69 609.92 C568.38 612.94 529.29 592.76 527.2 578.61 C524.52 560.49 567.32 507.64 590 506 Z',
      clipTo: 'hindwing',
    },
    {
      id: 'wing-marking',
      rank: 'structure',
      fill: 'pigment',
      d: 'M590 506 C609.4 504.59 652.61 545.09 664 570 C673.77 591.37 675.27 624.2 664 642 C651.82 661.24 616.91 668.68 588 678 C553.18 689.22 508.34 699.88 468 700 C427.02 700.12 383.19 691.89 344 678 C304.49 664 238.49 638.58 232 616 C227.87 601.61 243.02 574.53 257.18 570.51 C278.66 564.4 325.32 616.07 361.37 628.99 C395.67 641.28 432.56 648.15 467.85 648 C502.78 647.86 544.1 635.27 572.05 628.51 C591.26 623.86 614.6 622.77 620.06 614.19 C623.74 608.4 621.34 599.47 616.71 591.62 C608.23 577.27 557.61 561.01 555.98 545.33 C554.64 532.39 575.86 507.02 590 506 Z',
      clipTo: 'hindwing',
    },
    {
      id: 'wing-marking',
      rank: 'structure',
      fill: 'pigment-deep',
      d: 'M590 506 C604.32 504.96 652.61 545.09 664 570 C673.77 591.37 675.27 624.2 664 642 C651.82 661.24 616.91 668.68 588 678 C553.18 689.22 508.34 699.88 468 700 C427.02 700.12 383.19 691.89 344 678 C304.49 664 236.72 632.43 232 616 C230.13 609.51 235.22 600.35 241.69 598.5 C257.83 593.88 312.49 645.56 350.68 659.15 C388 672.43 429.15 680.13 467.94 680 C506.2 679.87 549.6 668.66 581.86 658.96 C607.1 651.38 637.28 646.53 647.1 631.31 C655.59 618.14 653.74 594.68 645.81 578.32 C635.51 557.05 578.02 534.49 576.92 521.13 C576.4 514.81 583.52 506.47 590 506 Z',
      clipTo: 'hindwing',
    },
    {
      id: 'wing-vein',
      rank: 'detail',
      fill: 'none',
      d: 'M140 420 C140 420 303.08 444.85 380 470 C456.37 494.97 600 570 600 570',
      clipTo: 'hindwing',
    },
    {
      id: 'wing-vein',
      rank: 'detail',
      fill: 'none',
      d: 'M141.25 443.75 C141.25 443.75 293.81 486.62 367.5 512.5 C440 537.96 580 597.5 580 597.5',
      clipTo: 'hindwing',
    },
    {
      id: 'wing-vein',
      rank: 'detail',
      fill: 'none',
      d: 'M142.5 467.5 C142.5 467.5 284.4 528.44 355 555 C423.55 580.79 560 625 560 625',
      clipTo: 'hindwing',
    },
    {
      id: 'wing-vein',
      rank: 'detail',
      fill: 'none',
      d: 'M143.75 491.25 C143.75 491.25 274.83 570.37 342.5 597.5 C407.04 623.37 540 652.5 540 652.5',
      clipTo: 'hindwing',
    },
    {
      id: 'wing-vein',
      rank: 'detail',
      fill: 'none',
      d: 'M145 515 C145 515 265.1 612.5 330 640 C390.52 665.65 520 680 520 680',
      clipTo: 'hindwing',
    },
    // The fore wing: long, narrow and pointed, swept back from a costa that is
    // nearly straight. A hawkmoth's wing is built for a hundred kilometres of
    // migration and it looks like it — this animal reaches Britain from north
    // Africa under its own power.
    {
      id: 'forewing',
      rank: 'outline',
      fill: 'pigment-deep',
      d: 'M104 132 C131.84 89.23 229.92 101.23 300 86 C380.42 68.53 473.14 49.02 560 34 C646.47 19.04 737.86 6.3 820 -4 C893.64 -13.23 969.69 -20.83 1030 -26 C1075.52 -29.9 1134.76 -52.24 1150 -34 C1165.46 -15.5 1141.12 48.69 1120 86 C1095.26 129.7 1044.61 168.26 1000 206 C952 246.61 896.88 288.94 840 320 C783.5 350.85 722.71 376.65 660 392 C596.15 407.63 524.97 410.2 460 412 C398.48 413.7 334.86 411.08 280 404 C232.87 397.92 179.76 406.54 150 376 C109.33 334.27 73.09 179.5 104 132 Z',
    },
    {
      id: 'wing-vein',
      rank: 'detail',
      fill: 'none',
      d: 'M180 180 C180 180 426.5 160.88 560 140 C711.23 116.35 1040 40 1040 40',
      clipTo: 'forewing',
    },
    {
      id: 'wing-vein',
      rank: 'detail',
      fill: 'none',
      d: 'M183.33 206.67 C183.33 206.67 424.57 195.17 553.33 176.67 C696.61 156.08 1003.33 83.33 1003.33 83.33',
      clipTo: 'forewing',
    },
    {
      id: 'wing-vein',
      rank: 'detail',
      fill: 'none',
      d: 'M186.67 233.33 C186.67 233.33 422.66 229.48 546.67 213.33 C681.9 195.72 966.67 126.67 966.67 126.67',
      clipTo: 'forewing',
    },
    {
      id: 'wing-vein',
      rank: 'detail',
      fill: 'none',
      d: 'M190 260 C190 260 420.79 263.82 540 250 C667.11 235.26 930 170 930 170',
      clipTo: 'forewing',
    },
    {
      id: 'wing-vein',
      rank: 'detail',
      fill: 'none',
      d: 'M193.33 286.67 C193.33 286.67 418.97 298.2 533.33 286.67 C652.22 274.68 893.33 213.33 893.33 213.33',
      clipTo: 'forewing',
    },
    {
      id: 'wing-vein',
      rank: 'detail',
      fill: 'none',
      d: 'M196.67 313.33 C196.67 313.33 417.2 332.61 526.67 323.33 C637.21 313.97 856.67 256.67 856.67 256.67',
      clipTo: 'forewing',
    },
    {
      id: 'wing-vein',
      rank: 'detail',
      fill: 'none',
      d: 'M200 340 C200 340 415.51 367.06 520 360 C622.07 353.1 820 300 820 300',
      clipTo: 'forewing',
    },
    // The transverse fasciae — the paler zigzag bands across the forewing. Four
    // strokes, from a guide near the wing base to one out towards the apex.
    //
    // Kirby's lithograph carries them as mottling in three or four browns. An
    // engraving has line and nothing else, so what is kept is where the bands
    // run and not what colour they are.
    {
      id: 'wing-marking',
      rank: 'detail',
      fill: 'none',
      d: 'M320 110 C320 110 350.36 204.24 350 250 C349.65 294.18 320 380 320 380',
      clipTo: 'forewing',
    },
    {
      id: 'wing-marking',
      rank: 'detail',
      fill: 'none',
      d: 'M513.33 80 C513.33 80 544.8 169.94 543.33 213.33 C541.91 255.44 506.67 336.67 506.67 336.67',
      clipTo: 'forewing',
    },
    {
      id: 'wing-marking',
      rank: 'detail',
      fill: 'none',
      d: 'M706.67 50 C706.67 50 739.19 135.68 736.67 176.67 C734.2 216.74 693.33 293.33 693.33 293.33',
      clipTo: 'forewing',
    },
    {
      id: 'wing-marking',
      rank: 'detail',
      fill: 'none',
      d: 'M900 20 C900 20 933.51 101.46 930 140 C926.53 178.09 880 250 880 250',
      clipTo: 'forewing',
    },
    // The two pale flecks near the middle of each forewing. Small, and drawn
    // because they are the only two hard-edged marks on a wing that is
    // otherwise all gradation.
    {
      id: 'wing-marking',
      rank: 'detail',
      fill: 'surface',
      d: 'M716 120 C716 126.63 708.84 132 700 132 C691.16 132 684 126.63 684 120 C684 113.37 691.16 108 700 108 C708.84 108 716 113.37 716 120 Z',
      clipTo: 'forewing',
    },
    {
      id: 'wing-marking',
      rank: 'detail',
      fill: 'surface',
      d: 'M652 194 C652 199.52 646.63 204 640 204 C633.37 204 628 199.52 628 194 C628 188.48 633.37 184 640 184 C646.63 184 652 188.48 652 194 Z',
      clipTo: 'forewing',
    },
    // The abdomen. Broad and heavy — a hawkmoth carries the flight muscle and
    // the fuel for it — with the bands across and the grey dorsal stripe down.
    {
      id: 'abdomen',
      rank: 'outline',
      fill: 'pigment',
      d: 'M0 352 C28.67 352 69.27 353.57 86 372 C103.7 391.5 96.96 434.95 99 470 C101.34 510.2 98.83 556.69 97 600 C95.17 643.36 92.44 688.56 88 730 C83.9 768.28 79.11 805.37 72 840 C65.49 871.7 57.44 905.07 48 930 C40.83 948.92 33.28 965.7 24 978 C16.77 987.58 8 1000 0 1000 C-8 1000 -16.77 987.58 -24 978 C-33.28 965.7 -40.83 948.92 -48 930 C-57.44 905.07 -65.49 871.7 -72 840 C-79.11 805.37 -83.9 768.28 -88 730 C-92.44 688.56 -95.17 643.36 -97 600 C-98.83 556.69 -101.34 510.2 -99 470 C-96.96 434.95 -103.7 391.5 -86 372 C-69.27 353.57 -28.67 352 0 352 Z',
      mirror: false,
    },
    // The bands, as seven strokes each crossing the axis — the fan case the
    // validator allows on the midline, because both guides are centred on it.
    // The strokes narrow as they go back, which is the abdomen tapering rather
    // than the bands changing.
    {
      id: 'abdomen-segment',
      rank: 'structure',
      fill: 'none',
      d: 'M-92 430 C-92 430 -30.67 430 0 430 C30.67 430 92 430 92 430',
      mirror: false,
      clipTo: 'abdomen',
    },
    {
      id: 'abdomen-segment',
      rank: 'structure',
      fill: 'none',
      d: 'M-83.33 513.33 C-83.33 513.33 -27.78 513.33 0 513.33 C27.78 513.33 83.33 513.33 83.33 513.33',
      mirror: false,
      clipTo: 'abdomen',
    },
    {
      id: 'abdomen-segment',
      rank: 'structure',
      fill: 'none',
      d: 'M-74.67 596.67 C-74.67 596.67 -24.89 596.67 0 596.67 C24.89 596.67 74.67 596.67 74.67 596.67',
      mirror: false,
      clipTo: 'abdomen',
    },
    {
      id: 'abdomen-segment',
      rank: 'structure',
      fill: 'none',
      d: 'M-66 680 C-66 680 -22 680 0 680 C22 680 66 680 66 680',
      mirror: false,
      clipTo: 'abdomen',
    },
    {
      id: 'abdomen-segment',
      rank: 'structure',
      fill: 'none',
      d: 'M-57.33 763.33 C-57.33 763.33 -19.11 763.33 0 763.33 C19.11 763.33 57.33 763.33 57.33 763.33',
      mirror: false,
      clipTo: 'abdomen',
    },
    {
      id: 'abdomen-segment',
      rank: 'structure',
      fill: 'none',
      d: 'M-48.67 846.67 C-48.67 846.67 -16.22 846.67 0 846.67 C16.22 846.67 48.67 846.67 48.67 846.67',
      mirror: false,
      clipTo: 'abdomen',
    },
    {
      id: 'abdomen-segment',
      rank: 'structure',
      fill: 'none',
      d: 'M-40 930 C-40 930 -13.33 930 0 930 C13.33 930 40 930 40 930',
      mirror: false,
      clipTo: 'abdomen',
    },
    // The dorsal stripe: broad, grey-blue on the animal, and the reason the
    // bands read as bands rather than as rings. Drawn on the axis and once.
    {
      id: 'marking',
      rank: 'structure',
      fill: 'pigment-deep',
      d: 'M-22 380 C-47.71 442.07 -47.71 897.93 -22 960 C-16.05 974.37 -7.33 982 0 982 C7.33 982 16.05 974.37 22 960 C47.71 897.93 47.71 442.07 22 380 C16.05 365.63 7.33 358 0 358 C-7.33 358 -16.05 365.63 -22 380 Z',
      mirror: false,
      clipTo: 'abdomen',
    },
    // The thorax, furred and heavy, and the surface the skull is on.
    {
      id: 'thorax',
      rank: 'outline',
      fill: 'pigment-deep',
      d: 'M0 10 C23.33 10 52.59 16.3 70 30 C86.94 43.34 95.51 67.21 104 90 C113.79 116.29 120.06 150.04 122 180 C123.9 209.37 121.1 241.51 116 268 C111.62 290.77 107.35 314.63 96 330 C86.18 343.3 71.26 351.97 56 358 C39.57 364.49 18.67 366 0 366 C-18.67 366 -39.57 364.49 -56 358 C-71.26 351.97 -86.18 343.3 -96 330 C-107.35 314.63 -111.62 290.77 -116 268 C-121.1 241.51 -123.9 209.37 -122 180 C-120.06 150.04 -113.79 116.29 -104 90 C-95.51 67.21 -86.94 43.34 -70 30 C-52.59 16.3 -23.33 10 0 10 Z',
      mirror: false,
    },
    // The skull: the pale ground, then the two sockets, then the mouth.
    //
    // Three shapes rather than one, because a single pale oval on a moth's back
    // is a pale oval. What makes it a skull is that there are two dark spots
    // high in it and one dark mark low and central, and a reader's eye does the
    // rest — which is exactly what the moth is relying on.
    {
      id: 'marking',
      rank: 'structure',
      fill: 'surface',
      d: 'M70 170 C70 218.6 38.66 258 0 258 C-38.66 258 -70 218.6 -70 170 C-70 121.4 -38.66 82 0 82 C38.66 82 70 121.4 70 170 Z',
      mirror: false,
      clipTo: 'thorax',
    },
    {
      id: 'marking',
      rank: 'structure',
      fill: 'ink',
      d: 'M50 124 C50 133.39 41.05 141 30 141 C18.95 141 10 133.39 10 124 C10 114.61 18.95 107 30 107 C41.05 107 50 114.61 50 124 Z',
      clipTo: 'thorax',
    },
    {
      id: 'marking',
      rank: 'structure',
      fill: 'ink',
      d: 'M15 222 C15 236.36 8.28 248 0 248 C-8.28 248 -15 236.36 -15 222 C-15 207.64 -8.28 196 0 196 C8.28 196 15 207.64 15 222 Z',
      mirror: false,
      clipTo: 'thorax',
    },
    {
      id: 'hatching',
      rank: 'detail',
      fill: 'none',
      d: 'M96 120 C96 120 106.21 179.53 106 210 C105.78 241.5 94 306 94 306',
      clipTo: 'thorax',
    },
    {
      id: 'hatching',
      rank: 'detail',
      fill: 'none',
      d: 'M70 46 C70 46 81.3 76.43 82 92 C82.71 107.76 74 140 74 140',
      clipTo: 'thorax',
    },
    {
      id: 'head',
      rank: 'outline',
      fill: 'pigment-deep',
      d: 'M0 -16 C18 -16 41.31 -14.26 54 -4 C66.4 6.02 74.92 27.97 76 44 C77.03 59.3 69.99 78.33 62 90 C55.13 100.04 44.39 107 34 112 C23.71 116.95 11.33 120 0 120 C-11.33 120 -23.71 116.95 -34 112 C-44.39 107 -55.13 100.04 -62 90 C-69.99 78.33 -77.03 59.3 -76 44 C-74.92 27.97 -66.4 6.02 -54 -4 C-41.31 -14.26 -18 -16 0 -16 Z',
      mirror: false,
    },
    {
      id: 'eye',
      rank: 'detail',
      fill: 'ink',
      d: 'M77 46 C77 56.49 67.6 65 56 65 C44.4 65 35 56.49 35 46 C35 35.51 44.4 27 56 27 C67.6 27 77 35.51 77 46 Z',
    },
    // A palp. Large, upturned and scaled, and one of the few Sphingid
    // characters that shows from above — which is why `palp` is in
    // `PLATE_PART_IDS` at all and this is the first plate to use it.
    {
      id: 'palp',
      rank: 'structure',
      fill: 'pigment-deep',
      d: 'M40.48 20.81 C47.92 13.24 54.3 -6.39 53.92 -18.63 C53.59 -29.52 45.76 -43.87 41.38 -49.15 C39.25 -51.71 36.64 -53.76 34.85 -53.38 C33.05 -52.99 31.56 -49.92 30.62 -46.85 C28.92 -41.29 32.66 -29.74 30.08 -21.37 C27.1 -11.69 12.57 -1.88 11.52 7.19 C10.67 14.58 14.36 26.21 19.19 28.48 C24.01 30.75 34.99 26.39 40.48 20.81 Z',
    },
    // The antenna: stout at the base and tapering to a fine point, which is a
    // hawkmoth's and is why the record says `filiform` where the peacock says
    // `clavate`. Three joints, drawn heavier than any other antenna here.
    {
      id: 'antenna',
      rank: 'structure',
      fill: 'pigment-deep',
      d: 'M54.89 23.3 C67.38 16.41 95.59 -20.99 99.34 -33.97 C100.96 -39.56 100.48 -45.33 98.03 -47.34 C95.58 -49.35 89.83 -48.7 84.66 -46.03 C72.65 -39.83 41.45 -4.89 37.11 8.7 C35.06 15.14 35.74 22.45 38.7 24.89 C41.66 27.32 48.97 26.56 54.89 23.3 Z',
    },
    {
      id: 'antenna',
      rank: 'structure',
      fill: 'pigment-deep',
      d: 'M101.49 -40.15 C113.89 -47.42 146.23 -93.08 149.52 -105.69 C150.66 -110.09 150.15 -114.08 148.31 -115.52 C146.47 -116.95 142.48 -116.49 138.48 -114.31 C127.05 -108.07 90.57 -65.64 86.51 -51.85 C84.87 -46.24 85.66 -40.46 88.15 -38.51 C90.65 -36.56 96.44 -37.2 101.49 -40.15 Z',
    },
    {
      id: 'antenna',
      rank: 'detail',
      fill: 'pigment-deep',
      d: 'M151.91 -112.24 C161.9 -119.73 188.58 -173.2 189.69 -180.93 C189.9 -182.39 189.64 -183.33 189.07 -183.69 C188.51 -184.05 187.55 -183.89 186.31 -183.07 C179.78 -178.8 142.65 -131.98 140.09 -119.76 C139.19 -115.42 140.27 -111.35 142.24 -110.09 C144.21 -108.84 148.36 -109.58 151.91 -112.24 Z',
    },
  ],
};
