// Generated from ../landmarks/aglais-io.json by `npm run plate:build`.
//
// Do not edit this file. Edit the landmarks and build again; `npm run
// plate:verify` fails the check if the two drift apart.

import type { SpeciesPlate } from '@/lib/plate';

/**
 * *Aglais io*, upperside, wings spread — the peacock butterfly.
 *
 * Traced from figure 3 of plate VIII of W. E. Kirby's *British and European
 * Butterflies and Moths*, captioned under the old name *Vanessa io*, with the
 * larva beside it as 3a. `references/aglais-io.jpg` is the plate and
 * `references/SOURCES.md` has the provenance.
 *
 * The figure is drawn at an angle across the sheet rather than square to it,
 * which is normal for a book that fits six butterflies on a page and is why
 * nothing here is a coordinate lifted off the scan. What was taken is the
 * wing shape, the eyespot positions and the proportions; the plate is drawn
 * square, because a plate that inherited the page's layout would be a drawing
 * of a book.
 *
 * ## What the drawing has to get right
 *
 * The **eyespots**, and there is nothing else close. Four of them, one to a
 * wing, and they are why the animal is called a peacock: a dark outer ring, a
 * paler inner ring, and a bright off-centre pupil that reads as a highlight.
 * Each is drawn as those three parts rather than as one shape, because a
 * single ellipse is a spot and the ringing is the whole effect. `markings:
 * 'eyespots'` is the only record in the archive that says so, and this is the
 * drawing of that word.
 *
 * Then the **forewing apex**, which on a peacock is squared off and very
 * slightly hooked, with a shallow scoop out of the outer margin below it. A
 * rounded apex turns it into a tortoiseshell — which is figure 2 on the same
 * plate, and the animal it is most often confused with.
 *
 * The **dark border** round both wings, with the paler band just inside it, is
 * drawn as two strips: the margin traced, and a depth inwards. Bands that keep
 * their width round a curve, rather than wedges.
 *
 * ## No legs
 *
 * A nymphalid with its wings spread shows none from above, and
 * `REQUIRED_PARTS.lepidoptera` does not ask for them. This family has only
 * four walking legs anyway — the forelegs are reduced to brushes held against
 * the thorax — and none of that is visible in dorsal view.
 *
 * ## Plate space
 *
 * y = 0 at the front of the head, y = 1000 at the tip of the abdomen. The
 * forewing apex reaches x = 1420 and y = -336; the hindwing reaches y = 1010.
 * The body is a tenth of the span, which is what a nymphalid is.
 */
export const AGLAIS_IO_PLATE: SpeciesPlate = {
  species: 'aglais-io',
  order: 'lepidoptera',
  sex: 'unsexed',
  hallmark: 'the four eyespots, one on each wing, each ringed and lit with a bright pupil',
  reference: {
    title: 'British and European Butterflies and Moths (Macrolepidoptera), plate VIII figure 3',
    artist: 'H. Deuchert and Shirley Slocombe',
    year: 1895,
    source:
      'https://commons.wikimedia.org/wiki/File:British_and_European_butterflies_and_moths_(Macrolepidoptera)_(Plate_VIII)_(6466291101).jpg',
    licence: 'Public domain (PD-old-70-expired)',
  },
  parts: [
    // The hind wing first, so the forewing overlaps it at the base, which is
    // the way round a spread butterfly is put together.
    {
      id: 'hindwing',
      rank: 'outline',
      fill: 'pigment',
      d: 'M80 368 C117.22 336.61 223.7 383.63 300 394 C383.14 405.31 476.37 417.06 560 434 C639.41 450.08 719.76 468.2 790 492 C852.41 513.14 916.26 533.24 962 566 C1001.17 594.06 1039.45 630.14 1054 668 C1067.14 702.19 1065.62 745.51 1054 780 C1041.7 816.52 1010.28 852.06 978 880 C942.89 910.39 894.65 932.9 848 952 C798.99 972.07 744.1 986.33 690 996 C634.83 1005.86 575.7 1011.86 520 1010 C465.75 1008.19 408.55 1000.63 360 986 C316.08 972.76 275.4 954.2 240 930 C205.68 906.54 173.77 878.05 150 844 C125.23 808.51 109.19 764.86 96 720 C81.56 670.89 73.05 615.93 70 560 C66.68 499.08 45.33 397.24 80 368 Z',
    },
    // The venation, as nine strokes fanning from the wing base to the margin.
    // Kirby's lithograph carries the veins as breaks in the colour rather than
    // as lines; drawn as lines here, because an engraving has no other way to
    // say a wing is a membrane on a frame.
    {
      id: 'wing-vein',
      rank: 'detail',
      fill: 'none',
      d: 'M160 420 C160 420 434.45 488.51 560 540 C680.5 589.42 900 720 900 720',
      clipTo: 'hindwing',
    },
    {
      id: 'wing-vein',
      rank: 'detail',
      fill: 'none',
      d: 'M157.5 447.5 C157.5 447.5 422.38 531.84 545 582.5 C660.84 630.36 875 741.25 875 741.25',
      clipTo: 'hindwing',
    },
    {
      id: 'wing-vein',
      rank: 'detail',
      fill: 'none',
      d: 'M155 475 C155 475 410.25 575.33 530 625 C641.2 671.12 850 762.5 850 762.5',
      clipTo: 'hindwing',
    },
    {
      id: 'wing-vein',
      rank: 'detail',
      fill: 'none',
      d: 'M152.5 502.5 C152.5 502.5 398.09 619.04 515 667.5 C621.59 711.68 825 783.75 825 783.75',
      clipTo: 'hindwing',
    },
    {
      id: 'wing-vein',
      rank: 'detail',
      fill: 'none',
      d: 'M150 530 C150 530 385.88 662.98 500 710 C602.04 752.04 800 805 800 805',
      clipTo: 'hindwing',
    },
    {
      id: 'wing-vein',
      rank: 'detail',
      fill: 'none',
      d: 'M147.5 557.5 C147.5 557.5 373.66 707.19 485 752.5 C582.56 792.2 775 826.25 775 826.25',
      clipTo: 'hindwing',
    },
    {
      id: 'wing-vein',
      rank: 'detail',
      fill: 'none',
      d: 'M145 585 C145 585 361.43 751.7 470 795 C563.16 832.16 750 847.5 750 847.5',
      clipTo: 'hindwing',
    },
    {
      id: 'wing-vein',
      rank: 'detail',
      fill: 'none',
      d: 'M142.5 612.5 C142.5 612.5 349.23 796.52 455 837.5 C543.87 871.93 725 868.75 725 868.75',
      clipTo: 'hindwing',
    },
    {
      id: 'wing-vein',
      rank: 'detail',
      fill: 'none',
      d: 'M140 640 C140 640 337.09 841.66 440 880 C524.69 911.55 700 890 700 890',
      clipTo: 'hindwing',
    },
    // The pale band and the dark border, as two strips on one traced margin.
    //
    // The pale one is drawn first and reaches seventy-four units in from the edge;
    // the border is drawn over it and reaches fifty-six. What shows of the
    // wider strip is the band, which is how an engraver would get it and
    // means one measured edge rather than two — the second of which would be
    // the first offset by hand, and wrong by a few units all the way round.
    {
      id: 'wing-marking',
      rank: 'detail',
      fill: 'surface',
      d: 'M794 522 C823.38 511.31 903.36 563.91 944 592 C977.81 615.37 1012.66 640.36 1026 672 C1038.71 702.15 1037.36 745.21 1026 776 C1014.44 807.35 985.35 834.43 956 858 C922.5 884.9 876.17 906.21 832 924 C785.77 942.61 735.06 956.66 684 966 C631.18 975.66 573.9 981.48 520 980 C467.27 978.55 410.46 972.28 364 958 C323.02 945.4 262.16 927.9 254 904 C247.66 885.42 268.49 843.68 286.61 837.57 C308.79 830.1 349.04 875.88 385.74 887.27 C426.63 899.95 475.55 904.85 522.03 906.03 C570.44 907.26 622.86 901.96 670.69 893.21 C716.85 884.76 763.23 871.73 804.36 855.36 C842.39 840.22 882.81 820.68 909.66 800.3 C930.05 784.83 949.12 768.54 956.57 750.4 C962.92 734.94 964.49 715.74 957.81 700.74 C949.68 682.48 926.09 668.33 901.92 652.87 C867.05 630.57 772.88 616.75 762.71 589.06 C755.63 569.81 774.35 529.14 794 522 Z',
      clipTo: 'hindwing',
    },
    {
      id: 'wing-marking',
      rank: 'structure',
      fill: 'pigment-deep',
      d: 'M794 522 C820.97 512.19 903.36 563.91 944 592 C977.81 615.37 1012.66 640.36 1026 672 C1038.71 702.15 1037.36 745.21 1026 776 C1014.44 807.35 985.35 834.43 956 858 C922.5 884.9 876.17 906.21 832 924 C785.77 942.61 735.06 956.66 684 966 C631.18 975.66 573.9 981.48 520 980 C467.27 978.55 410.46 972.28 364 958 C323.02 945.4 261.53 926.05 254 904 C248.91 889.09 264.03 858.68 278.68 853.73 C299.56 846.67 342.71 892.79 380.45 904.47 C422.7 917.54 473.53 922.78 521.54 924.02 C571.29 925.31 624.88 919.89 673.93 910.91 C721.28 902.25 768.71 888.97 811.08 872.05 C850.61 856.27 892.43 836.38 920.93 814.34 C943.54 796.86 964.99 778.03 973.46 756.62 C981.06 737.41 982.59 712.45 974.4 693.75 C964.95 672.19 938.74 655.51 912.16 638.07 C875.8 614.21 779.78 598.57 770.32 572.75 C764.65 557.28 778.31 527.7 794 522 Z',
      clipTo: 'hindwing',
    },
    // The hindwing eyespot: three parts, drawn outward in. A dark outer ring, a
    // paler inner ring, and an off-centre pupil in bare paper.
    //
    // One shape would be a spot. What makes an eyespot is that it is ringed and
    // that the highlight is not in the middle of it, which is the trick every
    // animal with eyespots is playing and the reason they work at all.
    {
      id: 'wing-marking',
      rank: 'structure',
      fill: 'pigment-deep',
      d: 'M856 700 C856 768.48 795.11 824 720 824 C644.89 824 584 768.48 584 700 C584 631.52 644.89 576 720 576 C795.11 576 856 631.52 856 700 Z',
      clipTo: 'hindwing',
    },
    {
      id: 'wing-marking',
      rank: 'structure',
      fill: 'pigment',
      d: 'M812 700 C812 745.29 770.81 782 720 782 C669.19 782 628 745.29 628 700 C628 654.71 669.19 618 720 618 C770.81 618 812 654.71 812 700 Z',
      clipTo: 'hindwing',
    },
    {
      id: 'wing-marking',
      rank: 'detail',
      fill: 'surface',
      d: 'M722 662 C722 678.57 705.88 692 686 692 C666.12 692 650 678.57 650 662 C650 645.43 666.12 632 686 632 C705.88 632 722 645.43 722 662 Z',
      clipTo: 'hindwing',
    },
    // The fore wing. The apex is squared off and faintly hooked and the outer
    // margin is scooped just below it — a rounded apex would make this a small
    // tortoiseshell, which is figure 2 on the same plate.
    {
      id: 'forewing',
      rank: 'outline',
      fill: 'pigment',
      d: 'M80 84 C95.35 46.7 219.53 41.25 300 20 C396.42 -5.46 512.51 -30.53 620 -56 C729.15 -81.86 846.36 -111.4 950 -134 C1041.64 -153.99 1135.43 -171.49 1210 -186 C1266.2 -196.94 1326.69 -228.9 1358 -214 C1381.4 -202.87 1393.72 -168.52 1398 -140 C1403.17 -105.6 1391.74 -58.93 1374 -20 C1353.28 25.46 1314.1 73.97 1272 112 C1226.71 152.92 1167.59 188.18 1108 214 C1046 240.86 978.17 255.4 906 268 C825.37 282.07 732.95 290.92 646 290 C558.29 289.07 467.37 278.74 382 262 C298.84 245.69 190.02 231.84 140 192 C104.97 164.1 68.73 111.39 80 84 Z',
    },
    {
      id: 'wing-vein',
      rank: 'detail',
      fill: 'none',
      d: 'M180 120 C180 120 449.83 30.94 600 -10 C770.26 -56.41 1150 -140 1150 -140',
      clipTo: 'forewing',
    },
    {
      id: 'wing-vein',
      rank: 'detail',
      fill: 'none',
      d: 'M182.5 127 C182.5 127 456.92 51.67 607.5 13.75 C777.04 -28.95 1150 -115 1150 -115',
      clipTo: 'forewing',
    },
    {
      id: 'wing-vein',
      rank: 'detail',
      fill: 'none',
      d: 'M185 134 C185 134 463.97 72.44 615 37.5 C783.72 -1.54 1150 -90 1150 -90',
      clipTo: 'forewing',
    },
    {
      id: 'wing-vein',
      rank: 'detail',
      fill: 'none',
      d: 'M187.5 141 C187.5 141 470.96 93.25 622.5 61.25 C790.32 25.81 1150 -65 1150 -65',
      clipTo: 'forewing',
    },
    {
      id: 'wing-vein',
      rank: 'detail',
      fill: 'none',
      d: 'M190 148 C190 148 477.92 114.1 630 85 C796.82 53.08 1150 -40 1150 -40',
      clipTo: 'forewing',
    },
    {
      id: 'wing-vein',
      rank: 'detail',
      fill: 'none',
      d: 'M192.5 155 C192.5 155 484.83 134.99 637.5 108.75 C803.23 80.26 1150 -15 1150 -15',
      clipTo: 'forewing',
    },
    {
      id: 'wing-vein',
      rank: 'detail',
      fill: 'none',
      d: 'M195 162 C195 162 491.71 155.94 645 132.5 C809.55 107.34 1150 10 1150 10',
      clipTo: 'forewing',
    },
    {
      id: 'wing-vein',
      rank: 'detail',
      fill: 'none',
      d: 'M197.5 169 C197.5 169 498.56 176.93 652.5 156.25 C815.78 134.32 1150 35 1150 35',
      clipTo: 'forewing',
    },
    {
      id: 'wing-vein',
      rank: 'detail',
      fill: 'none',
      d: 'M200 176 C200 176 505.38 197.98 660 180 C821.92 161.18 1150 60 1150 60',
      clipTo: 'forewing',
    },
    // The pale band and the dark border, as two strips on one traced margin.
    //
    // The pale one is drawn first and reaches seventy-four units in from the edge;
    // the border is drawn over it and reaches fifty-six. What shows of the
    // wider strip is the band, which is how an engraver would get it and
    // means one measured edge rather than two — the second of which would be
    // the first offset by hand, and wrong by a few units all the way round.
    {
      id: 'wing-marking',
      rank: 'detail',
      fill: 'surface',
      d: 'M1348 -190 C1361.22 -185.35 1369.34 -160.59 1372 -140 C1375.85 -110.21 1366.78 -63 1350 -26 C1330.32 17.38 1292.49 64.4 1252 100 C1208.87 137.92 1152.77 168.58 1096 192 C1036 216.76 970.08 230.11 900 242 C821.32 255.35 729.95 264.79 646 264 C563.31 263.22 425.93 270.06 400 238 C385.82 220.47 390.34 178.5 407.78 164.41 C439.21 139.03 566.85 189.21 646.7 190 C726.8 190.8 813.6 181.52 887.62 169.04 C952.5 158.11 1013.43 145.82 1067.78 123.59 C1117.71 103.18 1166.34 76.49 1203.13 44.43 C1236.45 15.41 1267.17 -23.77 1282.61 -56.57 C1294.45 -81.73 1301.82 -112.32 1298.61 -130.52 C1296.5 -142.44 1278.89 -149.66 1281.29 -157.98 C1284.9 -170.54 1332.73 -195.37 1348 -190 Z',
      clipTo: 'forewing',
    },
    {
      id: 'wing-marking',
      rank: 'structure',
      fill: 'pigment-deep',
      d: 'M1348 -190 C1360.36 -185.66 1369.34 -160.59 1372 -140 C1375.85 -110.21 1366.78 -63 1350 -26 C1330.32 17.38 1292.49 64.4 1252 100 C1208.87 137.92 1152.77 168.58 1096 192 C1036 216.76 970.08 230.11 900 242 C821.32 255.35 729.95 264.79 646 264 C563.31 263.22 423.64 267.23 400 238 C388.75 224.09 392.03 193.51 405.89 182.31 C434.69 159.04 565.99 207.21 646.53 208 C727.57 208.8 815.48 199.48 890.63 186.79 C956.78 175.62 1018.91 163.08 1074.64 140.23 C1126.24 119.08 1176.68 91.44 1215.02 57.95 C1250.08 27.32 1282.53 -13.72 1299 -49.13 C1312.06 -77.2 1319.82 -111.79 1316.46 -132.83 C1314.22 -146.85 1294.72 -156.74 1297.51 -165.77 C1300.91 -176.72 1335.58 -194.36 1348 -190 Z',
      clipTo: 'forewing',
    },
    {
      id: 'wing-marking',
      rank: 'structure',
      fill: 'pigment-deep',
      d: 'M1252 -16 C1252 40.33 1201.86 86 1140 86 C1078.14 86 1028 40.33 1028 -16 C1028 -72.33 1078.14 -118 1140 -118 C1201.86 -118 1252 -72.33 1252 -16 Z',
      clipTo: 'forewing',
    },
    {
      id: 'wing-marking',
      rank: 'structure',
      fill: 'pigment',
      d: 'M1214 -16 C1214 20.45 1180.87 50 1140 50 C1099.13 50 1066 20.45 1066 -16 C1066 -52.45 1099.13 -82 1140 -82 C1180.87 -82 1214 -52.45 1214 -16 Z',
      clipTo: 'forewing',
    },
    {
      id: 'wing-marking',
      rank: 'detail',
      fill: 'surface',
      d: 'M1138 -52 C1138 -37.64 1124.57 -26 1108 -26 C1091.43 -26 1078 -37.64 1078 -52 C1078 -66.36 1091.43 -78 1108 -78 C1124.57 -78 1138 -66.36 1138 -52 Z',
      clipTo: 'forewing',
    },
    // The abdomen. Stout for a butterfly and short — a peacock overwinters as
    // an adult and carries the fat to do it.
    {
      id: 'abdomen',
      rank: 'outline',
      fill: 'pigment',
      d: 'M0 364 C17.33 364 41.05 367.08 52 382 C69.35 405.63 56.2 472.3 56 520 C55.78 571.37 52.73 627.55 50 680 C47.35 730.83 44.05 783.91 40 830 C36.53 869.54 33.27 911.35 28 940 C24.55 958.78 22.38 975.67 16 986 C11.73 992.91 5.33 1000 0 1000 C-5.33 1000 -11.73 992.91 -16 986 C-22.38 975.67 -24.55 958.78 -28 940 C-33.27 911.35 -36.53 869.54 -40 830 C-44.05 783.91 -47.35 730.83 -50 680 C-52.73 627.55 -55.78 571.37 -56 520 C-56.2 472.3 -69.35 405.63 -52 382 C-41.05 367.08 -17.33 364 0 364 Z',
      mirror: false,
    },
    {
      id: 'abdomen-segment',
      rank: 'detail',
      fill: 'none',
      d: 'M-52 470 C-52 470 -17.33 476 0 476 C17.33 476 52 470 52 470',
      mirror: false,
    },
    {
      id: 'abdomen-segment',
      rank: 'detail',
      fill: 'none',
      d: 'M-48 580 C-48 580 -16 586 0 586 C16 586 48 580 48 580',
      mirror: false,
    },
    {
      id: 'abdomen-segment',
      rank: 'detail',
      fill: 'none',
      d: 'M-42 690 C-42 690 -14 696 0 696 C14 696 42 690 42 690',
      mirror: false,
    },
    {
      id: 'abdomen-segment',
      rank: 'detail',
      fill: 'none',
      d: 'M-34 800 C-34 800 -11.33 806 0 806 C11.33 806 34 800 34 800',
      mirror: false,
    },
    {
      id: 'abdomen-segment',
      rank: 'detail',
      fill: 'none',
      d: 'M-26 900 C-26 900 -8.67 906 0 906 C8.67 906 26 900 26 900',
      mirror: false,
    },
    // The thorax, furred, and drawn once on the axis. The three hatching
    // strokes are the fur; a filled shape would be a beetle's pronotum.
    {
      id: 'thorax',
      rank: 'outline',
      fill: 'pigment-deep',
      d: 'M0 8 C24.67 8 56.7 21.83 74 40 C91.81 58.71 97.91 91.36 104 120 C110.59 151.02 111.01 188.57 110 220 C109.09 248.2 105.89 276.51 100 300 C95.1 319.53 90.36 339.05 80 352 C70.87 363.41 57.17 370.34 44 376 C30.55 381.78 14.67 386 0 386 C-14.67 386 -30.55 381.78 -44 376 C-57.17 370.34 -70.87 363.41 -80 352 C-90.36 339.05 -95.1 319.53 -100 300 C-105.89 276.51 -109.09 248.2 -110 220 C-111.01 188.57 -110.59 151.02 -104 120 C-97.91 91.36 -91.81 58.71 -74 40 C-56.7 21.83 -24.67 8 0 8 Z',
      mirror: false,
    },
    {
      id: 'hatching',
      rank: 'detail',
      fill: 'none',
      d: 'M24 70 C24 70 13.51 157.55 14 200 C14.47 240.82 26 320 26 320',
      clipTo: 'thorax',
    },
    {
      id: 'hatching',
      rank: 'detail',
      fill: 'none',
      d: 'M54 78 C54 78 64.23 164.77 64 206 C63.79 244.59 54 318 54 318',
      clipTo: 'thorax',
    },
    {
      id: 'hatching',
      rank: 'detail',
      fill: 'none',
      d: 'M84 110 C84 110 92.78 174.56 92 206 C91.25 236.53 80 296 80 296',
      clipTo: 'thorax',
    },
    {
      id: 'head',
      rank: 'outline',
      fill: 'pigment-deep',
      d: 'M0 -30 C20.67 -30 47.95 -21.24 62 -8 C75.01 4.26 86.32 30.53 84 44 C82.24 54.23 70.36 61.32 62 68 C53.68 74.64 44.13 80.34 34 84 C23.52 87.79 11.33 90 0 90 C-11.33 90 -23.52 87.79 -34 84 C-44.13 80.34 -53.68 74.64 -62 68 C-70.36 61.32 -82.24 54.23 -84 44 C-86.32 30.53 -75.01 4.26 -62 -8 C-47.95 -21.24 -20.67 -30 0 -30 Z',
      mirror: false,
    },
    {
      id: 'eye',
      rank: 'detail',
      fill: 'ink',
      d: 'M90 34 C90 46.15 79.25 56 66 56 C52.75 56 42 46.15 42 34 C42 21.85 52.75 12 66 12 C79.25 12 90 21.85 90 34 Z',
    },
    // A clubbed antenna, which is what puts this animal with the butterflies
    // rather than the moths — and the character that separates it from the
    // death's-head hawkmoth two accessions later, whose antennae taper to a
    // point. Two strokes for the shaft and a filled club at the end.
    {
      id: 'antenna',
      rank: 'structure',
      fill: 'none',
      d: 'M40 30 C40 30 98.41 -20.77 130 -46 C163.54 -72.79 236 -126 236 -126',
    },
    {
      id: 'antenna',
      rank: 'structure',
      fill: 'none',
      d: 'M236 -126 C236 -126 279.85 -161.89 300 -176 C316.82 -187.78 348 -206 348 -206',
    },
    {
      id: 'antenna',
      rank: 'detail',
      fill: 'pigment-deep',
      d: 'M364.35 -191.02 C377.72 -195.02 398.55 -216.24 404.82 -227.87 C408.72 -235.11 411.07 -244.78 408.13 -248.82 C405.19 -252.87 395.27 -253.61 387.18 -252.13 C374.18 -249.75 347.58 -236.47 339.65 -224.98 C333.81 -216.53 330.9 -201.31 335.02 -195.65 C339.13 -189.99 354.51 -188.07 364.35 -191.02 Z',
    },
  ],
};
