// Generated from ../landmarks/anoplognathus-viridiaeneus.json by `npm run plate:build`.
//
// Do not edit this file. Edit the landmarks and build again; `npm run
// plate:verify` fails the check if the two drift apart.

import type { SpeciesPlate } from '@/lib/plate';

/**
 * *Anoplognathus viridiaeneus*, dorsal - the king Christmas beetle.
 *
 * Traced from plate 1 of Edward Donovan's *An epitome of the natural history
 * of the insects of New Holland* (1805), where the animal is figured and named
 * *Melolontha viridi-aenea* - the description Donovan published it under, and
 * the reason his plate is the type figure for the species.
 * `references/anoplognathus-viridiaeneus.jpg` is that figure, cut from the
 * sheet and turned upright; the whole plate carries nine beetles and this is
 * the large one in the middle.
 *
 * ## What identifies it
 *
 * Size and shape, before colour. It is one of the largest Christmas beetles -
 * 28 to 34 mm - and the outline is one unbroken oval from the front of the
 * clypeus to the apex of the wing cases, because the pronotum is at its widest
 * exactly where the elytra begin. Then the **pygidium**, uncovered behind the
 * wing cases, and the broad squared **clypeus** at the front. All three are
 * drawn.
 *
 * The colour is not drawn and cannot be: red-brown under a gold-green sheen
 * that shifts with the angle it is held at. `morphology.colourFamily` says
 * `metallic`, which is where that fact belongs - the same call the rose chafer
 * made.
 *
 * ## The figure leans, and the plate does not
 *
 * Donovan's beetle is rolled onto its left side by something like twenty
 * degrees, and cocks its head a few more. A roll about the long axis
 * foreshortens width and leaves length alone, so the figure measures 0.48 as
 * wide as it is long against the 0.57 the published measurements give - 16 to
 * 19.5 mm across at 28 to 34 mm long. Every x measured off the reference is
 * therefore multiplied by 1.19, the factor that restores that ratio, and the
 * head is drawn square.
 *
 * Both corrections are written down rather than quietly applied. A reader
 * checking this plate against the reference will measure the same 0.48 and is
 * owed the reason the numbers here differ. It is the same bargain the field
 * cricket's plate struck - arrangement off the reference, proportions off the
 * published measurements - and it is struck for the same reason.
 *
 * ## Plate space
 *
 * y = 0 at the front margin of the clypeus, y = 1000 at the tip of the
 * pygidium, so the wing cases end at about y = 976 and the last stretch is
 * abdomen - exactly as on the rose chafer. The middle legs reach past x = 570
 * and the fore tarsi above y = -100.
 */
export const ANOPLOGNATHUS_VIRIDIAENEUS_PLATE: SpeciesPlate = {
  species: 'anoplognathus-viridiaeneus',
  order: 'coleoptera',
  sex: 'unsexed',
  hallmark:
    'the unbroken oval of pronotum and wing cases, and the hairy pygidium left uncovered behind them',
  reference: {
    title:
      'Melolontha viridi-aenea, from An epitome of the natural history of the insects of New Holland, plate 1',
    artist: 'Edward Donovan',
    year: 1805,
    source: 'https://archive.org/details/epitomeofnatura00dono',
    licence: 'Public domain (published 1805, author died 1837)',
  },
  parts: [
    // Legs first, so they pass under the wing cases.
    //
    // A Christmas beetle is a heavy animal on stout legs, and the tibiae
    // carry a fringe of stiff spines that Donovan draws one by one. They are
    // not drawn here: at eighty pixels a spine is a burr on the outline and
    // six burred limbs read as a smudge. The femora are measured at about
    // eight per cent of the width across the wing cases rather than the six
    // CLAUDE.md gives as usual, which is what the reference shows and what
    // separates a scarab's leg from a ground beetle's.
    {
      id: 'hindleg-femur',
      rank: 'structure',
      fill: 'pigment-deep',
      d: 'M150.82 761.09 C168.34 778.79 223.18 791.06 260.27 805.44 C298.16 820.14 352.68 848.84 375.83 848.3 C385.9 848.07 395.24 844.27 397.3 839.17 C399.36 834.07 395.26 824.85 388.17 817.7 C371.93 801.29 312.61 785.2 275.73 768.56 C239.64 752.26 193.99 719.67 169.18 718.91 C156.13 718.51 141.97 723.79 138.91 730.82 C135.85 737.85 141.63 751.8 150.82 761.09 Z',
    },
    {
      id: 'hindleg-tibia',
      rank: 'structure',
      fill: 'pigment-deep',
      d: 'M373.93 847.39 C388.98 866.2 453.13 889.67 490.73 910.55 C526.29 930.29 573.88 966.57 593.84 969.3 C601.39 970.33 608.25 968.59 610.3 965.16 C612.35 961.73 610.64 954.86 606.16 948.7 C594.29 932.37 540.2 906.53 505.27 885.45 C468.32 863.16 414 821.63 390.07 818.61 C380.05 817.34 370.29 820.14 367.61 824.93 C364.92 829.73 367.63 839.51 373.93 847.39 Z',
    },
    {
      id: 'hindleg-tarsus',
      rank: 'detail',
      fill: 'pigment-deep',
      d: 'M593.16 965.6 C598.48 978.74 636.87 1016.31 649.24 1021.55 C653.92 1023.54 658.64 1023.61 660.55 1021.76 C662.47 1019.91 662.57 1015.19 660.76 1010.45 C655.96 997.9 619.78 958.18 606.84 952.4 C601.51 950.02 595.68 949.96 593.4 952.16 C591.12 954.36 590.97 960.18 593.16 965.6 Z',
    },
    {
      id: 'hindleg-tarsus',
      rank: 'detail',
      fill: 'pigment-deep',
      d: 'M656.27 1034.33 C658.6 1046.44 685.98 1086.05 695.54 1092.52 C698.99 1094.86 702.7 1095.64 704.52 1094.46 C706.34 1093.29 707.17 1089.6 706.46 1085.48 C704.53 1074.11 679.78 1032.8 669.73 1025.67 C665.69 1022.81 660.91 1021.83 658.67 1023.27 C656.43 1024.72 655.34 1029.47 656.27 1034.33 Z',
    },
    {
      id: 'hindleg-tarsus',
      rank: 'detail',
      fill: 'ink',
      d: 'M700.19 1104.91 C701.17 1114.41 721.6 1146.7 727.32 1151.34 C728.92 1152.64 730.45 1153.13 731.34 1152.68 C732.24 1152.24 732.76 1150.72 732.68 1148.66 C732.4 1141.31 718.82 1105.58 711.81 1099.09 C708.92 1096.41 705.03 1095.22 703.09 1096.19 C701.16 1097.16 699.78 1100.98 700.19 1104.91 Z',
    },
    {
      id: 'midleg-femur',
      rank: 'structure',
      fill: 'pigment-deep',
      d: 'M133.74 416.13 C156.96 434.09 231.34 442.24 279.74 454.3 C327.35 466.16 396.29 491.77 421.81 487.96 C432.02 486.44 440.56 481.51 441.96 476.19 C443.36 470.87 438.33 462.37 430.19 456.04 C409.85 440.22 337.18 429.61 290.26 415.7 C242.55 401.57 175.39 368.73 146.26 371.87 C132.72 373.32 119.95 380.36 117.87 387.74 C115.78 395.12 122.96 407.8 133.74 416.13 Z',
    },
    {
      id: 'midleg-tibia',
      rank: 'structure',
      fill: 'pigment-deep',
      d: 'M420.83 487.67 C437.54 501.83 494.33 510.87 530.53 521.79 C565.83 532.44 616.35 554.29 635.37 552.44 C642.87 551.71 649.23 548.44 650.44 544.63 C651.65 540.82 648.33 534.48 642.63 529.56 C628.17 517.1 574.25 506.25 539.47 494.21 C503.79 481.85 453.01 454.91 431.17 456.33 C421.33 456.97 412.06 461.6 410.33 466.83 C408.61 472.05 413.29 481.29 420.83 487.67 Z',
    },
    {
      id: 'midleg-tarsus',
      rank: 'detail',
      fill: 'pigment-deep',
      d: 'M635.9 549.98 C644.97 557.82 683.01 569.39 694.39 568.56 C699.28 568.21 703.69 566.13 704.56 563.61 C705.43 561.09 703.24 556.73 699.61 553.44 C691.16 545.77 654.07 531.44 642.1 532.02 C636.5 532.29 631.05 534.91 630.02 537.9 C628.99 540.9 631.66 546.31 635.9 549.98 Z',
    },
    {
      id: 'midleg-tarsus',
      rank: 'detail',
      fill: 'pigment-deep',
      d: 'M703.96 574.73 C712.39 580.98 747.58 588.74 757.34 587.28 C761.34 586.69 764.73 584.75 765.28 582.66 C765.84 580.57 763.84 577.21 760.66 574.72 C752.89 568.63 718.46 558 708.04 559.27 C703.31 559.84 698.95 562.38 698.27 564.96 C697.58 567.54 700.13 571.9 703.96 574.73 Z',
    },
    {
      id: 'midleg-tarsus',
      rank: 'detail',
      fill: 'ink',
      d: 'M768.41 591.47 C775.99 595.08 806.56 594.18 812.73 591.99 C814.64 591.31 815.9 590.27 815.99 589.27 C816.08 588.28 815.03 587.02 813.27 586.01 C807.6 582.74 777.7 576.35 769.59 578.53 C765.9 579.52 762.72 582.25 762.53 584.41 C762.33 586.57 764.96 589.83 768.41 591.47 Z',
    },
    {
      id: 'foreleg-femur',
      rank: 'structure',
      fill: 'pigment-deep',
      d: 'M132.49 274.56 C152.52 264.4 178.75 221.58 198.83 194.88 C217.65 169.85 245.87 137.75 249.95 119.4 C251.98 110.26 250.72 100.19 246.4 97.05 C242.08 93.92 232.09 95.85 224.05 100.6 C208.08 110.03 189.14 147.76 169.17 171.12 C147.86 196.06 107.03 224.56 99.51 245.44 C95.36 256.98 95.94 271.64 101.44 276.49 C106.93 281.34 121.52 280.13 132.49 274.56 Z',
    },
    // The fore tibia, toothed on its outer edge for digging. Drawn as a taper
    // rather than as three separate spurs, for the reason given above the hind
    // femur: the widening towards the tip is what actually reads.
    {
      id: 'foreleg-tibia',
      rank: 'structure',
      fill: 'pigment-deep',
      d: 'M252.43 114.25 C262.02 101.56 265.54 67.45 269.7 43.87 C273.82 20.58 281.12 -12.64 277.38 -26.35 C275.59 -32.93 271.44 -38.83 267.65 -39.38 C263.86 -39.93 258.19 -35.42 254.62 -29.65 C247.26 -17.77 247.75 15.71 242.3 38.13 C236.77 60.85 219.86 90.2 221.57 105.75 C222.54 114.55 227.61 124.01 232.75 125.43 C237.89 126.84 247.07 121.34 252.43 114.25 Z',
    },
    {
      id: 'foreleg-tarsus',
      rank: 'detail',
      fill: 'pigment-deep',
      d: 'M275.34 -29.76 C277.44 -40.56 269.73 -73.78 263.86 -82.48 C261.17 -86.47 257.14 -89.36 254.52 -88.86 C251.9 -88.37 249.19 -84.21 248.14 -79.52 C245.85 -69.27 250.77 -35.53 256.66 -26.24 C259.6 -21.6 264.65 -18.08 267.76 -18.66 C270.87 -19.25 274.29 -24.37 275.34 -29.76 Z',
    },
    {
      id: 'foreleg-tarsus',
      rank: 'detail',
      fill: 'pigment-deep',
      d: 'M259.48 -95.82 C259.68 -106.54 245.07 -141.04 238.08 -148.29 C235.27 -151.22 231.73 -152.85 229.71 -152.08 C227.68 -151.32 226.1 -147.76 225.92 -143.71 C225.46 -133.64 237.29 -98.09 244.52 -90.18 C247.75 -86.64 252.33 -84.57 254.82 -85.52 C257.32 -86.46 259.4 -91.04 259.48 -95.82 Z',
    },
    {
      id: 'foreleg-tarsus',
      rank: 'detail',
      fill: 'ink',
      d: 'M232.71 -162.11 C231.42 -171.15 211.28 -200.2 205.63 -204.44 C203.99 -205.67 202.44 -206.11 201.56 -205.63 C200.69 -205.15 200.22 -203.61 200.37 -201.56 C200.87 -194.52 214.39 -161.86 221.29 -155.89 C224.25 -153.33 228.21 -152.26 230.11 -153.29 C232.01 -154.33 233.26 -158.25 232.71 -162.11 Z',
    },
    // The pygidium - the last abdominal segment, left uncovered because a
    // chafer's wing cases stop short of it. Bright green on the living animal
    // and clothed in pale hair, which is why Donovan gives it a colour of its
    // own. Drawn behind the elytra so they overlap its front edge, exactly as
    // the reference shows.
    //
    // It is also what y = 1000 is measured to. The elytral apex is at about
    // y = 950 and the last fifty units of this plate are abdomen. Fifty rather
    // than the twenty-eight of the first pass, which the wing cases covered
    // entirely - a pygidium that does not clear them is not drawn at all.
    {
      id: 'abdomen',
      rank: 'outline',
      fill: 'pigment-deep',
      d: 'M0 841 C38.67 841 96.95 849.11 116 870 C130.12 885.49 131.66 916 126 935 C120.34 954.01 101.03 972.02 82 984 C60.33 997.65 27.33 1008 0 1008 C-27.33 1008 -60.33 997.65 -82 984 C-101.03 972.02 -120.34 954.01 -126 935 C-131.66 916 -130.12 885.49 -116 870 C-96.95 849.11 -38.67 841 0 841 Z',
      mirror: false,
    },
    // One wing case. The suture between the pair is the midline, so the inner
    // edge of this shape is the axis and the renderer's reflection draws the
    // other one against it.
    {
      id: 'elytron',
      rank: 'outline',
      fill: 'pigment',
      d: 'M0 370 C0 343.26 80.33 369.89 119 372 C155.91 374.02 204.2 367.02 227 382 C244.02 393.18 248.64 413.73 256 435 C265.62 462.83 269.29 500.31 273 537 C277.28 579.4 279.26 632.18 278 675 C276.9 712.43 275.31 749.49 268 780 C262.01 805.02 253.85 826.18 242 846 C230.39 865.42 216.57 885.26 198 898 C178.36 911.47 153.75 916.95 126 923 C90.23 930.79 0 960.92 0 935 C0 880.23 0 428.25 0 370 Z',
    },
    // The striae. An Anoplognathus is polished rather than deeply grooved, so
    // what shows is three shallow lines and the raised shoulder - not the eight
    // sharp furrows a ground beetle gets.
    {
      id: 'stria',
      rank: 'structure',
      fill: 'none',
      d: 'M39 455 C39 455 32.79 600.67 34 667 C35.07 725.74 44 833 44 833',
      clipTo: 'elytron',
    },
    {
      id: 'stria',
      rank: 'structure',
      fill: 'none',
      d: 'M123.5 451 C123.5 451 145.08 602.64 140.5 671 C136.43 731.77 104 841.5 104 841.5',
      clipTo: 'elytron',
    },
    {
      id: 'stria',
      rank: 'structure',
      fill: 'none',
      d: 'M208 447 C208 447 256.58 605.4 247 675 C238.24 738.69 164 850 164 850',
      clipTo: 'elytron',
    },
    {
      id: 'hatching',
      rank: 'detail',
      fill: 'none',
      d: 'M24 585 C24 585 17.77 686.15 19 732 C20.08 772.45 29 846 29 846',
      clipTo: 'elytron',
    },
    {
      id: 'hatching',
      rank: 'detail',
      fill: 'none',
      d: 'M58 650 C58 650 59.06 738.28 59.33 776.67 C59.56 808.66 59.67 864.67 59.67 864.67',
      clipTo: 'elytron',
    },
    {
      id: 'hatching',
      rank: 'detail',
      fill: 'none',
      d: 'M92 715 C92 715 100.85 790.7 99.67 821.33 C98.76 844.83 90.33 883.33 90.33 883.33',
      clipTo: 'elytron',
    },
    {
      id: 'hatching',
      rank: 'detail',
      fill: 'none',
      d: 'M126 780 C126 780 143.61 843.93 140 866 C137.53 881.08 121 902 121 902',
      clipTo: 'elytron',
    },
    // The swell of the wing case, and the correction that took two passes.
    //
    // It was first drawn as a long panel of bare paper clipped to the elytron -
    // the gloss every figure of a polished scarab shows. On the page that read
    // as a pale *marking*, which is the one thing this animal has not got, and
    // a plate suggesting the rose chafer's flecks on an unmarked beetle keys a
    // reader to the wrong species. So the highlight became its opposite: five
    // fine strokes crowding the outer margin, leaving the crown of the case
    // bare. Shading is what an engraver had, and it cannot be mistaken for a
    // mark on the animal.
    {
      id: 'hatching',
      rank: 'detail',
      fill: 'none',
      d: 'M160 472 C160 472 189.12 581.12 198 634 C206.34 683.66 213 780 213 780',
      clipTo: 'elytron',
    },
    {
      id: 'hatching',
      rank: 'detail',
      fill: 'none',
      d: 'M140.5 512.5 C140.5 512.5 167.02 622.9 176.25 674.75 C184.63 721.84 194.75 810.5 194.75 810.5',
      clipTo: 'elytron',
    },
    {
      id: 'hatching',
      rank: 'detail',
      fill: 'none',
      d: 'M121 553 C121 553 144.82 664.76 154.5 715.5 C162.98 759.96 176.5 841 176.5 841',
      clipTo: 'elytron',
    },
    {
      id: 'hatching',
      rank: 'detail',
      fill: 'none',
      d: 'M101.5 593.5 C101.5 593.5 122.52 706.73 132.75 756.25 C141.38 798.04 158.25 871.5 158.25 871.5',
      clipTo: 'elytron',
    },
    {
      id: 'hatching',
      rank: 'detail',
      fill: 'none',
      d: 'M82 634 C82 634 100.09 748.84 111 797 C119.85 836.06 140 902 140 902',
      clipTo: 'elytron',
    },
    // The suture, drawn once on the axis. Reflecting it would lay a second
    // copy a hair off the first and show as a doubled line down the back.
    {
      id: 'seam',
      rank: 'structure',
      fill: 'none',
      d: 'M0 394 C0 394 0 581.08 0 675 C0 769.42 0 959 0 959',
      mirror: false,
    },
    {
      id: 'scutellum',
      rank: 'structure',
      fill: 'pigment-deep',
      d: 'M0 374 C25.67 374 70.42 382.42 77 398 C83.25 412.81 58.15 446.15 44 463 C31.71 477.64 14.67 496 0 496 C-14.67 496 -31.71 477.64 -44 463 C-58.15 446.15 -83.25 412.81 -77 398 C-70.42 382.42 -25.67 374 0 374 Z',
      mirror: false,
    },
    // The pronotum: broad, strongly convex, narrowing forward to about two
    // thirds of its basal width. It is widest at its own base, where it meets
    // the wing cases - which is what makes the outline of this animal a single
    // unbroken oval from the head backwards, and is the first thing to get
    // right about it.
    {
      id: 'pronotum',
      rank: 'outline',
      fill: 'pigment',
      d: 'M0 163 C30.67 163 64.78 159.66 92 171 C119.52 182.47 145.41 207.96 164 232 C182.15 255.47 191.69 288.79 203 313 C212.1 332.47 232.84 355.65 227 366 C220.71 377.15 187.17 372.04 160 374 C118.15 377.02 53.33 378 0 378 C-53.33 378 -118.15 377.02 -160 374 C-187.17 372.04 -220.71 377.15 -227 366 C-232.84 355.65 -212.1 332.47 -203 313 C-191.69 288.79 -182.15 255.47 -164 232 C-145.41 207.96 -119.52 182.47 -92 171 C-64.78 159.66 -30.67 163 0 163 Z',
      mirror: false,
    },
    {
      id: 'hatching',
      rank: 'detail',
      fill: 'none',
      d: 'M24 220 C24 220 24 313 24 313',
      clipTo: 'pronotum',
    },
    {
      id: 'hatching',
      rank: 'detail',
      fill: 'none',
      d: 'M66 224 C66 224 77.33 317 77.33 317',
      clipTo: 'pronotum',
    },
    {
      id: 'hatching',
      rank: 'detail',
      fill: 'none',
      d: 'M108 228 C108 228 130.67 321 130.67 321',
      clipTo: 'pronotum',
    },
    {
      id: 'hatching',
      rank: 'detail',
      fill: 'none',
      d: 'M150 232 C150 232 184 325 184 325',
      clipTo: 'pronotum',
    },
    // The head, which on this animal is mostly clypeus: a broad plate, squared
    // across the front and turned up at the margin, and what a Christmas
    // beetle pushes soil with.
    //
    // Donovan draws it cocked a few degrees to the animal's right. It is drawn
    // square here, because a plate that inherited the tilt would be drawing
    // that specimen's pose rather than the species.
    {
      id: 'head',
      rank: 'outline',
      fill: 'pigment-deep',
      d: 'M0 0 C24.33 0 55.84 -6.81 73 4 C88.6 13.83 95.66 38.11 102 57 C108.4 76.08 113.6 100.02 111 118 C108.77 133.39 104.53 149.8 92 159 C74.05 172.18 30.67 171 0 171 C-30.67 171 -74.05 172.18 -92 159 C-104.53 149.8 -108.77 133.39 -111 118 C-113.6 100.02 -108.4 76.08 -102 57 C-95.66 38.11 -88.6 13.83 -73 4 C-55.84 -6.81 -24.33 0 0 0 Z',
      mirror: false,
    },
    {
      id: 'eye',
      rank: 'detail',
      fill: 'ink',
      d: 'M114.96 101.79 C119.36 110.08 112.66 122.27 99.98 129.01 C87.3 135.75 73.45 134.5 69.04 126.21 C64.64 117.92 71.34 105.73 84.02 98.99 C96.7 92.25 110.55 93.5 114.96 101.79 Z',
    },
    // A lamellate club - three flat plates that open like a fan, and the
    // character that puts this beetle in the Scarabaeoidea. Drawn as one filled
    // club with two lines across it, because three separate lamellae at plate
    // size is three smudges. The record says `lamellate`; this is the drawing
    // of that word.
    {
      id: 'antenna',
      rank: 'structure',
      fill: 'none',
      d: 'M82 85 C82 85 115.72 71.34 131 65 C144.49 59.41 169 49 169 49',
    },
    {
      id: 'antenna',
      rank: 'detail',
      fill: 'pigment-deep',
      d: 'M181.88 57.76 C192.27 56.21 206.07 44.83 216.75 37.4 C226.8 30.4 239.63 22.76 244.38 14.7 C247.78 8.93 250.16 0.19 247.7 -3.38 C245.24 -6.95 236.2 -7.82 229.62 -6.7 C220.55 -5.16 209.5 4.35 199.25 10.6 C188.35 17.26 172.07 23.76 166.12 32.24 C161.76 38.44 158.61 48.63 161.24 52.88 C163.87 57.14 174.35 58.89 181.88 57.76 Z',
    },
    {
      id: 'antenna',
      rank: 'detail',
      fill: 'none',
      d: 'M189 12 C189 12 208 45 208 45',
    },
    {
      id: 'antenna',
      rank: 'detail',
      fill: 'none',
      d: 'M218 -4 C218 -4 237 28 237 28',
    },
  ],
};
