// Generated from ../landmarks/bombus-terrestris.json by `npm run plate:build`.
//
// Do not edit this file. Edit the landmarks and build again; `npm run
// plate:verify` fails the check if the two drift apart.

import type { SpeciesPlate } from '@/lib/plate';

/**
 * *Bombus terrestris*, female, dorsal — the buff-tailed bumblebee.
 *
 * Traced from figure 3 of Robert Morgan's plate 52 for Edward Saunders's *The
 * Hymenoptera Aculeata of the British Islands* (1896), where the caption gives
 * both the species and the sex. `references/bombus-terrestris.jpg` is the
 * sheet; the queen is the large figure on the right of the middle row.
 *
 * ## Three bands, and the last one is the name
 *
 * A collar across the front of the thorax, a band across the second segment of
 * the abdomen, and a pale tail. British bumblebees are keyed out on that
 * sequence before anything else, and *terrestris* is the one whose tail is buff
 * rather than white — a distinction this plate cannot make, because the tail is
 * drawn as bare paper and bare paper is whatever the season's surface token
 * says it is. The record carries the word `buff-tailed`; the drawing carries
 * the fact that there is a tail band at all.
 *
 * ## Hair as hatching
 *
 * The whole animal is furred, and fur is the thing an engraving is least able
 * to copy and most able to *suggest*. Two fans of strokes, one over the thorax
 * and one over the abdomen, both clipped to the surface they sit on, both at
 * `detail` weight so they drop out first at thumbnail size and leave a clean
 * silhouette. Drawing every hair would produce a grey rectangle at eighty
 * pixels and an unmaintainable file at six hundred.
 *
 * ## No waist to speak of
 *
 * A bumblebee has one — it is a wasp-waisted insect like every aculeate — but
 * the fur closes over it and nothing of it shows from above. The thorax and the
 * abdomen are drawn meeting, which is what the reference shows, and the
 * hornet is the plate in this collection where the gap is the point.
 *
 * ## Plate space
 *
 * y = 0 at the top of the head, y = 1000 at the tip of the abdomen. The wings
 * reach past x = 830 and the hind tarsi below y = 1200.
 */
export const BOMBUS_TERRESTRIS_PLATE: SpeciesPlate = {
  species: 'bombus-terrestris',
  order: 'hymenoptera',
  sex: 'female',
  hallmark: 'two ochre bands and the pale tail the animal is named for',
  reference: {
    title:
      'Bombus terrestris, from The Hymenoptera Aculeata of the British Islands, plate 52, fig. 3',
    artist: 'Robert Morgan',
    year: 1896,
    source: 'https://commons.wikimedia.org/wiki/File:SaundersHymenopteraAculeataPlate52.jpg',
    licence: 'Public domain (PD-US-expired, PD-old-70)',
  },
  parts: [
    // Legs first, under the wings and the fur.
    //
    // The hind tibia is the exception to the four-per-cent rule CLAUDE.md
    // records: on a female *Bombus* it is broadened into the corbicula, the
    // bare polished plate she carries pollen on, and drawing it at the width of
    // a wasp's tibia would delete the one structure that says this animal is a
    // worker or a queen rather than a male.
    {
      id: 'hindleg-femur',
      rank: 'structure',
      fill: 'pigment-deep',
      d: 'M218.64 613.96 C229.27 633.25 277 659.47 305.83 682.35 C334.46 705.07 371.73 744.93 391.04 750.76 C399.26 753.23 407.77 752.55 410.76 748.96 C413.74 745.38 412.88 736.88 408.96 729.24 C399.74 711.28 354.01 681.43 326.17 657.65 C298.14 633.7 262.44 592.55 241.36 586.04 C231.27 582.92 219.83 583.98 216.04 588.64 C212.25 593.29 213.54 604.71 218.64 613.96 Z',
    },
    {
      id: 'hindleg-tibia',
      rank: 'structure',
      fill: 'pigment-deep',
      d: 'M385.38 743.36 C380.88 765.65 397.38 826.31 405.48 866.68 C413.41 906.2 420.24 964.12 433.29 983.12 C439.14 991.63 447.55 997.75 453.12 996.71 C458.69 995.67 464.32 986.94 466.71 976.88 C472.07 954.35 459.04 896.94 450.52 857.32 C441.81 816.85 428.45 754.84 414.62 736.64 C408.94 729.18 401.52 724.26 396.64 725.38 C391.77 726.5 387.23 734.17 385.38 743.36 Z',
    },
    {
      id: 'hindleg-tarsus',
      rank: 'detail',
      fill: 'pigment-deep',
      d: 'M439.08 981.3 C435.04 996.33 443.75 1052.39 451.06 1065.06 C453.9 1069.98 458.08 1073.29 461.06 1072.94 C464.04 1072.58 467.34 1068.38 468.94 1062.94 C473.07 1048.9 468.38 992.36 460.92 978.7 C457.73 972.84 452.34 968.64 448.7 969.08 C445.06 969.51 440.81 974.86 439.08 981.3 Z',
    },
    {
      id: 'hindleg-tarsus',
      rank: 'detail',
      fill: 'pigment-deep',
      d: 'M454.52 1072.61 C450.81 1084.53 456.62 1136.21 462.02 1146.48 C463.84 1149.96 466.49 1152.14 468.48 1151.98 C470.48 1151.82 472.74 1149.24 473.98 1145.52 C477.65 1134.51 475.06 1082.57 469.48 1071.39 C467.36 1067.17 463.89 1064.32 461.39 1064.52 C458.9 1064.73 455.93 1068.1 454.52 1072.61 Z',
    },
    {
      id: 'hindleg-tarsus',
      rank: 'detail',
      fill: 'ink',
      d: 'M463.51 1154.31 C460.75 1162.93 466.36 1202.04 469.5 1208.14 C470.31 1209.7 471.31 1210.54 472.14 1210.5 C472.97 1210.45 473.87 1209.5 474.5 1207.86 C476.95 1201.45 478.19 1161.97 474.49 1153.69 C473.09 1150.56 470.53 1148.41 468.69 1148.51 C466.86 1148.61 464.55 1151.04 463.51 1154.31 Z',
    },
    {
      id: 'midleg-femur',
      rank: 'structure',
      fill: 'pigment-deep',
      d: 'M187.62 487.84 C207.93 499.39 267.8 497.19 307.89 501.86 C347.97 506.53 407.38 521.59 428.15 515.88 C436.55 513.57 443.26 508.48 443.88 503.85 C444.49 499.22 439.35 492.55 431.85 488.12 C413.3 477.17 352.03 476.13 312.11 470.14 C272.2 464.15 215.01 446.33 192.38 452.16 C182 454.83 172.95 461.67 172.16 467.62 C171.36 473.57 178.31 482.55 187.62 487.84 Z',
    },
    {
      id: 'midleg-tibia',
      rank: 'structure',
      fill: 'pigment-deep',
      d: 'M418.71 508.45 C421.35 528.14 458.52 572.34 475.73 605.18 C492.66 637.48 508.57 691.86 521.3 703.83 C525.78 708.03 530.93 709.97 533.83 708.7 C536.72 707.42 538.77 702.33 538.7 696.17 C538.47 678.58 512.34 628 496.27 594.82 C479.94 561.11 457.02 507.9 441.29 495.55 C434.95 490.58 427.31 488.56 423.55 490.71 C419.79 492.86 417.65 500.48 418.71 508.45 Z',
    },
    {
      id: 'midleg-tarsus',
      rank: 'detail',
      fill: 'pigment-deep',
      d: 'M522.02 699.4 C516.08 711.45 513.49 767.63 517.52 779.51 C518.88 783.53 521.35 786.32 523.51 786.48 C525.67 786.64 528.53 784.26 530.48 780.49 C536.24 769.34 542.06 713.4 537.98 700.6 C536.45 695.79 533.26 692.22 530.6 692.02 C527.94 691.82 524.25 694.88 522.02 699.4 Z',
    },
    {
      id: 'midleg-tarsus',
      rank: 'detail',
      fill: 'pigment-deep',
      d: 'M515.52 787.47 C510.18 798.07 507.01 850.91 510.52 861.56 C511.65 865 513.73 867.33 515.56 867.48 C517.38 867.63 519.8 865.66 521.48 862.44 C526.66 852.5 532.04 799.85 528.48 788.53 C527.22 784.54 524.68 781.7 522.53 781.52 C520.37 781.35 517.4 783.75 515.52 787.47 Z',
    },
    {
      id: 'midleg-tarsus',
      rank: 'detail',
      fill: 'ink',
      d: 'M510.03 869.46 C506.41 876.51 505.6 909.79 507.51 915.73 C508.04 917.37 508.9 918.4 509.73 918.49 C510.56 918.58 511.62 917.76 512.49 916.27 C515.63 910.88 521.99 878.2 519.97 870.54 C519.18 867.55 517.2 865.21 515.54 865.03 C513.88 864.85 511.44 866.71 510.03 869.46 Z',
    },
    {
      id: 'foreleg-femur',
      rank: 'structure',
      fill: 'pigment-deep',
      d: 'M120.57 200.57 C143.86 194.8 188.19 150.02 221.43 124.92 C254.09 100.26 307.25 69.86 318.29 51.28 C322.74 43.79 324.05 35.47 321.28 31.71 C318.52 27.95 310.19 26.71 301.71 28.72 C280.69 33.7 235.97 75.51 202.57 99.08 C168.56 123.07 112.14 151.09 99.43 171.43 C93.72 180.57 91.91 191.71 95.43 196.57 C98.95 201.43 110.1 203.16 120.57 200.57 Z',
    },
    {
      id: 'foreleg-tibia',
      rank: 'structure',
      fill: 'pigment-deep',
      d: 'M316.36 51.34 C333.93 49.1 371.09 19.98 397.73 3.97 C423.89 -11.75 465.58 -31.25 474.83 -43.82 C478.38 -48.65 479.79 -54.1 478.18 -56.83 C476.57 -59.55 471.12 -60.96 465.17 -60.18 C449.74 -58.18 412.93 -30.64 386.27 -15.97 C359.1 -1.02 314.69 14.86 303.64 28.66 C298.75 34.77 296.54 42.58 298.66 46.36 C300.78 50.14 308.6 52.33 316.36 51.34 Z',
    },
    {
      id: 'foreleg-tarsus',
      rank: 'detail',
      fill: 'pigment-deep',
      d: 'M473.89 -45.01 C485.14 -46.44 520.64 -67.9 527.16 -76.32 C529.67 -79.56 530.73 -83.26 529.68 -85.16 C528.63 -87.05 524.93 -88.1 520.84 -87.68 C510.25 -86.6 473.28 -67.79 466.11 -58.99 C463.05 -55.23 461.71 -50.45 463.01 -48.11 C464.3 -45.78 469.07 -44.39 473.89 -45.01 Z',
    },
    {
      id: 'foreleg-tarsus',
      rank: 'detail',
      fill: 'pigment-deep',
      d: 'M534.13 -80.3 C544.21 -81.5 578.69 -101.62 584.65 -109.18 C586.83 -111.94 587.7 -115.04 586.82 -116.65 C585.94 -118.25 582.86 -119.18 579.35 -118.82 C569.77 -117.85 534.29 -99.57 527.87 -91.7 C525.32 -88.57 524.26 -84.77 525.3 -82.87 C526.34 -80.97 530.12 -79.83 534.13 -80.3 Z',
    },
    {
      id: 'foreleg-tarsus',
      rank: 'detail',
      fill: 'ink',
      d: 'M591.48 -113.66 C598.63 -114.79 621.86 -131.18 625.24 -135.83 C626.24 -137.21 626.58 -138.52 626.17 -139.24 C625.76 -139.96 624.45 -140.33 622.76 -140.17 C617.04 -139.62 591.13 -127.93 586.52 -122.34 C584.59 -120 583.83 -116.97 584.66 -115.52 C585.49 -114.07 588.49 -113.18 591.48 -113.66 Z',
    },
    // Hindwing under forewing, and both membranous: the legs pass beneath them
    // and painting a bee's wings opaque deletes a leg apiece.
    {
      id: 'hindwing',
      rank: 'outline',
      fill: 'surface',
      d: 'M150 348 C156.56 336.38 249.61 367.46 296 380 C339.32 391.7 383.95 406.63 420 420 C448.68 430.64 494.53 441.04 496 452 C496.97 459.2 481.85 470.04 468 474 C441.66 481.53 381.41 468.5 340 460 C299.46 451.68 254.42 444.07 222 424 C192.13 405.51 144.51 357.72 150 348 Z',
      opacity: 'membrane',
    },
    {
      id: 'wing-vein',
      rank: 'detail',
      fill: 'none',
      d: 'M206 378 C206 378 282.49 395.61 320 406 C357.15 416.29 430 440 430 440',
      clipTo: 'hindwing',
    },
    {
      id: 'forewing',
      rank: 'outline',
      fill: 'surface',
      d: 'M165 288 C183.71 254.54 272.7 233.93 330 208 C390.75 180.51 457.35 153.37 520 128 C580.64 103.45 648.51 76.23 700 58 C737.96 44.56 776.89 20.79 800 26 C814.94 29.37 832.17 44.31 832 56 C831.76 73.07 790.67 97.34 762 118 C724.03 145.35 667.93 172.1 620 200 C570.64 228.73 519.29 259.81 470 288 C422.68 315.06 374.33 345.15 330 366 C292.31 383.73 249.77 413.84 222 408 C200.31 403.44 181.49 378.03 172 358 C162.53 338.02 153.41 308.73 165 288 Z',
      opacity: 'membrane',
    },
    {
      id: 'wing-vein',
      rank: 'detail',
      fill: 'none',
      d: 'M222 292 C222 292 380.6 224.55 460 190 C539.93 155.22 700 84 700 84',
      clipTo: 'forewing',
    },
    {
      id: 'wing-vein',
      rank: 'detail',
      fill: 'none',
      d: 'M226 336 C226 336 356.27 288.7 420 262 C483.6 235.36 608 176 608 176',
      clipTo: 'forewing',
    },
    {
      id: 'wing-vein',
      rank: 'detail',
      fill: 'none',
      d: 'M352 234 C352 234 384.17 255.99 396 268 C406.04 278.18 420 300 420 300',
      clipTo: 'forewing',
    },
    // The abdomen. Drawn once on the axis, like the thorax and the head: one
    // organ straddling the midline, symmetric in itself, and a doubled line
    // down the back if it were reflected.
    {
      id: 'abdomen',
      rank: 'outline',
      fill: 'pigment-deep',
      d: 'M0 452 C85.33 452 210.41 433.42 256 476 C294.82 512.26 287.41 602.97 286 660 C284.76 709.97 271.73 758.3 256 800 C241.92 837.31 224.38 871.64 200 900 C175.68 928.28 143.24 952.68 110 970 C76.6 987.41 36.67 1004 0 1004 C-36.67 1004 -76.6 987.41 -110 970 C-143.24 952.68 -175.68 928.28 -200 900 C-224.38 871.64 -241.92 837.31 -256 800 C-271.73 758.3 -284.76 709.97 -286 660 C-287.41 602.97 -294.82 512.26 -256 476 C-210.41 433.42 -85.33 452 0 452 Z',
      mirror: false,
    },
    // The band across the second tergite, and the tail.
    //
    // Two of the three bands a British bumblebee is keyed out on; the third is
    // the collar, which is on the thorax. `pigment` for the ochre band and
    // `surface` for the tail, so the two read as different values rather than
    // as one band drawn twice.
    {
      id: 'marking',
      rank: 'structure',
      fill: 'pigment',
      d: 'M0 574 C60 574 132.7 576.11 180 584 C211.71 589.29 244.17 588.58 258 606 C272.26 623.95 275.31 679.08 262 692 C249.31 704.31 215.52 687.21 184 686 C135.66 684.14 61.33 686 0 686 C-61.33 686 -135.66 684.14 -184 686 C-215.52 687.21 -249.31 704.31 -262 692 C-275.31 679.08 -272.26 623.95 -258 606 C-244.17 588.58 -211.71 589.29 -180 584 C-132.7 576.11 -60 574 0 574 Z',
      mirror: false,
      clipTo: 'abdomen',
    },
    {
      id: 'marking',
      rank: 'structure',
      fill: 'surface',
      d: 'M0 828 C46.67 828 106.79 828.39 140 844 C163.29 854.95 189.22 874.58 190 892 C190.85 910.98 161.25 938.53 136 954 C103.03 974.2 45.33 988 0 988 C-45.33 988 -103.03 974.2 -136 954 C-161.25 938.53 -190.85 910.98 -190 892 C-189.22 874.58 -163.29 854.95 -140 844 C-106.79 828.39 -46.67 828 0 828 Z',
      mirror: false,
      clipTo: 'abdomen',
    },
    // Fur, as a fan radiating from the base of the abdomen.
    //
    // Strokes running *across* the animal were the first attempt and they read
    // as tergite boundaries — which the abdomen does not have here, because
    // the fur hides them. Fur lies back from where it grows, so the strokes
    // share an origin and spread.
    {
      id: 'hatching',
      rank: 'detail',
      fill: 'none',
      d: 'M24 516 C24 516 102.2 521.87 140 528 C176.82 533.98 248 552 248 552',
      clipTo: 'abdomen',
    },
    {
      id: 'hatching',
      rank: 'detail',
      fill: 'none',
      d: 'M24 516 C24 516 98.27 548.69 132.8 567.6 C166.15 585.87 228 627.2 228 627.2',
      clipTo: 'abdomen',
    },
    {
      id: 'hatching',
      rank: 'detail',
      fill: 'none',
      d: 'M24 516 C24 516 94.42 575.45 125.6 607.2 C155.54 637.69 208 702.4 208 702.4',
      clipTo: 'abdomen',
    },
    {
      id: 'hatching',
      rank: 'detail',
      fill: 'none',
      d: 'M24 516 C24 516 90.64 602.23 118.4 646.8 C145 689.51 188 777.6 188 777.6',
      clipTo: 'abdomen',
    },
    {
      id: 'hatching',
      rank: 'detail',
      fill: 'none',
      d: 'M24 516 C24 516 86.89 629.05 111.2 686.4 C134.5 741.36 168 852.8 168 852.8',
      clipTo: 'abdomen',
    },
    {
      id: 'hatching',
      rank: 'detail',
      fill: 'none',
      d: 'M24 516 C24 516 83.14 655.9 104 726 C124.01 793.24 148 928 148 928',
      clipTo: 'abdomen',
    },
    // The thorax, and the collar across the front of it — the first of the
    // three bands.
    {
      id: 'thorax',
      rank: 'outline',
      fill: 'pigment-deep',
      d: 'M0 104 C54.67 104 125.82 90.47 164 120 C205.18 151.85 224.47 248.15 230 300 C234.01 337.63 229.75 372.99 216 400 C203.5 424.56 183.55 444.97 156 458 C118.21 475.87 52 476 0 476 C-52 476 -118.21 475.87 -156 458 C-183.55 444.97 -203.5 424.56 -216 400 C-229.75 372.99 -234.01 337.63 -230 300 C-224.47 248.15 -205.18 151.85 -164 120 C-125.82 90.47 -54.67 104 0 104 Z',
      mirror: false,
    },
    {
      id: 'marking',
      rank: 'structure',
      fill: 'pigment',
      d: 'M0 112 C53.33 112 127.02 104.36 160 128 C185.57 146.33 208 197.43 200 216 C193 232.24 157.35 235.87 130 240 C93.73 245.47 43.33 236 0 236 C-43.33 236 -93.73 245.47 -130 240 C-157.35 235.87 -193 232.24 -200 216 C-208 197.43 -185.57 146.33 -160 128 C-127.02 104.36 -53.33 112 0 112 Z',
      mirror: false,
      clipTo: 'thorax',
    },
    {
      id: 'hatching',
      rank: 'detail',
      fill: 'none',
      d: 'M18 288 C18 288 85.21 286.61 118 288 C149.85 289.35 212 296 212 296',
      clipTo: 'thorax',
    },
    {
      id: 'hatching',
      rank: 'detail',
      fill: 'none',
      d: 'M18 288 C18 288 82.42 299.93 112.5 307.5 C140.57 314.57 193 331.5 193 331.5',
      clipTo: 'thorax',
    },
    {
      id: 'hatching',
      rank: 'detail',
      fill: 'none',
      d: 'M18 288 C18 288 79.84 313.01 107 327 C131.34 339.54 174 367 174 367',
      clipTo: 'thorax',
    },
    {
      id: 'hatching',
      rank: 'detail',
      fill: 'none',
      d: 'M18 288 C18 288 77.61 325.98 101.5 346.5 C122.33 364.39 155 402.5 155 402.5',
      clipTo: 'thorax',
    },
    {
      id: 'hatching',
      rank: 'detail',
      fill: 'none',
      d: 'M18 288 C18 288 75.67 339.05 96 366 C113.57 389.29 136 438 136 438',
      clipTo: 'thorax',
    },
    {
      id: 'head',
      rank: 'outline',
      fill: 'pigment-deep',
      d: 'M0 -4 C24 -4 52.66 -2.78 72 8 C90.08 18.08 109.76 39.22 114 56 C117.57 70.11 115 89.76 104 100 C87.21 115.64 34.67 116 0 116 C-34.67 116 -87.21 115.64 -104 100 C-115 89.76 -117.57 70.11 -114 56 C-109.76 39.22 -90.08 18.08 -72 8 C-52.66 -2.78 -24 -4 0 -4 Z',
      mirror: false,
    },
    {
      id: 'eye',
      rank: 'detail',
      fill: 'ink',
      d: 'M103.61 63.74 C99.7 82.11 88.65 95.32 78.93 93.26 C69.21 91.19 64.49 74.62 68.39 56.26 C72.3 37.89 83.35 24.68 93.07 26.74 C102.79 28.81 107.51 45.38 103.61 63.74 Z',
    },
    // A short, elbowed antenna, drawn as two filled segments that meet at the
    // bend: a long scape off the face, and a flagellum kicked outward from it.
    // Twelve segments on a female and thirteen on a male, and neither count
    // survives to plate size — the elbow does, so the elbow is the drawing.
    // The flagellum was a single hairline for one release and disappeared at
    // eighty pixels: a stroke is one weight whatever the frame, and a capsule
    // carries its width in plate units and scales with the animal.
    {
      id: 'antenna',
      rank: 'structure',
      fill: 'pigment-deep',
      d: 'M62.82 45.21 C72.48 38.53 82.1 16.32 89.95 1.77 C97.34 -11.93 108.39 -29.45 108.94 -39.53 C109.25 -45.15 107.45 -51.45 104.47 -52.94 C101.49 -54.43 95.35 -52.07 91.06 -48.47 C83.49 -42.13 78.05 -22.58 70.05 -9.77 C61.55 3.85 43.59 19.53 41.18 30.79 C39.72 37.63 41.18 46.41 44.79 48.82 C48.39 51.22 57.03 49.21 62.82 45.21 Z',
    },
    // The flagellum, from the elbow outward. Its own segment rather than a
    // continuation of the scape, because a smoothed curve through both rounds
    // the bend off and the bend is the character.
    {
      id: 'antenna',
      rank: 'structure',
      fill: 'pigment-deep',
      d: 'M103.71 -34.72 C117.61 -34.78 148.99 -55.88 172.46 -64.92 C196.22 -74.06 236.93 -82.08 245.42 -89.21 C248 -91.37 249.27 -93.83 248.79 -95.42 C248.32 -97.02 245.92 -98.39 242.58 -98.79 C231.5 -100.13 192.06 -86.73 167.54 -79.08 C143.3 -71.53 106.45 -62.88 96.29 -53.28 C91.89 -49.14 89.48 -43.38 90.72 -40.29 C91.95 -37.19 97.68 -34.69 103.71 -34.72 Z',
    },
  ],
};
