// Generated from ../landmarks/carabus-violaceus.json by `npm run plate:build`.
//
// Do not edit this file. Edit the landmarks and build again; `npm run
// plate:verify` fails the check if the two drift apart.

import type { SpeciesPlate } from '@/lib/plate';

/**
 * *Carabus violaceus*, dorsal — the violet ground beetle.
 *
 * The third plate traced from Emil Hochdanz's lithographs for Calwer's
 * *Käferbuch* (1876), after the stag beetle and the seven-spot, and by now the
 * reason for staying with one engraver is visible on the contact sheet: three
 * beetles that look like three beetles rather than three projects.
 * `references/carabus-violaceus.jpg` is the file and `references/SOURCES.md`
 * has the provenance.
 *
 * ## What the drawing has to get right
 *
 * The **border**. This beetle is not violet; it is black with a violet rim,
 * the outer margin of each wing case turned up and catching the light, and
 * that rim is the whole of the common name. It is drawn as a `strip` — the
 * outer margin traced, and a depth inwards from it — rather than as a second
 * outline, because a band that keeps its width round a curve is a border and
 * one that does not is a wedge.
 *
 * Then the **legs**, which are the other half of the animal. A ground beetle is
 * a runner: the femora are long, the tibiae longer, and the hind tarsi reach a
 * third of a body length past the wing cases. Drawn at a chafer's proportions
 * it becomes a dung beetle.
 *
 * Then the **antennae**, which are filiform and are drawn segment by segment.
 * Eleven on the animal; seven here, because at eighty pixels eleven capsules
 * end-to-end is a dotted line. What has to read is that they are a chain of
 * equal joints rather than a club or a comb, and seven says that.
 *
 * ## Plate space
 *
 * y = 0 at the front margin of the head, y = 1000 at the elytral apex, which
 * puts the pronotum at 200–410 and the wing cases at 400–1000 — the
 * proportions measured off the lithograph, where the body is 405 pixels long
 * and 157 across. The mandibles and the antennae reach above y = 0 and the
 * hind tarsi past y = 1290; the frame is measured from the drawing.
 *
 * Drawing order is back to front: legs, then the wing cases and their surface
 * work, then the thorax, then the head and its appendages.
 */
export const CARABUS_VIOLACEUS_PLATE: SpeciesPlate = {
  species: 'carabus-violaceus',
  order: 'coleoptera',
  sex: 'unsexed',
  hallmark: "the reflexed violet border round each wing case, and the long runner's legs",
  reference: {
    title: 'Käferbuch. Naturgeschichte der Käfer Europas, table 3 figure 9',
    artist: 'Emil Hochdanz',
    year: 1876,
    source: 'https://commons.wikimedia.org/wiki/File:Carabus.violaceus.-.calwer.03.09.jpg',
    licence: 'Public domain (PD-old-100-1923)',
  },
  parts: [
    // The legs first, so they pass under the body.
    //
    // Long and slender, and measured that way: a Carabus runs down its prey on
    // the ground rather than digging or clinging, and the reference shows all
    // six legs held clear of the body with nothing foreshortened. Femora at
    // about nine per cent of the width across the wing cases and tibiae at six,
    // which is finer than the chafer's and heavier than the ladybird's.
    {
      id: 'hindleg-femur',
      rank: 'structure',
      fill: 'pigment-deep',
      d: 'M127.98 632.02 C136.53 652.15 183.62 684.7 209.17 710.37 C232.89 734.23 259.8 773.25 276.42 780.78 C283.64 784.06 291.59 784.51 294.78 781.58 C297.98 778.65 298.22 770.7 295.58 763.22 C289.49 745.94 253.78 714.52 230.83 689.63 C206.14 662.84 172.22 616.56 152.02 607.98 C142.72 604.03 131.99 603.97 127.98 607.98 C123.97 611.99 124.03 622.73 127.98 632.02 Z',
    },
    {
      id: 'hindleg-tibia',
      rank: 'structure',
      fill: 'pigment-deep',
      d: 'M274.07 773.3 C268.31 793.51 286.69 857.89 289.52 900.57 C292.36 943.46 283.6 1012.42 291 1030 C293.32 1035.51 297 1039 300 1039 C303 1039 306.68 1035.52 309 1030 C316.44 1012.32 312.35 942.75 310.48 899.43 C308.63 856.31 307.98 789.28 297.93 770.7 C294.29 763.96 288.67 759.64 284.7 760.07 C280.72 760.51 276.17 765.95 274.07 773.3 Z',
    },
    {
      id: 'hindleg-tarsus',
      rank: 'detail',
      fill: 'pigment-deep',
      d: 'M292.01 1029.6 C286.33 1041.78 284.61 1097.56 289.01 1109.65 C290.56 1113.9 293.32 1116.87 295.65 1116.99 C297.98 1117.11 301.03 1114.42 302.99 1110.35 C308.57 1098.76 312.43 1043.09 307.99 1030.4 C306.32 1025.63 303.06 1022.14 300.4 1022.01 C297.74 1021.88 294.15 1025.02 292.01 1029.6 Z',
    },
    {
      id: 'hindleg-tarsus',
      rank: 'detail',
      fill: 'pigment-deep',
      d: 'M288.01 1117.55 C282.53 1128.9 280.08 1184.32 284.01 1195.62 C285.31 1199.34 287.62 1201.86 289.62 1201.99 C291.61 1202.12 294.23 1199.91 295.99 1196.38 C301.33 1185.68 305.98 1130.4 301.99 1118.45 C300.57 1114.19 297.78 1111.16 295.45 1111.01 C293.12 1110.87 289.97 1113.51 288.01 1117.55 Z',
    },
    {
      id: 'hindleg-tarsus',
      rank: 'detail',
      fill: 'ink',
      d: 'M283.02 1203.46 C277.31 1214.88 275.62 1283.09 278.51 1291.77 C279.09 1293.51 279.94 1294.41 280.77 1294.49 C281.6 1294.57 282.61 1293.83 283.49 1292.23 C287.9 1284.21 298.53 1216.81 294.98 1204.54 C293.87 1200.74 291.54 1198.21 289.54 1198.02 C287.55 1197.84 284.79 1199.92 283.02 1203.46 Z',
    },
    {
      id: 'midleg-femur',
      rank: 'structure',
      fill: 'pigment-deep',
      d: 'M121.69 444.83 C135.5 462.03 190.06 480.76 222.41 498.94 C253.11 516.19 292.49 548.29 311.2 551.08 C319.11 552.26 326.81 550.49 329.08 546.8 C331.35 543.11 329.43 535.44 324.8 528.92 C313.8 513.45 267.8 491.53 237.59 473.06 C205.76 453.6 160.26 417.96 138.31 415.17 C128.26 413.89 117.94 416.75 115.17 421.69 C112.4 426.64 115.36 436.94 121.69 444.83 Z',
    },
    {
      id: 'midleg-tibia',
      rank: 'structure',
      fill: 'pigment-deep',
      d: 'M311.08 549.8 C319.68 563.15 357.53 580.98 379.84 596.51 C401.34 611.45 429.25 638.01 442.64 641.23 C448.08 642.54 453.44 641.77 455.23 639.36 C457.02 636.95 456.19 631.6 453.36 626.77 C446.38 614.86 413.14 595.29 392.16 579.49 C370.37 563.1 340.4 533.84 324.92 530.2 C317.94 528.55 310.5 529.81 308.2 533.08 C305.89 536.35 307.19 543.77 311.08 549.8 Z',
    },
    {
      id: 'midleg-tarsus',
      rank: 'detail',
      fill: 'pigment-deep',
      d: 'M442.76 640.05 C446.64 647.57 465.62 662.8 473.42 665.29 C477.31 666.53 481.76 666.35 483.29 664.58 C484.82 662.82 484.37 658.39 482.58 654.71 C479.01 647.34 461.24 630.73 453.24 627.95 C448.97 626.47 443.7 626.75 441.95 628.76 C440.21 630.78 440.69 636.03 442.76 640.05 Z',
    },
    {
      id: 'midleg-tarsus',
      rank: 'detail',
      fill: 'pigment-deep',
      d: 'M477.05 668.95 C480.09 676.02 496.89 691.51 503.76 694.24 C507.06 695.56 510.83 695.66 512.24 694.24 C513.66 692.83 513.56 689.06 512.24 685.76 C509.51 678.89 494.02 662.09 486.95 659.05 C483.28 657.47 478.7 657.4 477.05 659.05 C475.4 660.7 475.47 665.28 477.05 668.95 Z',
    },
    {
      id: 'midleg-tarsus',
      rank: 'detail',
      fill: 'ink',
      d: 'M507.6 698.08 C510.5 704.9 530.97 721.6 536.17 723.7 C537.74 724.34 539.09 724.4 539.7 723.83 C540.31 723.26 540.35 721.92 539.83 720.3 C538.12 714.96 522.98 693.31 516.4 689.92 C513.3 688.32 509.38 688.24 507.92 689.6 C506.45 690.96 506.24 694.88 507.6 698.08 Z',
    },
    {
      id: 'foreleg-femur',
      rank: 'structure',
      fill: 'pigment-deep',
      d: 'M84.08 276.96 C101.95 274.9 134.71 248.48 157.29 235.11 C177.07 223.4 204.08 212.44 212.45 201.29 C216.91 195.34 219.44 187.31 217.29 183.55 C215.14 179.79 206.93 177.89 199.55 178.71 C185.74 180.25 163 198.33 142.71 208.89 C119.53 220.95 79.4 233.26 67.92 247.04 C61.77 254.42 58.35 265.1 61.04 270.08 C63.74 275.07 74.54 278.05 84.08 276.96 Z',
    },
    {
      id: 'foreleg-tibia',
      rank: 'structure',
      fill: 'pigment-deep',
      d: 'M214.83 198.12 C227.42 192.11 246.35 164.03 260.07 146.71 C272.98 130.43 292.42 108.85 295.2 97.4 C296.48 92.15 295.8 86.6 293.4 84.8 C291 83 285.47 83.91 280.8 86.6 C270.7 92.41 257.35 117.89 243.93 133.29 C229.63 149.68 202.06 168.96 197.17 181.88 C194.71 188.35 194.93 196.12 197.88 198.83 C200.82 201.54 208.56 201.12 214.83 198.12 Z',
    },
    {
      id: 'foreleg-tarsus',
      rank: 'detail',
      fill: 'pigment-deep',
      d: 'M294.97 95.92 C301.22 90.88 311.28 71.16 312.1 63.43 C312.53 59.42 311.47 55.04 309.43 53.9 C307.4 52.76 303.11 54.12 299.9 56.57 C293.72 61.29 282.09 80.12 281.03 88.08 C280.44 92.49 281.75 97.67 284.08 98.97 C286.4 100.28 291.51 98.72 294.97 95.92 Z',
    },
    {
      id: 'foreleg-tarsus',
      rank: 'detail',
      fill: 'pigment-deep',
      d: 'M314.41 56.81 C319.7 51.58 327.46 31.55 327.5 24.4 C327.52 20.88 326.24 17.3 324.4 16.5 C322.57 15.7 319.08 17.19 316.5 19.6 C311.28 24.47 301.84 43.77 301.59 51.19 C301.45 55.15 303.06 59.48 305.19 60.41 C307.33 61.35 311.6 59.59 314.41 56.81 Z',
    },
    {
      id: 'foreleg-tarsus',
      rank: 'detail',
      fill: 'ink',
      d: 'M329.66 18 C334.16 12.47 338.91 -11.78 338.36 -17.17 C338.19 -18.85 337.62 -20.08 336.83 -20.36 C336.05 -20.63 334.83 -20.03 333.64 -18.83 C329.84 -14.99 318.31 6.88 318.34 14 C318.36 17.45 320.12 20.99 322 21.66 C323.89 22.32 327.48 20.67 329.66 18 Z',
    },
    // One wing case, from the suture outwards. The pair meet on the midline, so
    // the inner edge of this shape is the axis and the renderer's reflection
    // supplies the other one.
    //
    // Widest at about three fifths of the way down, which is where a Carabus
    // carries its shoulder — further back than a ladybird and much further back
    // than a chafer.
    {
      id: 'elytron',
      rank: 'outline',
      fill: 'pigment',
      d: 'M0 398 C0 376.43 64.14 394.17 92 400 C116.91 405.21 144.32 412.07 160 428 C175.4 443.64 180.43 469.72 186 494 C192.36 521.7 192.26 554.37 193 586 C193.79 619.58 192.88 655.75 190 690 C187.16 723.74 183.21 757.83 176 790 C169.04 821.08 160.5 852.38 148 880 C136.17 906.13 121.43 933.07 104 952 C88.77 968.54 70.27 982.05 52 990 C35.44 997.21 0 1011.04 0 1000 C0 962.77 0 453.18 0 398 Z',
    },
    // The violet border, and the reason for the name.
    //
    // A strip: the outer margin traced a little inside the outline, and a depth
    // of twenty-four units inwards from it. Set inside rather than on the
    // margin because a band drawn exactly on an outline is half on the animal
    // and half off it, and the plate test measures the ink rather than the
    // intention.
    {
      id: 'marking',
      rank: 'structure',
      fill: 'pigment-deep',
      d: 'M92 414 C102.81 409.72 138.33 425.52 152 440 C165.52 454.32 169.26 477.72 174 500 C179.57 526.18 179.57 557.72 180 588 C180.45 620.26 179.05 655.09 176 688 C173 720.41 168.94 753.33 162 784 C155.39 813.2 147.54 842.33 136 868 C125.19 892.05 108.65 930.9 96 934 C88.95 935.73 77.18 928.56 75.48 921.56 C72.47 909.25 103.74 881.18 114.11 858.16 C125.08 833.79 132.33 806.48 138.59 778.7 C145.24 749.19 149.2 717.2 152.1 685.79 C155.06 653.77 156.4 619.54 156 588.34 C155.63 559.46 155.15 528.79 150.53 505 C146.91 486.39 145.38 467.93 134.55 456.48 C123.21 444.49 86.39 445.49 82.46 436.02 C79.88 429.82 85.45 416.59 92 414 Z',
      clipTo: 'elytron',
    },
    // The striae. Faint on this beetle — Calwer's figure shows three low ridges
    // and a granulate surface between them rather than the deep grooves of a
    // ground beetle like Carabus nemoralis — so four strokes, laid from a guide
    // near the suture to one inside the border.
    {
      id: 'stria',
      rank: 'structure',
      fill: 'none',
      d: 'M26 452 C26 452 22.53 619.46 24 700 C25.4 776.59 34 924 34 924',
      clipTo: 'elytron',
    },
    {
      id: 'stria',
      rank: 'structure',
      fill: 'none',
      d: 'M66.67 460 C66.67 460 71.45 622.39 69.33 700 C67.34 773.24 55.33 913.33 55.33 913.33',
      clipTo: 'elytron',
    },
    {
      id: 'stria',
      rank: 'structure',
      fill: 'none',
      d: 'M107.33 468 C107.33 468 120.4 625.58 114.67 700 C109.26 770.14 76.67 902.67 76.67 902.67',
      clipTo: 'elytron',
    },
    {
      id: 'stria',
      rank: 'structure',
      fill: 'none',
      d: 'M148 476 C148 476 169.24 629.02 160 700 C151.24 767.32 98 892 98 892',
      clipTo: 'elytron',
    },
    // The granulation, as six short cross-strokes over the same field. Together
    // with the striae this is what stops a plain black wing case reading as a
    // silhouette at thumbnail size.
    {
      id: 'hatching',
      rank: 'detail',
      fill: 'none',
      d: 'M40 540 C40 540 92 566 92 566',
      clipTo: 'elytron',
    },
    {
      id: 'hatching',
      rank: 'detail',
      fill: 'none',
      d: 'M43.2 603.2 C43.2 603.2 95.6 618.8 95.6 618.8',
      clipTo: 'elytron',
    },
    {
      id: 'hatching',
      rank: 'detail',
      fill: 'none',
      d: 'M46.4 666.4 C46.4 666.4 99.2 671.6 99.2 671.6',
      clipTo: 'elytron',
    },
    {
      id: 'hatching',
      rank: 'detail',
      fill: 'none',
      d: 'M49.6 729.6 C49.6 729.6 102.8 724.4 102.8 724.4',
      clipTo: 'elytron',
    },
    {
      id: 'hatching',
      rank: 'detail',
      fill: 'none',
      d: 'M52.8 792.8 C52.8 792.8 106.4 777.2 106.4 777.2',
      clipTo: 'elytron',
    },
    {
      id: 'hatching',
      rank: 'detail',
      fill: 'none',
      d: 'M56 856 C56 856 110 830 110 830',
      clipTo: 'elytron',
    },
    // The suture, drawn once on the axis. Reflecting it would lay a second copy
    // a hair off the first and show as a doubled line down the beetle's back.
    {
      id: 'seam',
      rank: 'structure',
      fill: 'none',
      d: 'M0 410 C0 410 0 603.67 0 700 C0 795.66 0 986 0 986',
      mirror: false,
    },
    {
      id: 'scutellum',
      rank: 'structure',
      fill: 'pigment-deep',
      d: 'M0 400 C10.67 400 29.11 401.72 32 408 C34.91 414.33 22.86 429.62 17 438 C11.97 445.2 5.67 456 0 456 C-5.67 456 -11.97 445.2 -17 438 C-22.86 429.62 -34.91 414.33 -32 408 C-29.11 401.72 -10.67 400 0 400 Z',
      mirror: false,
    },
    // The pronotum: a broad shield, widest a third of the way back, with the
    // hind angles drawn out into the small backward points that are a Carabus
    // character. Drawn once on the axis, because it straddles it.
    {
      id: 'pronotum',
      rank: 'outline',
      fill: 'pigment',
      d: 'M0 204 C29.33 204 62.15 193.77 88 198 C109.81 201.57 132.67 208.12 146 222 C159.45 236.01 165.14 261.86 168 282 C170.73 301.21 167.25 321.75 164 340 C160.98 356.93 157.85 377.54 150 388 C144.33 395.56 137.78 398.82 128 402 C112.67 406.99 85.34 405 64 406 C42.67 407 21.33 408 0 408 C-21.33 408 -42.67 407 -64 406 C-85.34 405 -112.67 406.99 -128 402 C-137.78 398.82 -144.33 395.56 -150 388 C-157.85 377.54 -160.98 356.93 -164 340 C-167.25 321.75 -170.73 301.21 -168 282 C-165.14 261.86 -159.45 236.01 -146 222 C-132.67 208.12 -109.81 201.57 -88 198 C-62.15 193.77 -29.33 204 0 204 Z',
      mirror: false,
    },
    {
      id: 'hatching',
      rank: 'detail',
      fill: 'none',
      d: 'M22 250 C22 250 24 372 24 372',
      clipTo: 'pronotum',
    },
    {
      id: 'hatching',
      rank: 'detail',
      fill: 'none',
      d: 'M54 252.67 C54 252.67 54.67 370.67 54.67 370.67',
      clipTo: 'pronotum',
    },
    {
      id: 'hatching',
      rank: 'detail',
      fill: 'none',
      d: 'M86 255.33 C86 255.33 85.33 369.33 85.33 369.33',
      clipTo: 'pronotum',
    },
    {
      id: 'hatching',
      rank: 'detail',
      fill: 'none',
      d: 'M118 258 C118 258 116 368 116 368',
      clipTo: 'pronotum',
    },
    // The median impression down the pronotum, drawn once on the axis for the
    // same reason the suture is.
    {
      id: 'pronotum',
      rank: 'detail',
      fill: 'none',
      d: 'M0 224 C0 224 0 281.33 0 310 C0 338.67 0 396 0 396',
      mirror: false,
    },
    {
      id: 'head',
      rank: 'outline',
      fill: 'pigment-deep',
      d: 'M0 -6 C15.33 -6 31.75 -5.25 46 0 C60.45 5.32 75.48 14.22 86 26 C97.16 38.5 104.98 56.75 110 74 C115.24 91.98 117.09 113.1 116 132 C114.93 150.41 113.2 171.06 104 186 C94.68 201.15 76.96 214.31 60 222 C42.46 229.95 20 232 0 232 C-20 232 -42.46 229.95 -60 222 C-76.96 214.31 -94.68 201.15 -104 186 C-113.2 171.06 -114.93 150.41 -116 132 C-117.09 113.1 -115.24 91.98 -110 74 C-104.98 56.75 -97.16 38.5 -86 26 C-75.48 14.22 -60.45 5.32 -46 0 C-31.75 -5.25 -15.33 -6 0 -6 Z',
      mirror: false,
    },
    // A mandible. Sickle-shaped, crossed in front of the head on the animal and
    // drawn open here, because two crossed mandibles at plate size are one
    // blot. Mirrored, so this entry draws both.
    {
      id: 'mandible',
      rank: 'structure',
      fill: 'pigment-deep',
      d: 'M47.98 8.66 C55.45 3 65.1 -14.85 65.85 -26.45 C66.54 -37.22 57.68 -54.35 54.45 -58.49 C53.41 -59.82 52.33 -60.61 51.51 -60.45 C50.69 -60.29 50.01 -59.1 49.55 -57.51 C48.25 -53.03 53.28 -38.05 50.15 -29.55 C46.74 -20.28 30.18 -12.65 28.02 -4.66 C26.47 1.05 28.02 9.77 31.34 11.98 C34.67 14.2 43.09 12.37 47.98 8.66 Z',
    },
    {
      id: 'eye',
      rank: 'detail',
      fill: 'ink',
      d: 'M119.81 122.78 C117.81 137 107.32 147.28 96.38 145.75 C85.44 144.21 78.2 131.44 80.19 117.22 C82.19 103 92.68 92.72 103.62 94.25 C114.56 95.79 121.8 108.56 119.81 122.78 Z',
    },
    // The antenna: a chain of equal joints, which is what `filiform` means and
    // the character that separates this beetle from every scarab in the
    // collection. The scape is the stout first joint; six more carry it up and
    // out to where the reference puts the tip.
    {
      id: 'antenna',
      rank: 'structure',
      fill: 'pigment-deep',
      d: 'M69.53 52.85 C78.09 48.65 91.06 32.26 94.06 23.48 C95.97 17.89 96.17 10.43 93.48 7.94 C90.8 5.44 83.38 6.19 77.94 8.52 C69.41 12.16 54.03 26.3 50.47 35.15 C48.01 41.29 47.98 50.58 51.15 53.53 C54.33 56.47 63.59 55.76 69.53 52.85 Z',
    },
    {
      id: 'antenna',
      rank: 'structure',
      fill: 'pigment-deep',
      d: 'M97.15 18.1 C104.36 13.13 114.77 -3.99 116.32 -12.45 C117.29 -17.75 116.32 -24.47 113.55 -26.32 C110.77 -28.17 104.2 -26.48 99.68 -23.55 C92.47 -18.86 80.67 -2.67 78.85 5.9 C77.65 11.52 78.85 19.12 81.9 21.15 C84.95 23.19 92.42 21.37 97.15 18.1 Z',
    },
    {
      id: 'antenna',
      rank: 'detail',
      fill: 'pigment-deep',
      d: 'M119.25 -20.19 C125.25 -26.38 132.45 -46.14 132.32 -54.57 C132.24 -59.54 130.2 -65.18 127.43 -66.32 C124.65 -67.46 119.23 -64.9 115.68 -61.43 C109.64 -55.53 100.85 -36.43 100.75 -27.81 C100.69 -22.46 103.11 -16.02 106.19 -14.75 C109.27 -13.48 115.53 -16.35 119.25 -20.19 Z',
    },
    {
      id: 'antenna',
      rank: 'detail',
      fill: 'pigment-deep',
      d: 'M134.67 -61.59 C139.72 -68.32 144.37 -90.01 143.23 -97.99 C142.62 -102.25 140.42 -106.56 138.01 -107.23 C135.6 -107.9 131.49 -105.34 128.77 -102.01 C123.68 -95.75 116.47 -74.78 117.33 -66.41 C117.83 -61.53 120.7 -56.13 123.59 -55.33 C126.48 -54.53 131.73 -57.66 134.67 -61.59 Z',
    },
    {
      id: 'antenna',
      rank: 'detail',
      fill: 'pigment-deep',
      d: 'M144.42 -104.91 C148.12 -111.42 149.82 -132.29 147.94 -139.13 C147 -142.52 144.85 -145.65 142.87 -145.94 C140.89 -146.23 137.94 -143.86 136.06 -140.87 C132.29 -134.87 127.91 -114.4 129.58 -107.09 C130.51 -103.03 133.44 -98.94 135.91 -98.58 C138.38 -98.22 142.36 -101.29 144.42 -104.91 Z',
    },
    {
      id: 'antenna',
      rank: 'detail',
      fill: 'pigment-deep',
      d: 'M148 -145.81 C150.48 -151.93 148.71 -172.68 146.5 -177.89 C145.63 -179.94 144.28 -181.46 143.11 -181.5 C141.94 -181.53 140.49 -180.1 139.5 -178.11 C136.97 -173.04 133.91 -152.45 136 -146.19 C137.08 -142.97 139.81 -140.07 141.81 -140 C143.81 -139.94 146.72 -142.67 148 -145.81 Z',
    },
  ],
};
