// Generated from ../landmarks/cetonia-aurata.json by `npm run plate:build`.
//
// Do not edit this file. Edit the landmarks and build again; `npm run
// plate:verify` fails the check if the two drift apart.

import type { SpeciesPlate } from '@/lib/plate';

/**
 * *Cetonia aurata*, dorsal — the rose chafer.
 *
 * Traced from figure 15 of plate 31 of Georgiy Jacobson's *Zhuki Rossii i
 * Zapadnoi Evropy* — Beetles of Russia and Western Europe — where the species
 * is named in the plate's own caption. `references/cetonia-aurata.jpg` is the
 * sheet; the chafer is on the right of the third row.
 *
 * ## What identifies it
 *
 * Two things, and neither is the colour. The **white flecks**: short, broken,
 * irregular dashes scattered across the wing cases, which is what separates a
 * rose chafer from the several other big green beetles a reader might have in
 * mind. And the **pygidium** — the last segment of the abdomen, left uncovered
 * behind the wing cases, because a chafer's elytra stop short. Both are drawn.
 *
 * The metallic green is not drawn, because it cannot be: the plate's ink is a
 * season's pigment and the animal's iridescence is structural colour that
 * shifts with the angle you hold it at. The record says `metallic` in words
 * instead, which is the honest place for it.
 *
 * ## The flecks are markings, not gaps
 *
 * They are `surface` fills — bare paper — clipped to the wing case, rather than
 * holes in it. A hole would knock out the hatching *and* the outline, and the
 * reference shows the flecks sitting on top of a surface that carries on
 * underneath them.
 *
 * ## Plate space
 *
 * y = 0 at the front margin of the clypeus, y = 1000 at the tip of the
 * pygidium. The legs reach past x = 440 and above y = -130; the antennal clubs
 * sit just outside the head.
 */
export const CETONIA_AURATA_PLATE: SpeciesPlate = {
  species: 'cetonia-aurata',
  order: 'coleoptera',
  sex: 'unsexed',
  hallmark:
    'the broken white flecks across the wing cases, and the pygidium left uncovered behind them',
  reference: {
    title: 'Cetonia aurata, from Zhuki Rossii i Zapadnoi Evropy, plate 31, fig. 15',
    artist: 'Georgiy Georgiyevich Jacobson',
    year: 1913,
    source:
      'https://commons.wikimedia.org/wiki/File:Georgiy_Jacobson_-_Beetles_Russia_and_Western_Europe_-_plate_31.jpg',
    licence: 'Public domain (PD-old-100-expired)',
  },
  parts: [
    // Legs first, so they pass under the body.
    //
    // A chafer's legs are stouter than a ladybird's — the fore tibiae are
    // toothed for digging — so the femora are measured a little heavier than
    // the six per cent CLAUDE.md gives as the usual proportion. Heavier still
    // and the animal reads as moulded rather than engraved.
    {
      id: 'hindleg-femur',
      rank: 'structure',
      fill: 'pigment-deep',
      d: 'M232.99 694.28 C239.99 710.12 269.47 727.94 287.21 744.66 C304.52 760.98 323.84 787.47 338.18 793.39 C346.05 796.64 355.79 797.28 359.39 793.82 C363 790.35 362.75 780.61 359.82 772.61 C354.45 757.97 329.05 736.94 312.79 719.34 C296.14 701.31 277.06 672.45 261.01 665.72 C251.12 661.58 237.39 661.23 232.72 665.99 C228.05 670.75 228.67 684.48 232.99 694.28 Z',
    },
    {
      id: 'hindleg-tibia',
      rank: 'structure',
      fill: 'pigment-deep',
      d: 'M335.06 784.32 C329.83 801.85 342.71 847.14 345.53 878.85 C348.37 910.83 344.85 960.47 352.01 975.41 C354.75 981.12 359.08 985.13 362.41 984.99 C365.74 984.85 369.73 980.51 371.99 974.59 C377.92 959.04 372 909.44 370.47 877.15 C368.96 845.14 371.41 797.99 362.94 781.68 C359.08 774.27 352.33 768.62 347.68 769.06 C343.03 769.5 337.45 776.32 335.06 784.32 Z',
    },
    {
      id: 'hindleg-tarsus',
      rank: 'detail',
      fill: 'pigment-deep',
      d: 'M354.02 974.51 C348.94 985.12 347.26 1028.92 351.01 1039.57 C352.48 1043.72 355.24 1046.84 357.57 1046.99 C359.9 1047.13 363.03 1044.37 364.99 1040.43 C370.02 1030.32 373.72 986.64 369.98 975.49 C368.43 970.84 365.15 967.18 362.49 967.02 C359.83 966.85 356.13 970.09 354.02 974.51 Z',
    },
    {
      id: 'hindleg-tarsus',
      rank: 'detail',
      fill: 'pigment-deep',
      d: 'M349.02 1047.42 C344.27 1056.94 342.4 1098.19 345.52 1107.54 C346.64 1110.9 348.72 1113.33 350.54 1113.48 C352.37 1113.63 354.82 1111.58 356.48 1108.46 C361.1 1099.75 366.09 1058.76 362.98 1048.58 C361.71 1044.45 358.91 1041.22 356.58 1041.02 C354.26 1040.83 350.95 1043.56 349.02 1047.42 Z',
    },
    {
      id: 'hindleg-tarsus',
      rank: 'detail',
      fill: 'ink',
      d: 'M344.52 1115.5 C341.07 1122.65 341.5 1154.02 343.51 1159.77 C344.08 1161.4 344.94 1162.41 345.77 1162.49 C346.6 1162.57 347.64 1161.72 348.49 1160.23 C351.5 1154.93 357.58 1124.15 355.48 1116.5 C354.6 1113.29 352.32 1110.69 350.5 1110.52 C348.67 1110.36 345.97 1112.51 344.52 1115.5 Z',
    },
    {
      id: 'midleg-femur',
      rank: 'structure',
      fill: 'pigment-deep',
      d: 'M208.2 414.36 C216.15 429 245.32 443.25 263.22 457.61 C280.55 471.51 299.93 494.57 313.98 499.16 C321.97 501.77 331.82 501.74 335.16 498.02 C338.5 494.3 337.48 484.51 334.02 476.84 C327.9 463.27 303.19 445.68 286.78 430.39 C269.83 414.6 249.74 388.85 233.8 383.64 C223.72 380.34 209.9 381.07 205.64 386.2 C201.37 391.32 203.14 405.06 208.2 414.36 Z',
    },
    {
      id: 'midleg-tibia',
      rank: 'structure',
      fill: 'pigment-deep',
      d: 'M310.82 492.71 C310.1 510.15 332.89 547.9 342.04 575.64 C351.01 602.82 356.01 645.35 365.31 657.45 C369.1 662.39 374.22 665.51 377.45 664.69 C380.68 663.88 383.71 658.7 384.69 652.55 C387.14 637.34 373.76 596.29 365.96 568.36 C357.99 539.86 348.89 496.45 337.18 483.29 C331.69 477.11 323.69 473.25 319.29 474.82 C314.9 476.39 311.15 484.46 310.82 492.71 Z',
    },
    {
      id: 'midleg-tarsus',
      rank: 'detail',
      fill: 'pigment-deep',
      d: 'M367.22 656.85 C365.45 668.44 376.53 710.56 383.19 719.62 C385.8 723.16 389.35 725.35 391.62 724.81 C393.89 724.27 396.08 720.72 396.81 716.38 C398.68 705.29 389.58 662.69 382.78 653.15 C379.94 649.16 375.74 646.6 373.15 647.22 C370.55 647.84 367.96 652.01 367.22 656.85 Z',
    },
    {
      id: 'midleg-tarsus',
      rank: 'detail',
      fill: 'pigment-deep',
      d: 'M385.18 727.59 C383.55 738.27 394.72 779.19 400.64 787.25 C402.75 790.11 405.46 791.77 407.25 791.36 C409.04 790.94 410.74 788.25 411.36 784.75 C413.1 774.9 405 733.27 398.82 724.41 C396.34 720.86 392.68 718.65 390.41 719.18 C388.14 719.71 385.84 723.31 385.18 727.59 Z',
    },
    {
      id: 'midleg-tarsus',
      rank: 'detail',
      fill: 'ink',
      d: 'M402.64 795.22 C401.55 803.19 411.83 833.64 415.56 838.55 C416.6 839.93 417.74 840.62 418.55 840.44 C419.37 840.25 420.09 839.13 420.44 837.45 C421.68 831.41 417.79 799.5 413.36 792.78 C411.53 789.99 408.57 788.23 406.78 788.64 C404.99 789.04 403.09 791.91 402.64 795.22 Z',
    },
    {
      id: 'foreleg-femur',
      rank: 'structure',
      fill: 'pigment-deep',
      d: 'M101.74 186.83 C123.17 187.67 165.27 163.18 196.21 150.89 C226.43 138.9 271.6 127.31 285.3 114.03 C291.73 107.81 295.8 99.38 294.03 94.7 C292.27 90.02 283.63 86.39 274.7 85.97 C255.68 85.07 214.48 106.7 183.79 117.11 C152.35 127.76 104.26 134.95 88.26 149.17 C79.78 156.7 73.92 168.46 76.17 174.74 C78.42 181.02 90.4 186.39 101.74 186.83 Z',
    },
    // The fore tibia, with the three teeth a chafer digs with.
    //
    // Drawn as a taper rather than as three separate spurs: at eighty pixels a
    // spur is a burr on the outline, and the widening towards the tip is what
    // actually reads.
    {
      id: 'foreleg-tibia',
      rank: 'structure',
      fill: 'pigment-deep',
      d: 'M289.9 109.9 C305.24 103.43 328.86 71.01 347.43 50.95 C365.86 31.05 395.77 4.87 400.92 -9.97 C403.28 -16.76 403 -24.24 400.03 -26.92 C397.05 -29.6 389.58 -29.08 383.08 -26.03 C368.94 -19.38 347.32 13.77 328.57 33.05 C309.67 52.49 276.53 74.84 270.1 90.1 C266.94 97.61 266.8 106.6 270.1 109.9 C273.4 113.2 282.38 113.07 289.9 109.9 Z',
    },
    {
      id: 'foreleg-tarsus',
      rank: 'detail',
      fill: 'pigment-deep',
      d: 'M399.35 -14.85 C407.35 -22.78 422.39 -60.42 422.43 -71.24 C422.45 -75.6 420.9 -79.51 418.76 -80.43 C416.61 -81.35 412.71 -79.78 409.57 -76.76 C401.76 -69.27 384.88 -32.41 384.65 -21.15 C384.55 -16.3 386.4 -11.7 388.85 -10.65 C391.3 -9.6 395.91 -11.43 399.35 -14.85 Z',
    },
    {
      id: 'foreleg-tarsus',
      rank: 'detail',
      fill: 'pigment-deep',
      d: 'M424.61 -79.71 C431.18 -87.31 441.88 -122.91 441.2 -132.2 C440.94 -135.69 439.53 -138.6 437.8 -139.2 C436.07 -139.8 433.16 -138.39 430.8 -135.8 C424.53 -128.92 410.93 -94.32 411.39 -84.29 C411.58 -80.04 413.51 -76.15 415.71 -75.39 C417.92 -74.62 421.83 -76.49 424.61 -79.71 Z',
    },
    {
      id: 'foreleg-tarsus',
      rank: 'detail',
      fill: 'ink',
      d: 'M443.24 -140.34 C447.8 -146.19 453.09 -173.56 452.38 -179.25 C452.17 -180.94 451.55 -182.13 450.75 -182.38 C449.96 -182.63 448.76 -182.02 447.62 -180.75 C443.77 -176.51 432.39 -151.06 432.76 -143.66 C432.92 -140.39 434.6 -137.31 436.34 -136.76 C438.09 -136.2 441.24 -137.76 443.24 -140.34 Z',
    },
    // The pygidium — the reason the wing cases stop short.
    //
    // A chafer's elytra leave the last abdominal segment uncovered, and it is
    // one of the characters that puts this beetle in Cetoniinae rather than
    // with the other big green scarabs. Drawn behind the elytra so they overlap
    // its front edge, which is what the reference shows.
    {
      id: 'abdomen',
      rank: 'outline',
      fill: 'pigment-deep',
      d: 'M0 872 C34.67 872 90.89 871.52 104 890 C114.91 905.37 101.79 942.39 92 962 C83.27 979.48 67.75 995.02 52 1004 C36.89 1012.62 17.33 1016 0 1016 C-17.33 1016 -36.89 1012.62 -52 1004 C-67.75 995.02 -83.27 979.48 -92 962 C-101.79 942.39 -114.91 905.37 -104 890 C-90.89 871.52 -34.67 872 0 872 Z',
      mirror: false,
    },
    // One wing case. The suture between the pair runs down the midline, so the
    // inner edge of this shape is the axis and the renderer's reflection draws
    // the other one against it.
    {
      id: 'elytron',
      rank: 'outline',
      fill: 'pigment',
      d: 'M0 388 C0 359.45 79.84 383.68 120 384 C160.51 384.32 221.56 371.52 242 390 C257.89 404.37 250.16 434.62 253 463 C256.92 502.25 259.28 556.03 260 604 C260.75 653.95 262.72 708.54 257 757 C251.71 801.84 246.64 851.46 229 885 C214.56 912.44 190.9 932.67 169 949 C149.22 963.75 126.99 974.18 105 981 C83.94 987.53 59.06 989.87 40 990 C25.06 990.1 0 996.99 0 985 C0 938.86 0 451.67 0 388 Z',
    },
    // The striae — the shallow longitudinal grooves on the wing case. Four,
    // from one guide to the other, so they stay in step with each other and
    // with the margin.
    {
      id: 'stria',
      rank: 'structure',
      fill: 'none',
      d: 'M56 440 C56 440 54.73 619.89 54 700 C53.38 768.84 52 892 52 892',
      clipTo: 'elytron',
    },
    {
      id: 'stria',
      rank: 'structure',
      fill: 'none',
      d: 'M108 438.67 C108 438.67 111.82 620.07 110 700 C108.46 767.84 100 888 100 888',
      clipTo: 'elytron',
    },
    {
      id: 'stria',
      rank: 'structure',
      fill: 'none',
      d: 'M160 437.33 C160 437.33 168.98 620.3 166 700 C163.5 766.86 148 884 148 884',
      clipTo: 'elytron',
    },
    {
      id: 'stria',
      rank: 'structure',
      fill: 'none',
      d: 'M212 436 C212 436 226.2 620.57 222 700 C218.52 765.9 196 880 196 880',
      clipTo: 'elytron',
    },
    {
      id: 'hatching',
      rank: 'detail',
      fill: 'none',
      d: 'M92 470 C92 470 86 620 86 620',
      clipTo: 'elytron',
    },
    {
      id: 'hatching',
      rank: 'detail',
      fill: 'none',
      d: 'M120.8 516 C120.8 516 110 664 110 664',
      clipTo: 'elytron',
    },
    {
      id: 'hatching',
      rank: 'detail',
      fill: 'none',
      d: 'M149.6 562 C149.6 562 134 708 134 708',
      clipTo: 'elytron',
    },
    {
      id: 'hatching',
      rank: 'detail',
      fill: 'none',
      d: 'M178.4 608 C178.4 608 158 752 158 752',
      clipTo: 'elytron',
    },
    {
      id: 'hatching',
      rank: 'detail',
      fill: 'none',
      d: 'M207.2 654 C207.2 654 182 796 182 796',
      clipTo: 'elytron',
    },
    {
      id: 'hatching',
      rank: 'detail',
      fill: 'none',
      d: 'M236 700 C236 700 206 840 206 840',
      clipTo: 'elytron',
    },
    // The white flecks, which are the identification.
    //
    // Broken, uneven and asymmetric on the animal; drawn as five dashes on the
    // right wing case and reflected, because a plate that scattered them
    // differently on each side would be drawing a specimen rather than the
    // species. Bare paper clipped to the wing case, not holes in it — the
    // surface carries on underneath, and the reference shows it doing so.
    {
      id: 'marking',
      rank: 'detail',
      fill: 'surface',
      d: 'M207.63 594.71 C208.63 601.82 192.59 609.95 171.81 612.87 C151.03 615.79 133.37 612.4 132.37 605.29 C131.37 598.18 147.41 590.05 168.19 587.13 C188.97 584.21 206.63 587.6 207.63 594.71 Z',
      clipTo: 'elytron',
    },
    {
      id: 'marking',
      rank: 'detail',
      fill: 'surface',
      d: 'M125.88 613.7 C126.4 618.64 117.02 623.68 104.94 624.95 C92.86 626.22 82.64 623.24 82.12 618.3 C81.6 613.36 90.98 608.32 103.06 607.05 C115.14 605.78 125.36 608.76 125.88 613.7 Z',
      clipTo: 'elytron',
    },
    {
      id: 'marking',
      rank: 'detail',
      fill: 'surface',
      d: 'M199.81 752.36 C199.18 759.51 176.38 763.36 148.87 760.95 C121.36 758.54 99.56 750.79 100.19 743.64 C100.82 736.49 123.62 732.64 151.13 735.05 C178.64 737.46 200.44 745.21 199.81 752.36 Z',
      clipTo: 'elytron',
    },
    {
      id: 'marking',
      rank: 'detail',
      fill: 'surface',
      d: 'M161.58 877.32 C160.63 883.32 144.83 885.8 126.28 882.86 C107.73 879.93 93.47 872.68 94.42 866.68 C95.37 860.68 111.17 858.2 129.72 861.14 C148.27 864.07 162.53 871.32 161.58 877.32 Z',
      clipTo: 'elytron',
    },
    {
      id: 'marking',
      rank: 'detail',
      fill: 'surface',
      d: 'M231.47 685.65 C232.53 689.93 225.58 695.36 215.94 697.76 C206.29 700.17 197.6 698.64 196.53 694.35 C195.47 690.07 202.42 684.64 212.06 682.24 C221.71 679.83 230.4 681.36 231.47 685.65 Z',
      clipTo: 'elytron',
    },
    // The suture, drawn once on the axis. Reflecting it would put a second copy
    // a hair off the first and show as a doubled line down the beetle's back.
    {
      id: 'seam',
      rank: 'structure',
      fill: 'none',
      d: 'M0 400 C0 400 0 602.45 0 700 C0 792.89 0 972 0 972',
      mirror: false,
    },
    {
      id: 'scutellum',
      rank: 'structure',
      fill: 'pigment-deep',
      d: 'M0 378 C15.33 378 40.99 380.23 46 390 C51.43 400.57 34.27 426.72 26 442 C18.61 455.64 8.67 478 0 478 C-8.67 478 -18.61 455.64 -26 442 C-34.27 426.72 -51.43 400.57 -46 390 C-40.99 380.23 -15.33 378 0 378 Z',
      mirror: false,
    },
    // The pronotum: a broad shield, widest where it meets the wing cases and
    // narrowing forward to about half that across the front margin.
    {
      id: 'pronotum',
      rank: 'outline',
      fill: 'pigment',
      d: 'M0 124 C30.67 124 66.77 117.82 92 130 C116.42 141.79 133.99 170.46 150 194 C165.97 217.47 178.87 243.67 188 271 C197.43 299.23 204 338.76 205 361 C205.59 373.97 209.32 384.95 202 392 C188.74 404.77 133.84 396.67 100 398 C66.51 399.32 33.33 400 0 400 C-33.33 400 -66.51 399.32 -100 398 C-133.84 396.67 -188.74 404.77 -202 392 C-209.32 384.95 -205.59 373.97 -205 361 C-204 338.76 -197.43 299.23 -188 271 C-178.87 243.67 -165.97 217.47 -150 194 C-133.99 170.46 -116.42 141.79 -92 130 C-66.77 117.82 -30.67 124 0 124 Z',
      mirror: false,
    },
    {
      id: 'hatching',
      rank: 'detail',
      fill: 'none',
      d: 'M16 240 C16 240 16 340 16 340',
      clipTo: 'pronotum',
    },
    {
      id: 'hatching',
      rank: 'detail',
      fill: 'none',
      d: 'M59.33 240 C59.33 240 63.33 338.67 63.33 338.67',
      clipTo: 'pronotum',
    },
    {
      id: 'hatching',
      rank: 'detail',
      fill: 'none',
      d: 'M102.67 240 C102.67 240 110.67 337.33 110.67 337.33',
      clipTo: 'pronotum',
    },
    {
      id: 'hatching',
      rank: 'detail',
      fill: 'none',
      d: 'M146 240 C146 240 158 336 158 336',
      clipTo: 'pronotum',
    },
    {
      id: 'head',
      rank: 'outline',
      fill: 'pigment-deep',
      d: 'M0 4 C14 4 31.84 -9.89 42 -4 C54.17 3.06 56.95 34.83 62 54 C66.78 72.14 79.7 95.67 72 108 C63.02 122.38 24 128 0 128 C-24 128 -63.02 122.38 -72 108 C-79.7 95.67 -66.78 72.14 -62 54 C-56.95 34.83 -54.17 3.06 -42 -4 C-31.84 -9.89 -14 4 0 4 Z',
      mirror: false,
    },
    {
      id: 'eye',
      rank: 'detail',
      fill: 'ink',
      d: 'M92.27 87.87 C95.42 94.93 89.79 104.3 79.69 108.79 C69.6 113.28 58.87 111.2 55.73 104.13 C52.58 97.07 58.21 87.7 68.31 83.21 C78.4 78.72 89.13 80.8 92.27 87.87 Z',
    },
    // A lamellate club, which is what puts this beetle in the Scarabaeoidea.
    //
    // Three flat plates that open like a fan; drawn as one filled club with two
    // lines across it, because at plate size three separate lamellae is three
    // smudges. `morphology.antennae` says `lamellate` and this is the drawing
    // of that word.
    {
      id: 'antenna',
      rank: 'structure',
      fill: 'none',
      d: 'M42 76 C42 76 64.88 61.85 76 56 C86.18 50.64 106 42 106 42',
    },
    {
      id: 'antenna',
      rank: 'detail',
      fill: 'pigment-deep',
      d: 'M116.6 52.29 C123.86 50.83 131.2 43.97 137.5 38.87 C143.62 33.93 150.95 28.5 153.98 22.26 C156.67 16.73 158.92 7.44 156.26 4.02 C153.6 0.6 144 0.51 138.02 1.74 C131.39 3.1 124.84 8.88 118.5 13.13 C111.96 17.51 103.16 21.54 99.4 27.71 C95.87 33.51 92.84 44.51 95.71 48.6 C98.58 52.7 109.89 53.63 116.6 52.29 Z',
    },
    {
      id: 'antenna',
      rank: 'detail',
      fill: 'none',
      d: 'M114 22 C114 22 124 40 124 40',
    },
    {
      id: 'antenna',
      rank: 'detail',
      fill: 'none',
      d: 'M130 12 C130 12 140 30 140 30',
    },
  ],
};
