// Generated from ../landmarks/chrysolina-coerulans.json by `npm run plate:build`.
//
// Do not edit this file. Edit the landmarks and build again; `npm run
// plate:verify` fails the check if the two drift apart.

import type { SpeciesPlate } from '@/lib/plate';

/**
 * *Chrysolina coerulans*, dorsal — the blue mint beetle.
 *
 * The fourth Hochdanz lithograph from Calwer's *Käferbuch* (1876), and the
 * smallest reference in the folder at 229 × 250 pixels — smaller even than the
 * seven-spot's. That turned out not to matter for the same reason it did not
 * matter there: what a leaf beetle needs from a reference is the outline, the
 * puncture rows and where the short legs sit, and all three survive at that
 * size. `references/chrysolina-coerulans.jpg` is the file.
 *
 * ## What the drawing has to get right
 *
 * The **outline**, which is the whole animal. A Chrysolina is 0.65 as wide as
 * it is long and strongly domed — very nearly a hemisphere — and the tracing
 * reflex is to draw the beetle-shaped oval that every other Coleoptera plate
 * here wanted. Beside the violet ground beetle at 0.39 the difference is the
 * identification, so the margin is measured row by row off the lithograph.
 *
 * Then the **legs**, which are short, thick and held close in. A leaf beetle
 * spends its life on one plant and walks nowhere; drawn at the ground beetle's
 * proportions it becomes a different family.
 *
 * The blue is not drawn, because it cannot be: the animal is metallic and the
 * plate is inked in one seasonal earth. `morphology.colourFamily` says
 * `metallic` in words instead, which is where that fact belongs.
 *
 * ## Plate space
 *
 * y = 0 at the front of the head, y = 1000 at the elytral apex. The head is
 * mostly under the pronotum — 90 to 310 — which is why the visible head is
 * only the first 150 units. The antennae reach above y = -160 and the legs out
 * to about x = 480.
 */
export const CHRYSOLINA_COERULANS_PLATE: SpeciesPlate = {
  species: 'chrysolina-coerulans',
  order: 'coleoptera',
  sex: 'unsexed',
  hallmark: 'the domed, almost circular outline and the rows of punctures across it',
  reference: {
    title: 'Käferbuch. Naturgeschichte der Käfer Europas, table 44 figure 6',
    artist: 'Emil Hochdanz',
    year: 1876,
    source: 'https://commons.wikimedia.org/wiki/File:Chrysolina.coerulans.-.calwer.44.06.jpg',
    licence: 'Public domain (PD-old-100-1923)',
  },
  parts: [
    // The legs first, so they pass under the body.
    //
    // Short and stout: the whole leg from coxa to claw is about a body length
    // in the lithograph, against nearly two for the ground beetle. Femora at
    // around seven per cent of the width across the wing cases — a smaller
    // fraction than the Carabus, because this beetle is so much broader.
    {
      id: 'hindleg-femur',
      rank: 'structure',
      fill: 'pigment-deep',
      d: 'M158.34 658.66 C170.73 675.64 213.24 690.63 238.93 706.66 C263.05 721.71 290.59 748.25 308.2 751.89 C317.69 753.85 328.62 752.43 331.89 747.8 C335.16 743.17 332.84 732.41 327.8 724.11 C318.39 708.6 284.59 689.96 261.07 673.34 C236.05 655.66 202.52 625.06 181.66 621.34 C169.72 619.21 155.23 622.12 151.34 628.34 C147.46 634.56 151.21 648.88 158.34 658.66 Z',
    },
    {
      id: 'hindleg-tibia',
      rank: 'structure',
      fill: 'pigment-deep',
      d: 'M305.35 747.79 C309.95 763.87 339.25 787.94 354.63 808.17 C369.39 827.57 383.83 858.74 396.02 866.66 C401.94 870.51 409.33 872.2 412.66 869.98 C415.98 867.77 417.26 860.31 415.98 853.34 C413.34 838.93 391.25 812.25 377.37 791.83 C362.89 770.53 345.18 736.76 330.65 728.21 C322.87 723.63 312.42 722.08 308.21 725.35 C303.99 728.61 302.87 739.14 305.35 747.79 Z',
    },
    {
      id: 'hindleg-tarsus',
      rank: 'detail',
      fill: 'pigment-deep',
      d: 'M396.61 865.74 C398.35 875.31 412.67 895.39 420.32 900.69 C424.52 903.6 430.13 905.24 432.69 903.68 C435.25 902.12 436.35 896.37 435.68 891.31 C434.45 882.08 423.11 860.18 415.39 854.26 C410.7 850.68 403.39 848.7 400.26 850.61 C397.14 852.53 395.56 859.93 396.61 865.74 Z',
    },
    {
      id: 'hindleg-tarsus',
      rank: 'detail',
      fill: 'pigment-deep',
      d: 'M421.95 906.02 C422.74 914.85 434.79 935.92 441.29 941.35 C444.63 944.14 449.12 945.83 451.35 944.71 C453.59 943.59 454.94 938.99 454.71 934.65 C454.26 926.18 444.63 903.9 438.05 897.98 C434.35 894.64 428.66 892.61 425.98 893.95 C423.29 895.29 421.5 901.07 421.95 906.02 Z',
    },
    {
      id: 'hindleg-tarsus',
      rank: 'detail',
      fill: 'ink',
      d: 'M442.92 946.48 C442.89 955.01 456.64 980.43 461.17 984.99 C462.6 986.43 464.05 987.16 464.99 986.83 C465.93 986.5 466.61 985.02 466.83 983.01 C467.53 976.62 462.42 948.18 457.08 941.52 C454.41 938.2 449.88 936.1 447.52 936.92 C445.16 937.75 442.93 942.22 442.92 946.48 Z',
    },
    {
      id: 'midleg-femur',
      rank: 'structure',
      fill: 'pigment-deep',
      d: 'M142.28 400.6 C156.81 413.86 196.8 419.52 222.77 428.65 C247.17 437.22 276.83 454.33 293.69 453.78 C303.22 453.48 313.68 449.58 315.78 444.31 C317.89 439.05 313.01 429.02 306.31 422.22 C294.43 410.15 261.16 401.5 237.23 391.35 C211.75 380.55 177.47 358.96 157.72 359.4 C145.83 359.67 131.98 365.41 129.4 372.28 C126.83 379.14 133.49 392.59 142.28 400.6 Z',
    },
    {
      id: 'midleg-tibia',
      rank: 'structure',
      fill: 'pigment-deep',
      d: 'M292.06 451.89 C301.2 463.32 330.49 471.72 348.75 481.98 C366.26 491.81 386.91 510.07 399.53 512.11 C406.3 513.2 413.95 511.84 416.11 508.47 C418.26 505.1 416.3 497.59 412.47 491.89 C405.28 481.2 380.28 469.1 363.25 458.02 C345.5 446.48 322.53 426.19 307.94 424.11 C299.32 422.88 288.75 425.43 286.11 430.06 C283.46 434.69 286.64 445.11 292.06 451.89 Z',
    },
    {
      id: 'midleg-tarsus',
      rank: 'detail',
      fill: 'pigment-deep',
      d: 'M398.96 510.45 C402.83 517.29 416.91 526.89 424.24 528.91 C428.91 530.21 434.99 530.07 436.91 527.76 C438.83 525.46 437.88 519.45 435.76 515.09 C432.45 508.24 420.47 496.13 413.04 493.55 C407.81 491.73 399.9 492.14 397.55 494.96 C395.2 497.77 396.23 505.63 398.96 510.45 Z',
    },
    {
      id: 'midleg-tarsus',
      rank: 'detail',
      fill: 'pigment-deep',
      d: 'M427.95 532.66 C431.16 539.07 444.38 549.37 450.95 551.55 C454.88 552.85 459.87 552.89 461.55 551.05 C463.23 549.2 462.71 544.23 461.05 540.45 C458.25 534.12 446.74 521.94 440.05 519.34 C435.68 517.64 429.36 517.73 427.34 519.95 C425.32 522.17 425.84 528.47 427.95 532.66 Z',
    },
    {
      id: 'midleg-tarsus',
      rank: 'detail',
      fill: 'ink',
      d: 'M453.56 555.17 C456.3 560.86 471.13 570.42 475.83 572.07 C477.65 572.71 479.34 572.86 480.07 572.17 C480.79 571.49 480.72 569.79 480.17 567.93 C478.77 563.16 469.99 547.86 464.44 544.83 C461.02 542.97 455.65 542.84 453.83 544.56 C452.02 546.28 451.88 551.66 453.56 555.17 Z',
    },
    {
      id: 'foreleg-femur',
      rank: 'structure',
      fill: 'pigment-deep',
      d: 'M117.63 267.27 C138.26 261.21 169.19 225.3 192.44 205.66 C213.17 188.15 242.65 170.44 250.62 155.27 C255.07 146.8 256.81 135.81 253.27 131.38 C249.73 126.96 238.62 126.24 229.38 128.73 C212.86 133.17 189.26 158.13 167.56 174.34 C143.2 192.54 101.04 214.1 90.37 232.73 C84.32 243.3 82.19 257.88 86.73 263.63 C91.28 269.39 105.95 270.7 117.63 267.27 Z',
    },
    {
      id: 'foreleg-tibia',
      rank: 'structure',
      fill: 'pigment-deep',
      d: 'M251.94 152.66 C266.62 145.33 286.04 114.46 300.93 94.74 C315.2 75.86 336.75 50.91 339.76 36.97 C341.25 30.1 340.23 22.56 336.97 20.24 C333.72 17.91 326.24 19.4 320.24 23.03 C308.21 30.29 294.03 59.58 279.07 77.26 C263.43 95.72 233.61 116.14 228.06 131.34 C225 139.73 225.37 150.38 229.34 153.94 C233.32 157.49 243.91 156.66 251.94 152.66 Z',
    },
    {
      id: 'foreleg-tarsus',
      rank: 'detail',
      fill: 'pigment-deep',
      d: 'M339.33 35.83 C346.51 30.42 356.43 11.32 357.63 2.77 C358.33 -2.19 357.31 -8.04 354.77 -9.63 C352.23 -11.22 346.53 -9.57 342.37 -6.77 C335.2 -1.94 322.39 15.34 320.67 24.17 C319.57 29.83 321.06 37.38 324.17 39.33 C327.28 41.27 334.72 39.3 339.33 35.83 Z',
    },
    {
      id: 'foreleg-tarsus',
      rank: 'detail',
      fill: 'pigment-deep',
      d: 'M359.94 -3.76 C365.92 -8.9 374.05 -26.92 374.62 -34.47 C374.94 -38.69 373.74 -43.44 371.53 -44.62 C369.32 -45.79 364.71 -44.14 361.38 -41.53 C355.43 -36.85 345 -20.06 344.06 -12.24 C343.49 -7.45 345.12 -1.47 347.76 -0.06 C350.41 1.35 356.29 -0.62 359.94 -3.76 Z',
    },
    {
      id: 'foreleg-tarsus',
      rank: 'detail',
      fill: 'ink',
      d: 'M376.94 -41.14 C382.05 -46.95 387.15 -70.97 386.77 -76.86 C386.65 -78.85 386.07 -80.39 385.14 -80.77 C384.22 -81.15 382.72 -80.47 381.23 -79.14 C376.81 -75.22 363.52 -54.58 363.06 -46.86 C362.82 -42.72 364.83 -38.02 367.14 -37.06 C369.46 -36.11 374.2 -38.04 376.94 -41.14 Z',
    },
    // One wing case. Broad, high-shouldered and rounded off almost as a circle
    // would be — 0.65 as wide as the animal is long, measured off the
    // lithograph, against 0.39 for the ground beetle on the plate before this
    // one.
    {
      id: 'elytron',
      rank: 'outline',
      fill: 'pigment',
      d: 'M0 298 C0 268.14 88.74 294.87 130 300 C168.47 304.78 211.09 307.84 240 326 C266.54 342.67 286.5 371.64 300 400 C313.98 429.37 317.18 466.49 321 500 C324.78 533.16 324.31 565.61 323 600 C321.6 636.8 318.36 677.1 312 714 C305.85 749.7 298.79 785.16 286 818 C273.36 850.45 257.4 883.77 236 910 C215.16 935.55 187.29 959.24 160 974 C134.98 987.53 106.94 993.01 80 998 C53.6 1002.89 0 1022.5 0 1004 C0 949.11 0 367.58 0 298 Z',
    },
    // The puncture rows. Six, from a guide beside the suture to one inside the
    // margin — a Chrysolina's punctures are arranged in rough longitudinal rows
    // rather than scattered, and the rows are what the surface reads as.
    {
      id: 'stria',
      rank: 'structure',
      fill: 'none',
      d: 'M40 380 C40 380 36 560.03 38 650 C40 740.03 52 920 52 920',
      clipTo: 'elytron',
    },
    {
      id: 'stria',
      rank: 'structure',
      fill: 'none',
      d: 'M80 384 C80 384 86.7 561.86 85.6 650 C84.51 737.18 73.6 910 73.6 910',
      clipTo: 'elytron',
    },
    {
      id: 'stria',
      rank: 'structure',
      fill: 'none',
      d: 'M120 388 C120 388 137.53 563.91 133.2 650 C128.95 734.53 95.2 900 95.2 900',
      clipTo: 'elytron',
    },
    {
      id: 'stria',
      rank: 'structure',
      fill: 'none',
      d: 'M160 392 C160 392 188.37 566.19 180.8 650 C173.38 732.1 116.8 890 116.8 890',
      clipTo: 'elytron',
    },
    {
      id: 'stria',
      rank: 'structure',
      fill: 'none',
      d: 'M200 396 C200 396 239.1 568.7 228.4 650 C217.88 729.92 138.4 880 138.4 880',
      clipTo: 'elytron',
    },
    {
      id: 'stria',
      rank: 'structure',
      fill: 'none',
      d: 'M240 400 C240 400 289.58 571.4 276 650 C262.52 727.99 160 870 160 870',
      clipTo: 'elytron',
    },
    {
      id: 'hatching',
      rank: 'detail',
      fill: 'none',
      d: 'M60 856 C60 856 130 886 130 886',
      clipTo: 'elytron',
    },
    {
      id: 'hatching',
      rank: 'detail',
      fill: 'none',
      d: 'M70 817 C70 817 150.5 847 150.5 847',
      clipTo: 'elytron',
    },
    {
      id: 'hatching',
      rank: 'detail',
      fill: 'none',
      d: 'M80 778 C80 778 171 808 171 808',
      clipTo: 'elytron',
    },
    {
      id: 'hatching',
      rank: 'detail',
      fill: 'none',
      d: 'M90 739 C90 739 191.5 769 191.5 769',
      clipTo: 'elytron',
    },
    {
      id: 'hatching',
      rank: 'detail',
      fill: 'none',
      d: 'M100 700 C100 700 212 730 212 730',
      clipTo: 'elytron',
    },
    // The suture, drawn once on the axis. Reflecting it would lay a second copy
    // a hair off the first and show as a doubled line down the beetle's back.
    {
      id: 'seam',
      rank: 'structure',
      fill: 'none',
      d: 'M0 310 C0 310 0 536.5 0 650 C0 763.83 0 992 0 992',
      mirror: false,
    },
    {
      id: 'scutellum',
      rank: 'structure',
      fill: 'pigment-deep',
      d: 'M0 300 C15.33 300 42.68 300.41 46 308 C49.09 315.07 32.28 332.66 24 342 C16.73 350.2 8 362 0 362 C-8 362 -16.73 350.2 -24 342 C-32.28 332.66 -49.09 315.07 -46 308 C-42.68 300.41 -15.33 300 0 300 Z',
      mirror: false,
    },
    // The pronotum: transverse, widest where it meets the wing cases, and wide
    // enough that the head sits almost entirely under its front margin. That
    // retracted head is a Chrysomelidae character and it is why the visible
    // head here is only the first 150 units of plate space.
    {
      id: 'pronotum',
      rank: 'outline',
      fill: 'pigment',
      d: 'M0 88 C40 88 83.73 86.33 120 96 C153.11 104.83 187.49 118.55 210 140 C231.49 160.48 245.09 192.82 254 220 C262.17 244.9 274.92 281.72 264 296 C253.22 310.1 215.93 303.68 190 306 C161.52 308.55 130.8 309.01 100 310 C67.55 311.05 33.33 312 0 312 C-33.33 312 -67.55 311.05 -100 310 C-130.8 309.01 -161.52 308.55 -190 306 C-215.93 303.68 -253.22 310.1 -264 296 C-274.92 281.72 -262.17 244.9 -254 220 C-245.09 192.82 -231.49 160.48 -210 140 C-187.49 118.55 -153.11 104.83 -120 96 C-83.73 86.33 -40 88 0 88 Z',
      mirror: false,
    },
    {
      id: 'hatching',
      rank: 'detail',
      fill: 'none',
      d: 'M40 150 C40 150 44 280 44 280',
      clipTo: 'pronotum',
    },
    {
      id: 'hatching',
      rank: 'detail',
      fill: 'none',
      d: 'M88.67 160.67 C88.67 160.67 93.33 280 93.33 280',
      clipTo: 'pronotum',
    },
    {
      id: 'hatching',
      rank: 'detail',
      fill: 'none',
      d: 'M137.33 171.33 C137.33 171.33 142.67 280 142.67 280',
      clipTo: 'pronotum',
    },
    {
      id: 'hatching',
      rank: 'detail',
      fill: 'none',
      d: 'M186 182 C186 182 192 280 192 280',
      clipTo: 'pronotum',
    },
    {
      id: 'head',
      rank: 'outline',
      fill: 'pigment-deep',
      d: 'M0 -4 C18 -4 38.04 -3.28 54 4 C70.07 11.33 84.96 25.86 96 40 C106.87 53.93 119.09 72.15 120 88 C120.85 102.8 114.2 121.7 104 132 C93.33 142.78 72.88 146 56 150 C38.3 154.19 18.67 156 0 156 C-18.67 156 -38.3 154.19 -56 150 C-72.88 146 -93.33 142.78 -104 132 C-114.2 121.7 -120.85 102.8 -120 88 C-119.09 72.15 -106.87 53.93 -96 40 C-84.96 25.86 -70.07 11.33 -54 4 C-38.04 -3.28 -18 -4 0 -4 Z',
      mirror: false,
    },
    {
      id: 'eye',
      rank: 'detail',
      fill: 'ink',
      d: 'M112.63 62.47 C114.12 69.49 107.89 76.76 98.7 78.72 C89.52 80.67 80.86 76.56 79.37 69.53 C77.88 62.51 84.11 55.24 93.3 53.28 C102.48 51.33 111.14 55.44 112.63 62.47 Z',
    },
    // The antenna. Filiform, and drawn thickening very slightly towards the tip
    // rather than tapering — which is what a Chrysolina has, and is as far
    // towards a club as the character goes before the record would have to say
    // `clavate` instead.
    {
      id: 'antenna',
      rank: 'structure',
      fill: 'pigment-deep',
      d: 'M79.8 57.89 C90.36 55.1 106.72 40.62 112.07 31.44 C115.76 25.11 118.13 15.74 115.44 11.93 C112.75 8.11 103.12 7.21 95.93 8.56 C85.48 10.53 66.36 21.1 60.2 30.11 C55.52 36.95 52.84 49.17 56.11 53.8 C59.38 58.43 71.79 60 79.8 57.89 Z',
    },
    {
      id: 'antenna',
      rank: 'structure',
      fill: 'pigment-deep',
      d: 'M115.53 26.26 C124.67 22.73 138.92 8.39 142.85 -0.47 C145.57 -6.62 146.47 -15.67 143.53 -18.85 C140.58 -22.02 131.49 -21.78 125.15 -19.53 C116.02 -16.27 100.67 -3.11 96.47 5.74 C93.45 12.11 92.57 22.11 95.74 25.53 C98.92 28.95 108.95 28.8 115.53 26.26 Z',
    },
    {
      id: 'antenna',
      rank: 'detail',
      fill: 'pigment-deep',
      d: 'M146.48 -8.31 C154.46 -13.3 165.59 -29.85 167.68 -38.9 C169.09 -45.02 168.32 -53.31 165.1 -55.68 C161.87 -58.04 153.73 -56.28 148.32 -53.1 C140.32 -48.38 127.88 -32.79 125.52 -23.69 C123.86 -17.29 124.82 -8.08 128.31 -5.52 C131.81 -2.95 140.88 -4.81 146.48 -8.31 Z',
    },
    {
      id: 'antenna',
      rank: 'detail',
      fill: 'pigment-deep',
      d: 'M170.46 -46.12 C177.66 -51.77 187.37 -69.03 188.46 -78.12 C189.2 -84.29 187.37 -92.5 183.88 -94.46 C180.4 -96.42 172.43 -93.73 167.54 -89.88 C160.34 -84.23 150.63 -66.97 149.54 -57.88 C148.8 -51.71 150.63 -43.5 154.12 -41.54 C157.6 -39.58 165.57 -42.27 170.46 -46.12 Z',
    },
    {
      id: 'antenna',
      rank: 'detail',
      fill: 'pigment-deep',
      d: 'M192.02 -85.05 C198.64 -91.7 206.04 -109.67 206.02 -119.05 C206.01 -125.68 202.96 -134.37 198.95 -136.02 C194.94 -137.67 186.66 -133.65 181.98 -128.95 C175.36 -122.3 167.96 -104.33 167.98 -94.95 C167.99 -88.32 171.04 -79.63 175.05 -77.98 C179.06 -76.33 187.34 -80.35 192.02 -85.05 Z',
    },
    {
      id: 'antenna',
      rank: 'detail',
      fill: 'pigment-deep',
      d: 'M207.57 -126.67 C212.56 -134.05 214.28 -153.5 212.7 -161.7 C211.75 -166.61 209.2 -171.93 206.3 -172.7 C203.4 -173.47 198.56 -170.11 195.3 -166.3 C189.87 -159.96 181.75 -142.2 182.43 -133.33 C182.93 -126.93 187.48 -118.54 191.67 -117.43 C195.86 -116.32 203.97 -121.36 207.57 -126.67 Z',
    },
  ],
};
