// Generated from ../landmarks/eupoecila-australasiae.json by `npm run plate:build`.
//
// Do not edit this file. Edit the landmarks and build again; `npm run
// plate:verify` fails the check if the two drift apart.

import type { SpeciesPlate } from '@/lib/plate';

/**
 * *Eupoecila australasiae*, dorsal - the fiddler beetle.
 *
 * Traced from plate 1 of Edward Donovan's *An epitome of the natural history
 * of the insects of New Holland* (1805), where it is figured and named
 * *Cetonia australasiae* - the description the species still carries, and the
 * reason this figure is its type. It is the same sheet the king Christmas
 * beetle came off, three figures away, so the two plates in this collection
 * that show Australian animals were drawn by one hand in one year.
 * `references/eupoecila-australasiae.jpg` is that figure, cut from the sheet
 * and turned upright.
 *
 * ## What identifies it
 *
 * The **fiddle**: a dark field either side of the suture, broad at the
 * shoulder, waisted two thirds of the way down and closing at the apex, which
 * read across both wing cases at once is the outline of a violin. Then the
 * **two yellow lines** along the margins of an otherwise black pronotum -
 * which is the character Donovan's specific description opens with, before he
 * gets to the wing cases at all. Both are drawn.
 *
 * ## Which way round the animal is
 *
 * The ground here is the *pale* colour and the pattern is dark on top of it,
 * which is the opposite of every other beetle in this collection. A fiddler
 * beetle is a yellow-green insect with a black figure on it, not a black
 * insect with yellow marks. Drawn the other way round it keys out on the same
 * six characters and looks like a different animal, so the fills are the
 * thing to check first if this plate is ever redrawn.
 *
 * Donovan's hand-colouring makes the pale ground ferruginous - rust and ochre
 * - and his own Latin says *elytris ferrugineis*. The living animal is usually
 * lime-green to yellow. The plate is inked in one seasonal earth and takes no
 * position on which; `morphology.colourFamily` says `yellow`, which is what a
 * reader looking at the specimen would say, and the record's notes carry the
 * rest.
 *
 * ## Three colours, two pigments
 *
 * The figure has a black field, a rust band and a pale margin. A plate has one
 * pigment at two strengths, so the rust band is drawn as a *boundary* rather
 * than as a fill - a structure-rank line along its outer edge. That is also
 * what carries the pattern at eighty pixels, where the detail rank has gone
 * and the fills have flattened.
 *
 * ## Plate space
 *
 * y = 0 at the front margin of the clypeus, y = 1000 at the apex of the wing
 * cases. There is no pygidium in this drawing: Donovan's figure rounds the
 * elytra off over it and shows none, and `REQUIRED_PARTS` does not ask a
 * beetle for an abdomen. The middle legs reach past x = 750.
 */
export const EUPOECILA_AUSTRALASIAE_PLATE: SpeciesPlate = {
  species: 'eupoecila-australasiae',
  order: 'coleoptera',
  sex: 'unsexed',
  hallmark:
    'the dark fiddle across the pale wing cases, and the two yellow lines along the black pronotum',
  reference: {
    title:
      'Cetonia australasiae, from An epitome of the natural history of the insects of New Holland, plate 1',
    artist: 'Edward Donovan',
    year: 1805,
    source: 'https://archive.org/details/epitomeofnatura00dono',
    licence: 'Public domain (published 1805, author died 1837)',
  },
  parts: [
    // Legs first, so they pass under the wing cases.
    //
    // Slighter than the Christmas beetle's, and that is the point of drawing
    // the two together: both are scarabs, one digs and one visits flowers, and
    // the femora come out at about five and a half per cent of the width
    // across the wing cases against the other's eight. `eupoecila-australasiae
    // .plate.test.ts` measures both and asserts the difference, because a
    // proportion is only a fact when something else is beside it.
    {
      id: 'hindleg-femur',
      rank: 'structure',
      fill: 'pigment-deep',
      d: 'M141.28 717.69 C154.54 737.53 210.14 761.01 243.23 784.3 C276.14 807.46 318.58 851.35 339.32 856.99 C347.73 859.27 356.1 858.34 358.99 854.68 C361.88 851.01 360.85 842.67 356.68 835.01 C346.31 816.03 295.01 782.43 262.77 757.7 C230.37 732.85 186.17 691.48 162.72 686.31 C151.75 683.9 139.88 686.05 136.31 691.28 C132.74 696.51 135.05 708.37 141.28 717.69 Z',
    },
    {
      id: 'hindleg-tibia',
      rank: 'structure',
      fill: 'pigment-deep',
      d: 'M338.24 855.33 C346.13 875.32 397.49 914.67 425.13 944.09 C451.44 972.07 484.1 1019.6 500.46 1027.57 C506.26 1030.39 512.05 1030.73 514.57 1028.54 C517.08 1026.35 517.54 1020.57 515.54 1014.43 C509.89 997.08 468.44 956.8 442.87 927.91 C415.99 897.55 377.43 845.49 357.76 836.67 C350.07 833.22 341.93 833.13 338.67 836.24 C335.42 839.35 335.15 847.49 338.24 855.33 Z',
    },
    {
      id: 'hindleg-tarsus',
      rank: 'detail',
      fill: 'pigment-deep',
      d: 'M501.06 1024.98 C502.98 1038.94 534.89 1091.29 545.36 1099.23 C548.78 1101.82 552.35 1102.72 554.23 1101.64 C556.11 1100.56 557.15 1097.02 556.64 1092.77 C555.08 1079.72 526.02 1025.73 514.94 1017.02 C510.93 1013.87 506.33 1012.73 504.02 1014.06 C501.71 1015.39 500.37 1019.93 501.06 1024.98 Z',
    },
    {
      id: 'hindleg-tarsus',
      rank: 'detail',
      fill: 'pigment-deep',
      d: 'M550.03 1114.58 C550.3 1127.08 574.43 1180.02 582.95 1188.18 C585.6 1190.72 588.5 1191.78 590.18 1191.05 C591.87 1190.32 593.08 1187.48 593.05 1183.82 C592.94 1172.02 570.89 1118.18 561.97 1109.42 C558.95 1106.46 555.41 1105.17 553.42 1106.03 C551.43 1106.89 549.94 1110.36 550.03 1114.58 Z',
    },
    {
      id: 'hindleg-tarsus',
      rank: 'detail',
      fill: 'ink',
      d: 'M587.77 1203.71 C587.22 1214.13 606.41 1260.97 611.62 1266.78 C612.82 1268.11 613.99 1268.64 614.78 1268.38 C615.57 1268.12 616.2 1267 616.38 1265.22 C617.14 1257.45 604.84 1208.35 598.23 1200.29 C595.98 1197.55 593.03 1196.2 591.29 1196.77 C589.54 1197.35 587.96 1200.18 587.77 1203.71 Z',
    },
    {
      id: 'midleg-femur',
      rank: 'structure',
      fill: 'pigment-deep',
      d: 'M129.45 373.83 C147.43 390.08 208.51 400.92 247.23 414.46 C285.02 427.67 337.78 454.98 359.05 454.09 C367.73 453.73 375.44 450.32 377.09 445.95 C378.75 441.59 375.23 433.93 368.95 427.91 C353.59 413.15 296.02 398.31 258.77 383.54 C220.58 368.4 166.8 337.43 142.55 338.17 C131.3 338.51 120.35 343.5 118.17 349.45 C115.98 355.39 121.1 366.29 129.45 373.83 Z',
    },
    {
      id: 'midleg-tibia',
      rank: 'structure',
      fill: 'pigment-deep',
      d: 'M358.71 453.42 C372.69 467.48 426.82 481.06 460.2 495 C492.87 508.64 539.48 535.8 556.91 536.13 C563.31 536.25 568.76 534.13 570.13 531.09 C571.49 528.05 569.44 522.57 565.09 517.87 C553.22 505.07 502.08 487.73 469.8 473 C436.83 457.96 389.14 428.91 369.29 428.58 C361.01 428.44 353.34 431.57 351.58 435.71 C349.82 439.85 352.88 447.55 358.71 453.42 Z',
    },
    {
      id: 'midleg-tarsus',
      rank: 'detail',
      fill: 'pigment-deep',
      d: 'M557.77 534.32 C565.94 542.66 606.44 558.83 617.38 558.95 C621.51 558.99 625.07 557.6 625.95 555.62 C626.82 553.64 625.44 550.07 622.62 547.05 C615.15 539.06 575.89 520.08 564.23 519.68 C559.34 519.51 554.75 521.33 553.68 523.77 C552.6 526.21 554.36 530.83 557.77 534.32 Z',
    },
    {
      id: 'midleg-tarsus',
      rank: 'detail',
      fill: 'pigment-deep',
      d: 'M627.55 567.02 C635.27 574.52 676.74 590.24 686.93 590.09 C690.49 590.04 693.4 588.77 694.09 587.07 C694.79 585.37 693.59 582.43 691.07 579.91 C683.88 572.69 643.22 555 632.45 554.98 C628.36 554.97 624.8 556.54 623.98 558.55 C623.16 560.56 624.62 564.17 627.55 567.02 Z',
    },
    {
      id: 'midleg-tarsus',
      rank: 'detail',
      fill: 'ink',
      d: 'M697.17 598.19 C704.33 604.28 745.1 614.93 752.17 614.36 C753.93 614.22 755.08 613.62 755.36 612.83 C755.63 612.04 755.11 610.85 753.83 609.64 C748.67 604.77 710.22 587.55 700.83 587.81 C697.36 587.91 694.42 589.45 693.81 591.17 C693.2 592.9 694.54 595.95 697.17 598.19 Z',
    },
    {
      id: 'foreleg-femur',
      rank: 'structure',
      fill: 'pigment-deep',
      d: 'M97.87 175.05 C119.05 170.78 157.56 134.33 186.62 113.88 C215.03 93.89 260.15 69.72 270.33 53.74 C274.63 46.99 276.18 39.25 273.74 35.67 C271.3 32.09 263.52 30.72 255.67 32.26 C237.12 35.91 198.63 69.54 169.38 88.12 C139.47 107.11 90.48 127.26 78.13 144.95 C72.12 153.55 69.66 164.85 72.95 169.87 C76.24 174.89 87.58 177.13 97.87 175.05 Z',
    },
    {
      id: 'foreleg-tibia',
      rank: 'structure',
      fill: 'pigment-deep',
      d: 'M269.39 54.32 C287.4 51.98 326.24 21.66 353.79 4.94 C380.72 -11.41 423.56 -31.98 432.89 -44.85 C436.42 -49.73 437.78 -55.17 436.15 -57.89 C434.52 -60.6 429.08 -61.97 423.11 -61.15 C407.4 -58.98 369.64 -30.24 342.21 -14.94 C314.16 0.71 267.88 17.5 256.61 31.68 C251.71 37.84 249.55 45.62 251.68 49.39 C253.81 53.17 261.58 55.33 269.39 54.32 Z',
    },
    {
      id: 'foreleg-tarsus',
      rank: 'detail',
      fill: 'pigment-deep',
      d: 'M432.58 -46.44 C443.96 -49.09 478.93 -75.37 484.72 -84.67 C486.9 -88.18 487.57 -91.94 486.33 -93.72 C485.09 -95.5 481.32 -96.17 477.28 -95.33 C466.55 -93.1 429.83 -69.33 423.42 -59.56 C420.74 -55.47 419.91 -50.61 421.44 -48.42 C422.97 -46.23 427.82 -45.33 432.58 -46.44 Z',
    },
    {
      id: 'foreleg-tarsus',
      rank: 'detail',
      fill: 'pigment-deep',
      d: 'M496.1 -95.95 C506.86 -99.24 543.46 -130.33 548.47 -139.73 C550.15 -142.9 550.43 -146.04 549.27 -147.47 C548.12 -148.89 544.99 -149.27 541.53 -148.27 C531.31 -145.31 493.34 -115.9 487.9 -106.05 C485.91 -102.43 485.59 -98.59 486.95 -96.9 C488.32 -95.22 492.15 -94.75 496.1 -95.95 Z',
    },
    {
      id: 'foreleg-tarsus',
      rank: 'detail',
      fill: 'ink',
      d: 'M559.93 -150.16 C568.75 -154.19 597.24 -188.41 599.79 -195.25 C600.41 -196.91 600.34 -198.21 599.75 -198.79 C599.15 -199.37 597.86 -199.4 596.21 -198.75 C589.43 -196.04 555.89 -166.75 552.07 -157.84 C550.69 -154.64 550.85 -151.35 552.16 -150.07 C553.47 -148.78 556.76 -148.71 559.93 -150.16 Z',
    },
    // One wing case, pale. The ground colour is the light one here and the
    // pattern is drawn on top of it, which is the opposite of every other
    // beetle in the collection - see the fiddle below.
    {
      id: 'elytron',
      rank: 'outline',
      fill: 'pigment',
      d: 'M0 372 C0 347.66 70.64 372.36 106 375 C141.64 377.66 189.87 369.83 213 388 C234.23 404.68 236.55 441.02 245 473 C255.29 511.93 262.01 561.53 266 606 C269.97 650.2 273.14 697.31 269 739 C265.24 776.85 258.77 814.07 245 846 C232.08 875.96 214.57 904.15 191 926 C166.18 949.01 130.4 966.64 98 979 C66.65 990.96 0 1018.87 0 1000 C0 952.77 0 431.24 0 372 Z',
    },
    // The fiddle. This is the identification and the reason the animal has the
    // name it has: a dark field either side of the suture, broad at the
    // shoulder, waisted at about two thirds of the way down and closing again
    // at the apex - the outline of a violin, laid across both wing cases at
    // once.
    //
    // Drawn as ink on a pale ground rather than as a pale mark on a dark one,
    // because that is the way round the animal is built: a fiddler beetle is a
    // yellow-green beetle with a black pattern, not a black beetle with yellow
    // on it. Getting that backwards would have produced a plate that keys to
    // the same six characters and looks like a different insect.
    {
      id: 'marking',
      rank: 'detail',
      fill: 'pigment-deep',
      d: 'M0 383 C0 366.65 57.93 378.96 77 394 C99.54 411.78 116 460.74 117 495 C118.01 529.73 84.24 567.34 82 601 C80.03 630.63 91.38 657.81 98 686 C104.69 714.48 122.23 741.07 122 771 C121.74 804.65 104.61 845.93 90 878 C76.63 907.34 58.09 939.99 40 957 C27.36 968.89 0 985.17 0 979 C0 956.69 0 428.27 0 383 Z',
      clipTo: 'elytron',
    },
    // The rust band that separates the black field from the pale margin.
    //
    // A plate has two strengths of one pigment and this animal wants three
    // colours, so the third is drawn as a *boundary* rather than as a fill -
    // which is what an engraver working in one ink did with it too. The line
    // is what carries the fiddle's outer edge at small sizes; at eighty pixels
    // the fill has gone grey and this is all that is left of the pattern.
    {
      id: 'marking',
      rank: 'structure',
      fill: 'none',
      d: 'M114 399 C114 399 155.06 461.45 157 495 C159.04 530.29 124.08 571.22 122 606 C120.21 635.98 131.41 662.73 138 691 C144.7 719.73 162.38 746.57 162 777 C161.56 811.7 144.92 855.36 128 888 C112.2 918.47 66 968 66 968',
      clipTo: 'elytron',
    },
    // The reticulation. Donovan draws the pale part of each wing case as a
    // close net of engraved cells, several hundred of them; five strokes along
    // the margin is what survives of that at plate size.
    {
      id: 'hatching',
      rank: 'detail',
      fill: 'none',
      d: 'M199 473 C199 473 221.61 600.23 221 660 C220.44 715.19 199 819 199 819',
      clipTo: 'elytron',
    },
    {
      id: 'hatching',
      rank: 'detail',
      fill: 'none',
      d: 'M191.25 486.5 C191.25 486.5 214.26 611.47 213 670.5 C211.83 725.58 187.25 829.75 187.25 829.75',
      clipTo: 'elytron',
    },
    {
      id: 'hatching',
      rank: 'detail',
      fill: 'none',
      d: 'M183.5 500 C183.5 500 206.89 622.71 205 681 C203.22 735.99 175.5 840.5 175.5 840.5',
      clipTo: 'elytron',
    },
    {
      id: 'hatching',
      rank: 'detail',
      fill: 'none',
      d: 'M175.75 513.5 C175.75 513.5 199.49 633.97 197 691.5 C194.63 746.39 163.75 851.25 163.75 851.25',
      clipTo: 'elytron',
    },
    {
      id: 'hatching',
      rank: 'detail',
      fill: 'none',
      d: 'M168 527 C168 527 192.06 645.23 189 702 C186.04 756.79 152 862 152 862',
      clipTo: 'elytron',
    },
    // The costae - the low longitudinal ribs a cetoniine's wing case carries,
    // running the length of the pale field outside the fiddle. Four, and only
    // on the pale side: on the dark field they would be invisible on the animal
    // and noise on the plate.
    //
    // The dark field carried three of its own for one pass and lost the waist
    // under them. What identifies this animal is the *shape* of that field, so
    // it is left flat and every stroke on this wing case sits outside it.
    {
      id: 'stria',
      rank: 'structure',
      fill: 'none',
      d: 'M146 447 C146 447 166.75 555.66 168 612 C169.31 670.87 152 793 152 793',
      clipTo: 'elytron',
    },
    {
      id: 'stria',
      rank: 'structure',
      fill: 'none',
      d: 'M166 451 C166 451 187.14 559.6 187.75 616 C188.39 675.2 167.75 798.25 167.75 798.25',
      clipTo: 'elytron',
    },
    {
      id: 'stria',
      rank: 'structure',
      fill: 'none',
      d: 'M186 455 C186 455 207.51 563.54 207.5 620 C207.49 679.54 183.5 803.5 183.5 803.5',
      clipTo: 'elytron',
    },
    {
      id: 'stria',
      rank: 'structure',
      fill: 'none',
      d: 'M206 459 C206 459 227.88 567.49 227.25 624 C226.58 683.89 199.25 808.75 199.25 808.75',
      clipTo: 'elytron',
    },
    {
      id: 'stria',
      rank: 'structure',
      fill: 'none',
      d: 'M226 463 C226 463 248.24 571.45 247 628 C245.68 688.24 215 814 215 814',
      clipTo: 'elytron',
    },
    // The suture, drawn once on the axis. Reflecting it would lay a second copy
    // a hair off the first and show as a doubled line.
    {
      id: 'seam',
      rank: 'structure',
      fill: 'none',
      d: 'M0 399 C0 399 0 568.64 0 660 C0 761 0 979 0 979',
      mirror: false,
    },
    {
      id: 'scutellum',
      rank: 'structure',
      fill: 'pigment-deep',
      d: 'M0 362 C27.33 362 74.09 374.97 82 394 C90.12 413.53 60.3 455.74 45 479 C32.11 498.6 15 527 0 527 C-15 527 -32.11 498.6 -45 479 C-60.3 455.74 -90.12 413.53 -82 394 C-74.09 374.97 -27.33 362 0 362 Z',
      mirror: false,
    },
    // The pronotum, and the one part of this plate filled with the deep pigment
    // rather than the pale: it is black on the animal, and it is black in every
    // figure of it. The yellow margins are laid over it below.
    {
      id: 'pronotum',
      rank: 'outline',
      fill: 'pigment-deep',
      d: 'M0 106 C31 106 67.71 106.93 93 122 C118.44 137.15 135.28 169.82 152 197 C169.06 224.73 182.21 257.56 194 287 C204.87 314.14 231.19 351.24 221 367 C209.24 385.2 146.11 375.33 109 378 C72.45 380.63 36.33 383 0 383 C-36.33 383 -72.45 380.63 -109 378 C-146.11 375.33 -209.24 385.2 -221 367 C-231.19 351.24 -204.87 314.14 -194 287 C-182.21 257.56 -169.06 224.73 -152 197 C-135.28 169.82 -118.44 137.15 -93 122 C-67.71 106.93 -31 106 0 106 Z',
      mirror: false,
    },
    // The yellow along each side of the pronotum - two lines, in Donovan's own
    // words, and the character his specific description opens with, before he
    // gets to the wing cases at all.
    //
    // Filled `pigment` and not `surface`, which is the more truthful of the two
    // and reads better as well. The yellow along this shield is the *same*
    // yellow as the wing cases, so it wants the same fill they have; bare paper
    // made two hard white patches on a black ground that read as a second pair
    // of eyes.
    //
    // A `strip` rather than a closed curve. Drawn as an outer chain of points
    // and an inner one, the smoothing bows each corner outward and the band
    // came out half the width of the shield - two white eyes rather than two
    // margins. A strip offsets along the measured edge's own normal, which is
    // what a band following a margin actually is.
    {
      id: 'marking',
      rank: 'detail',
      fill: 'pigment',
      d: 'M88 128 C105.37 130.11 129.36 175.05 146 202 C163.22 229.89 177.34 264.47 189 293 C198.94 317.31 219.38 348.82 213 362 C208.28 371.76 185.51 379.6 175.22 375.14 C161.53 369.21 156.91 333.35 146.42 310.41 C134.4 284.12 122.05 252.71 106.86 226.17 C92 200.2 53.87 169.85 56.52 152.68 C58.29 141.16 76.67 126.63 88 128 Z',
      clipTo: 'pronotum',
    },
    {
      id: 'hatching',
      rank: 'detail',
      fill: 'none',
      d: 'M24 181 C24 181 29 287 29 287',
      clipTo: 'pronotum',
    },
    {
      id: 'hatching',
      rank: 'detail',
      fill: 'none',
      d: 'M56 194 C56 194 71.5 298 71.5 298',
      clipTo: 'pronotum',
    },
    {
      id: 'hatching',
      rank: 'detail',
      fill: 'none',
      d: 'M88 207 C88 207 114 309 114 309',
      clipTo: 'pronotum',
    },
    // The head. Narrow and squared off in front, where the Christmas beetle's
    // is a broad shovel - the difference between a scarab that digs and one
    // that feeds at flowers, and visible in dorsal view without a lens.
    //
    // Donovan draws it cocked about ten pixels to the animal's right, as he
    // does the Christmas beetle's. Drawn square here for the same reason.
    {
      id: 'head',
      rank: 'outline',
      fill: 'pigment-deep',
      d: 'M0 0 C18.67 0 43.17 0.33 56 11 C68.83 21.67 75.67 46.57 77 64 C78.23 80.2 76.48 100.62 66 112 C53.58 125.5 22 133 0 133 C-22 133 -53.58 125.5 -66 112 C-76.48 100.62 -78.23 80.2 -77 64 C-75.67 46.57 -68.83 21.67 -56 11 C-43.17 0.33 -18.67 0 0 0 Z',
      mirror: false,
    },
    {
      id: 'eye',
      rank: 'detail',
      fill: 'ink',
      d: 'M72.69 67.26 C75.38 73.91 70.09 82.33 60.87 86.05 C51.65 89.78 42 87.4 39.31 80.74 C36.62 74.09 41.91 65.67 51.13 61.95 C60.35 58.22 70 60.6 72.69 67.26 Z',
    },
    // A lamellate club, as on every scarab. Drawn as one filled club with two
    // lines across it rather than as three separate plates, which at plate size
    // would be three smudges.
    {
      id: 'antenna',
      rank: 'structure',
      fill: 'none',
      d: 'M61 48 C61 48 93.35 33.33 109 27 C123.64 21.08 152 11 152 11',
    },
    {
      id: 'antenna',
      rank: 'detail',
      fill: 'pigment-deep',
      d: 'M163.04 14.2 C172.22 12.57 186.17 1.28 196.07 -6.3 C205.34 -13.41 217.31 -22.25 220.97 -29.61 C223.27 -34.23 224.38 -40.51 222.39 -42.97 C220.4 -45.43 214 -45.65 209.03 -44.39 C201.26 -42.41 191.26 -32.15 181.93 -25.7 C171.95 -18.79 156 -11.81 150.96 -4.2 C147.73 0.7 145.79 7.97 147.8 11.04 C149.82 14.1 157.23 15.23 163.04 14.2 Z',
    },
    {
      id: 'antenna',
      rank: 'detail',
      fill: 'none',
      d: 'M170 -21 C170 -21 181 0 181 0',
    },
    {
      id: 'antenna',
      rank: 'detail',
      fill: 'none',
      d: 'M197 -37 C197 -37 207 -16 207 -16',
    },
  ],
};
