// Generated from ../landmarks/formica-rufa.json by `npm run plate:build`.
//
// Do not edit this file. Edit the landmarks and build again; `npm run
// plate:verify` fails the check if the two drift apart.

import type { SpeciesPlate } from '@/lib/plate';

/**
 * *Formica rufa*, dorsal — the red wood ant, worker.
 *
 * Traced from figure 5 of plate 2 of John Lubbock's *Ants, Bees, and Wasps*,
 * where the plate's own caption names it and the other four figures are *Atta*
 * and *Pheidole*. `references/formica-rufa.jpg` is the plate; the wood ant is
 * the large figure at the bottom, drawn square to the page with all six legs
 * and both antennae clear of the body.
 *
 * ## The first plate with no wings
 *
 * Which is why `REQUIRED_PARTS.hymenoptera` no longer asks for any. A worker
 * ant has none — not folded, not reduced, none — and neither do the females of
 * a good many other families in the order, so the list was asking for a part
 * that is optional rather than for one whose absence is a mistake. The
 * bumblebee's and the hornet's own tests assert their four wings, which is
 * where a fact about one species belongs.
 *
 * `morphology.wingCover` says `absent`, and this is the only record in the
 * collection that does. It is worth a plate on its own account for that: the
 * key's first question is what covers the back, and until this animal arrived
 * one of its six answers led nowhere.
 *
 * ## What the drawing has to get right
 *
 * The **waist**. An ant is three parts with two constrictions, and the
 * constrictions are the order: head, alitrunk, gaster, with the petiole
 * between the last two. Drawn as a *gap* — the alitrunk ends at y = 568 and
 * the gaster starts at 582 — on the same reasoning the bumblebee's plate uses,
 * which is that a waist is the absence of an animal rather than a part of one.
 *
 * Then the **antennae**, which are elbowed. A long scape from the head, a bend,
 * and the funiculus carrying on at an angle: `geniculate` is the character
 * state and `ANTENNA_FORMS` has no such word, so the record says `filiform`,
 * which is the closest true thing — the joints past the elbow are a chain of
 * equal segments. The drawing says the rest.
 *
 * Then the **head**, which is nearly square with a slightly notched back
 * margin, and as wide as the gaster. A worker's head carries the mandibles and
 * the muscle to close them, and the notch at the occiput is where a
 * *Formica*'s neck sits.
 *
 * ## Plate space
 *
 * y = 0 at the front of the head, y = 1000 at the tip of the gaster. Head 0 to
 * 238, alitrunk 248 to 568, gaster 578 to 1004. The antennae reach x = 444 and
 * above y = -84; the hind tarsi reach y = 1090.
 */
export const FORMICA_RUFA_PLATE: SpeciesPlate = {
  species: 'formica-rufa',
  order: 'hymenoptera',
  sex: 'female',
  hallmark:
    'no wings at all, and the waist between the alitrunk and the gaster that is left as a gap',
  reference: {
    title: 'Ants, Bees, and Wasps, plate 2 figure 5',
    artist: 'John Lubbock',
    year: 1897,
    source:
      'https://commons.wikimedia.org/wiki/File:Ants,_bees,_and_wasps_(Plate_2)_(8476376962).jpg',
    licence: 'Public domain (PD-old-70-expired)',
  },
  parts: [
    // The legs first, so they pass under the body.
    //
    // Long and fine — a wood ant walks fifty metres from its nest and back — and
    // much finer than any beetle's here: the femur is 26 units against the
    // violet ground beetle's 34 on an animal a third of the length. The spines
    // Lubbock draws on each tibia are left out; at eighty pixels they are a
    // furred outline.
    {
      id: 'hindleg-femur',
      rank: 'structure',
      fill: 'pigment-deep',
      d: 'M42.4 558.55 C53.6 576.4 110.62 605.53 143.11 629.21 C174.36 651.98 216.17 693.15 233.86 697.89 C240.1 699.56 245.85 698.77 247.89 696.14 C249.94 693.51 249.3 687.74 246.14 682.11 C237.17 666.09 187.67 634.44 156.89 610.79 C124.9 586.21 78.12 542.42 57.6 537.45 C49.67 535.53 41.98 536.89 39.45 540.4 C36.92 543.92 38.08 551.65 42.4 558.55 Z',
    },
    {
      id: 'hindleg-tibia',
      rank: 'structure',
      fill: 'pigment-deep',
      d: 'M232.9 695.54 C237.97 713.58 286.72 761.24 311.53 794.71 C335.76 827.39 366.32 884.9 380.21 893.94 C384.19 896.53 388.01 897.1 389.94 895.79 C391.87 894.48 392.73 890.72 391.79 886.06 C388.48 869.78 348.26 818.5 324.47 785.29 C300.1 751.28 263.4 693.79 247.1 684.46 C241.94 681.51 236.83 681.06 234.46 682.9 C232.1 684.75 231.3 689.81 232.9 695.54 Z',
    },
    {
      id: 'hindleg-tarsus',
      rank: 'detail',
      fill: 'pigment-deep',
      d: 'M380.34 893.2 C381.81 904.44 406.72 946.18 415.21 952.71 C418.07 954.9 421.12 955.69 422.71 954.79 C424.31 953.88 425.2 950.86 424.79 947.29 C423.55 936.65 400.53 893.83 391.66 886.8 C388.41 884.23 384.68 883.28 382.8 884.34 C380.91 885.41 379.81 889.1 380.34 893.2 Z',
    },
    {
      id: 'hindleg-tarsus',
      rank: 'detail',
      fill: 'pigment-deep',
      d: 'M417.08 958.46 C417.9 968.89 440.55 1011.67 447.98 1018.01 C450.26 1019.96 452.67 1020.7 454.01 1020.02 C455.35 1019.35 456.22 1016.99 456.02 1013.99 C455.41 1004.25 434.77 960.45 426.92 953.54 C424.25 951.19 421.18 950.26 419.54 951.08 C417.9 951.9 416.8 954.91 417.08 958.46 Z',
    },
    {
      id: 'hindleg-tarsus',
      rank: 'detail',
      fill: 'ink',
      d: 'M449.84 1023.71 C449.99 1033.94 474.78 1085.55 480.15 1090.76 C481.2 1091.78 482.15 1092.1 482.76 1091.85 C483.38 1091.6 483.82 1090.7 483.85 1089.24 C483.99 1081.76 465.25 1027.65 458.16 1020.29 C456.08 1018.12 453.67 1017.27 452.29 1017.84 C450.9 1018.41 449.79 1020.71 449.84 1023.71 Z',
    },
    {
      id: 'midleg-femur',
      rank: 'structure',
      fill: 'pigment-deep',
      d: 'M41.33 442.13 C55.74 455.64 111.88 467.52 145.68 480.66 C178.05 493.24 222.99 519.16 240.08 519.2 C246.45 519.22 251.9 516.98 253.2 513.92 C254.51 510.85 252.34 505.38 247.92 500.8 C236.01 488.48 186.44 472.88 154.32 459.34 C120.77 445.21 70.46 417.49 50.67 417.87 C42.64 418.02 35.42 421.29 33.87 425.33 C32.31 429.38 35.48 436.64 41.33 442.13 Z',
    },
    {
      id: 'midleg-tibia',
      rank: 'structure',
      fill: 'pigment-deep',
      d: 'M239.48 517.78 C249.29 530.52 298.12 550.07 325.79 566.8 C352.25 582.8 388.48 613.31 402.15 615.85 C406.67 616.69 410.57 615.8 411.85 613.85 C413.13 611.9 412.41 607.97 409.85 604.15 C402.08 592.56 360.45 569.82 334.21 553.2 C306.77 535.81 264.5 504.45 248.52 502.22 C242.82 501.42 237.73 502.88 236.22 505.48 C234.71 508.07 235.96 513.22 239.48 517.78 Z',
    },
    {
      id: 'midleg-tarsus',
      rank: 'detail',
      fill: 'pigment-deep',
      d: 'M401.97 615.1 C406.45 622.92 432.32 642.07 440.59 644.32 C443.91 645.22 447.18 644.85 448.32 643.41 C449.45 641.97 449.05 638.7 447.41 635.68 C443.3 628.16 418.67 607.44 410.03 604.9 C406.26 603.79 402.24 604.27 400.9 605.97 C399.56 607.67 400.02 611.69 401.97 615.1 Z',
    },
    {
      id: 'midleg-tarsus',
      rank: 'detail',
      fill: 'pigment-deep',
      d: 'M443.42 648.18 C447.22 655.48 471.7 675.1 479.07 677.42 C481.81 678.28 484.44 678.07 485.42 676.93 C486.39 675.79 486.2 673.16 484.93 670.58 C481.51 663.66 458.37 642.47 450.58 639.82 C447.38 638.74 444.02 639.03 442.82 640.42 C441.63 641.81 441.86 645.18 443.42 648.18 Z',
    },
    {
      id: 'midleg-tarsus',
      rank: 'detail',
      fill: 'ink',
      d: 'M482.07 681.42 C485.7 688.11 513.23 707.89 518.7 709.52 C520.05 709.92 521.08 709.81 521.52 709.3 C521.95 708.8 521.91 707.76 521.3 706.48 C518.86 701.33 495.09 677.14 487.93 674.58 C485.27 673.63 482.56 673.93 481.58 675.07 C480.61 676.21 480.73 678.93 482.07 681.42 Z',
    },
    {
      id: 'foreleg-femur',
      rank: 'structure',
      fill: 'pigment-deep',
      d: 'M56.23 311.41 C77.42 309.02 130.99 269.7 165.55 250.07 C196.87 232.29 244.26 212.29 254.86 198.74 C258.78 193.72 260.36 188.06 258.74 185.14 C257.12 182.23 251.48 180.58 245.14 181.26 C228.05 183.1 186.21 212.99 154.45 229.93 C119.42 248.61 57.26 272.08 43.77 288.59 C38.61 294.91 36.51 302.42 38.59 306.23 C40.66 310.03 48.11 312.33 56.23 311.41 Z',
    },
    {
      id: 'foreleg-tibia',
      rank: 'structure',
      fill: 'pigment-deep',
      d: 'M256.46 196.27 C271.07 189.88 303.25 149.08 323.97 125.32 C343.35 103.12 373.62 71.3 377.42 58.43 C378.71 54.06 378.24 50.06 376.43 48.58 C374.63 47.1 370.61 47.44 366.58 49.57 C354.78 55.81 331.74 93.06 312.03 114.68 C290.94 137.8 249.48 169 243.54 183.73 C241.4 189.06 241.58 194.37 243.73 196.46 C245.88 198.55 251.19 198.58 256.46 196.27 Z',
    },
    {
      id: 'foreleg-tarsus',
      rank: 'detail',
      fill: 'pigment-deep',
      d: 'M377.48 57.49 C385.18 51.99 403.17 21.82 404.64 12.95 C405.21 9.53 404.5 6.34 402.95 5.36 C401.41 4.38 398.22 5.08 395.36 7.05 C387.95 12.13 368.24 41.21 366.52 50.51 C365.79 54.42 366.68 58.32 368.51 59.48 C370.34 60.65 374.25 59.8 377.48 57.49 Z',
    },
    {
      id: 'foreleg-tarsus',
      rank: 'detail',
      fill: 'pigment-deep',
      d: 'M406.83 6.63 C413.54 1.11 429.16 -29.74 429.95 -37.85 C430.23 -40.73 429.47 -43.23 428.15 -43.95 C426.84 -44.67 424.33 -43.95 422.05 -42.15 C415.66 -37.11 398.18 -7.26 397.17 1.37 C396.77 4.77 397.76 7.95 399.37 8.83 C400.98 9.71 404.19 8.81 406.83 6.63 Z',
    },
    {
      id: 'foreleg-tarsus',
      rank: 'detail',
      fill: 'ink',
      d: 'M432.06 -44.06 C437.96 -49.63 451.63 -85.09 451.8 -91.14 C451.85 -92.56 451.46 -93.52 450.86 -93.8 C450.26 -94.09 449.28 -93.79 448.2 -92.86 C443.6 -88.93 424.57 -56.04 423.94 -47.94 C423.72 -45.08 424.71 -42.59 426.06 -41.94 C427.41 -41.29 429.97 -42.09 432.06 -44.06 Z',
    },
    // The gaster — the ant's abdomen behind the waist. Broad, smooth and
    // shining, and where a wood ant carries the formic acid it sprays.
    {
      id: 'abdomen',
      rank: 'outline',
      fill: 'pigment',
      d: 'M0 578 C28.67 578 60.65 574.56 86 584 C110.42 593.09 134.74 610.83 150 632 C166.05 654.27 172.66 687.13 178 716 C183.39 745.12 183.69 776.25 182 806 C180.32 835.58 177.56 867.37 168 894 C159 919.06 145.5 944.78 128 962 C111.64 978.1 89.38 989 68 996 C46.7 1002.97 22.67 1004 0 1004 C-22.67 1004 -46.7 1002.97 -68 996 C-89.38 989 -111.64 978.1 -128 962 C-145.5 944.78 -159 919.06 -168 894 C-177.56 867.37 -180.32 835.58 -182 806 C-183.69 776.25 -183.39 745.12 -178 716 C-172.66 687.13 -166.05 654.27 -150 632 C-134.74 610.83 -110.42 593.09 -86 584 C-60.65 574.56 -28.67 578 0 578 Z',
      mirror: false,
    },
    // The tergite lines across the gaster: three strokes, each crossing the
    // axis. Both guides are centred on x = 0, which is the case the fan
    // validator allows on the midline.
    {
      id: 'abdomen-segment',
      rank: 'structure',
      fill: 'none',
      d: 'M-160 700 C-160 700 -53.33 690 0 690 C53.33 690 160 700 160 700',
      mirror: false,
      clipTo: 'abdomen',
    },
    {
      id: 'abdomen-segment',
      rank: 'structure',
      fill: 'none',
      d: 'M-140 815 C-140 815 -46.67 803 0 803 C46.67 803 140 815 140 815',
      mirror: false,
      clipTo: 'abdomen',
    },
    {
      id: 'abdomen-segment',
      rank: 'structure',
      fill: 'none',
      d: 'M-120 930 C-120 930 -40 916 0 916 C40 916 120 930 120 930',
      mirror: false,
      clipTo: 'abdomen',
    },
    // The pubescence on the gaster, as five strokes. A wood ant is not furred
    // the way a bumblebee is, but it is not bare either, and hatching is what
    // an engraving has for the difference.
    {
      id: 'hatching',
      rank: 'detail',
      fill: 'none',
      d: 'M60 640 C60 640 40 740 40 740',
      clipTo: 'abdomen',
    },
    {
      id: 'hatching',
      rank: 'detail',
      fill: 'none',
      d: 'M82 670.5 C82 670.5 59.5 773 59.5 773',
      clipTo: 'abdomen',
    },
    {
      id: 'hatching',
      rank: 'detail',
      fill: 'none',
      d: 'M104 701 C104 701 79 806 79 806',
      clipTo: 'abdomen',
    },
    {
      id: 'hatching',
      rank: 'detail',
      fill: 'none',
      d: 'M126 731.5 C126 731.5 98.5 839 98.5 839',
      clipTo: 'abdomen',
    },
    {
      id: 'hatching',
      rank: 'detail',
      fill: 'none',
      d: 'M148 762 C148 762 118 872 118 872',
      clipTo: 'abdomen',
    },
    // The alitrunk: the middle section, which in a wingless worker is the
    // thorax with nothing on it. Its profile from above steps in twice — the
    // pronotum, then the mesonotum, then the propodeum — and those steps are
    // the only structure this part of the animal has.
    //
    // It stops at y = 568 and the gaster starts at 578. The ten units between
    // them are the petiole, and they are drawn as nothing at all: a waist is
    // the absence of an animal rather than a part of one, and the bumblebee's
    // plate makes the same call for the same reason.
    {
      id: 'thorax',
      rank: 'outline',
      fill: 'pigment-deep',
      d: 'M0 248 C14.67 248 33.64 244.77 44 252 C54.1 259.05 58.28 276.09 62 290 C66.06 305.19 66.61 323.21 66 340 C65.37 357.2 61.86 375.53 58 392 C54.38 407.43 45.14 420.72 44 436 C42.8 452 52.24 470.08 52 486 C51.78 500.63 48.95 515.36 44 528 C39.35 539.87 32.37 553.41 24 560 C17.14 565.4 8 568 0 568 C-8 568 -17.14 565.4 -24 560 C-32.37 553.41 -39.35 539.87 -44 528 C-48.95 515.36 -51.78 500.63 -52 486 C-52.24 470.08 -42.8 452 -44 436 C-45.14 420.72 -54.38 407.43 -58 392 C-61.86 375.53 -65.37 357.2 -66 340 C-66.61 323.21 -66.06 305.19 -62 290 C-58.28 276.09 -54.1 259.05 -44 252 C-33.64 244.77 -14.67 248 0 248 Z',
      mirror: false,
    },
    {
      id: 'hatching',
      rank: 'detail',
      fill: 'none',
      d: 'M12 300 C12 300 14 420 14 420',
      clipTo: 'thorax',
    },
    {
      id: 'hatching',
      rank: 'detail',
      fill: 'none',
      d: 'M27 300 C27 300 26 420 26 420',
      clipTo: 'thorax',
    },
    {
      id: 'hatching',
      rank: 'detail',
      fill: 'none',
      d: 'M42 300 C42 300 38 420 38 420',
      clipTo: 'thorax',
    },
    // The head: nearly square, as wide as the gaster, with the back margin
    // slightly notched where the neck sits. A worker's head is mostly the
    // muscle that closes its mandibles.
    {
      id: 'head',
      rank: 'outline',
      fill: 'pigment-deep',
      d: 'M0 -8 C17.33 -8 37.13 -8.65 52 -2 C66.27 4.38 79.69 16.04 88 30 C97.39 45.79 99.94 69.39 102 90 C104.13 111.34 102.55 135.01 100 156 C97.63 175.55 97.74 198.17 88 212 C78.95 224.84 60.9 235.12 46 238 C31.52 240.8 15.33 230 0 230 C-15.33 230 -31.52 240.8 -46 238 C-60.9 235.12 -78.95 224.84 -88 212 C-97.74 198.17 -97.63 175.55 -100 156 C-102.55 135.01 -104.13 111.34 -102 90 C-99.94 69.39 -97.39 45.79 -88 30 C-79.69 16.04 -66.27 4.38 -52 -2 C-37.13 -8.65 -17.33 -8 0 -8 Z',
      mirror: false,
    },
    // A mandible: triangular and toothed on the animal, drawn open here.
    // Crossed in front of the head as an ant usually carries them, two of them
    // at plate size are one blot.
    {
      id: 'mandible',
      rank: 'structure',
      fill: 'pigment-deep',
      d: 'M45.21 10.59 C53.08 3.92 63.6 -16.92 62.97 -29.32 C62.4 -40.68 49.17 -57.2 44.79 -61.11 C43.29 -62.45 41.81 -63.16 40.89 -62.79 C39.96 -62.41 39.41 -60.83 39.21 -58.89 C38.7 -53.83 47.15 -39.61 45.03 -30.68 C42.66 -20.72 24.64 -11.32 22.79 -2.59 C21.48 3.66 23.67 13.01 27.41 15.21 C31.14 17.4 40.1 14.92 45.21 10.59 Z',
    },
    {
      id: 'eye',
      rank: 'detail',
      fill: 'ink',
      d: 'M96 98 C96 110.15 88.84 120 80 120 C71.16 120 64 110.15 64 98 C64 85.85 71.16 76 80 76 C88.84 76 96 85.85 96 98 Z',
    },
    // The three ocelli on the vertex, in a small triangle between the compound
    // eyes: one on the midline, drawn once, and a pair either side of it. A
    // wood ant worker has them and most smaller ants do not, so they are worth
    // the three parts.
    {
      id: 'ocellus',
      rank: 'detail',
      fill: 'ink',
      d: 'M9 170 C9 174.42 4.97 178 0 178 C-4.97 178 -9 174.42 -9 170 C-9 165.58 -4.97 162 0 162 C4.97 162 9 165.58 9 170 Z',
      mirror: false,
    },
    {
      id: 'ocellus',
      rank: 'detail',
      fill: 'ink',
      d: 'M39 196 C39 200.42 34.97 204 30 204 C25.03 204 21 200.42 21 196 C21 191.58 25.03 188 30 188 C34.97 188 39 191.58 39 196 Z',
    },
    // The sculpture on the head, as three strokes. A Formica's head is finely
    // striate rather than smooth, which is the difference between it and the
    // polished gaster below.
    {
      id: 'hatching',
      rank: 'detail',
      fill: 'none',
      d: 'M22 60 C22 60 24 200 24 200',
      clipTo: 'head',
    },
    {
      id: 'hatching',
      rank: 'detail',
      fill: 'none',
      d: 'M42 63 C42 63 45 198 45 198',
      clipTo: 'head',
    },
    {
      id: 'hatching',
      rank: 'detail',
      fill: 'none',
      d: 'M62 66 C62 66 66 196 66 196',
      clipTo: 'head',
    },
    // The antenna, elbowed. One long scape out of the head, a bend, and four
    // funicular joints carrying on at an angle — which is what an ant's antenna
    // does and what no other antenna in this collection does.
    //
    // `ANTENNA_FORMS` has no `geniculate`, so the record answers `filiform`:
    // true of the joints past the elbow, and the closest of six wrong answers
    // to the whole. The bend is drawn rather than recorded.
    {
      id: 'antenna',
      rank: 'structure',
      fill: 'pigment-deep',
      d: 'M52.38 68.96 C72.14 64.3 121.59 18.87 155.58 -6.31 C189.14 -31.17 245.74 -65.52 255.06 -81.17 C257.95 -86.03 258.52 -90.78 256.83 -93.06 C255.15 -95.33 250.44 -96.18 244.94 -94.83 C227.27 -90.5 178.41 -45.85 144.42 -21.69 C109.99 2.78 50.49 33.91 39.62 51.04 C35.83 57.02 34.91 63.39 37.04 66.38 C39.16 69.36 45.48 70.59 52.38 68.96 Z',
    },
    {
      id: 'antenna',
      rank: 'structure',
      fill: 'pigment-deep',
      d: 'M252.73 -78.15 C260.11 -70.88 291.11 -59 301.12 -59.08 C305.63 -59.11 309.96 -60.81 310.92 -63.12 C311.88 -65.42 310.04 -69.69 306.88 -72.92 C299.89 -80.08 269.63 -93.72 259.27 -93.85 C254.29 -93.9 249.24 -91.88 248.15 -89.27 C247.06 -86.65 249.18 -81.65 252.73 -78.15 Z',
    },
    {
      id: 'antenna',
      rank: 'detail',
      fill: 'pigment-deep',
      d: 'M305.01 -55.12 C311.81 -48.22 342.11 -36.11 351.41 -36.04 C355.39 -36.01 359.1 -37.42 359.96 -39.41 C360.82 -41.4 359.33 -45.07 356.59 -47.96 C350.2 -54.71 320.68 -68.61 310.99 -68.88 C306.54 -69 302.12 -67.28 301.12 -64.99 C300.13 -62.7 301.88 -58.3 305.01 -55.12 Z',
    },
    {
      id: 'antenna',
      rank: 'detail',
      fill: 'pigment-deep',
      d: 'M355.31 -32.08 C361.52 -25.57 391.17 -13.19 399.72 -12.99 C403.16 -12.91 406.25 -14.06 407.01 -15.72 C407.77 -17.39 406.59 -20.47 404.28 -23.01 C398.5 -29.32 369.68 -43.52 360.69 -43.92 C356.77 -44.09 352.98 -42.66 352.08 -40.69 C351.19 -38.72 352.6 -34.92 355.31 -32.08 Z',
    },
    {
      id: 'antenna',
      rank: 'detail',
      fill: 'pigment-deep',
      d: 'M403.65 -9.03 C408.94 -3.39 435.29 7.39 442.29 7.61 C444.85 7.7 447.04 6.92 447.61 5.71 C448.19 4.51 447.4 2.32 445.71 0.39 C441.11 -4.89 416.07 -18.45 408.35 -18.97 C405.04 -19.19 401.81 -18.01 401.03 -16.35 C400.24 -14.7 401.37 -11.45 403.65 -9.03 Z',
    },
    {
      id: 'antenna',
      rank: 'detail',
      fill: 'pigment-deep',
      d: 'M446.21 11.58 C450.7 16.56 477.18 27.94 482.88 28.24 C484.57 28.32 485.86 27.86 486.24 27.12 C486.61 26.37 486.2 25.06 485.12 23.76 C481.46 19.38 456.47 5.02 449.79 4.42 C447.28 4.2 445.02 5.02 444.42 6.21 C443.83 7.4 444.53 9.71 446.21 11.58 Z',
    },
  ],
};
