// Generated from ../landmarks/graphosoma-italicum.json by `npm run plate:build`.
//
// Do not edit this file. Edit the landmarks and build again; `npm run
// plate:verify` fails the check if the two drift apart.

import type { SpeciesPlate } from '@/lib/plate';

/**
 * *Graphosoma italicum*, dorsal — the Italian striped shield bug.
 *
 * Traced from figure 3 of plate I of Brunner von Wattenwyl's *Betrachtungen
 * über die Farbenpracht der Insekten* (1897), where it is captioned under the
 * name *Graphosoma lineatum* — the two have since been separated, and the
 * animal figured, with the whole pronotum striped rather than spotted at the
 * front, is *italicum*. `references/graphosoma-italicum.jpg` is the sheet and
 * the bug is figure 3, low and left of centre.
 *
 * It is a *small* figure on a large plate — Brunner's sheet is about colour in
 * insects generally, so it carries a locust, four scarabs and three
 * butterflies as well, and this bug gets fifty pixels. The same thing was true
 * of the seven-spot and the answer is the same: what a shield bug needs from a
 * reference is the outline, the scutellum and where the stripes run, and all
 * three survive at that size. The proportions were then checked against the
 * published measurements — 8 to 12 mm long and about 0.72 as wide as long.
 *
 * ## What the drawing has to get right
 *
 * The **stripes**, which are what `markings: 'stripes'` means on this record
 * and the reason this animal is in the collection at all: six black lines
 * running head to tail, straight across the pronotum and converging down the
 * scutellum. Drawn as capsules clipped to the surface they are on, three a
 * side, mirrored — because a plate that placed them separately on each side
 * would be drawing one specimen's asymmetry rather than the species.
 *
 * Then the **scutellum**. On a green shield bug it is a triangle between the
 * wings; on this one it reaches almost to the tip of the abdomen and the
 * hemelytra are reduced to a narrow strip either side of it. That is the
 * character that separates the two at a glance and it is why the corium here is
 * authored as a long thin shape rather than as half a wing.
 *
 * Then the **connexivum** — the rim of the abdomen showing outside the wings,
 * banded black and red. Six short strokes marching down it, clipped to the
 * abdomen.
 *
 * ## Plate space
 *
 * y = 0 at the front of the head, y = 1000 at the tip of the abdomen. The
 * pronotum is 130 to 360 and the scutellum 350 to 900. Half-width 358, which
 * is the 0.72 the measurements give.
 */
export const GRAPHOSOMA_ITALICUM_PLATE: SpeciesPlate = {
  species: 'graphosoma-italicum',
  order: 'hemiptera',
  sex: 'unsexed',
  hallmark:
    "the six black stripes running head to tail, and the scutellum that reaches almost to the abdomen's tip",
  reference: {
    title: 'Betrachtungen über die Farbenpracht der Insekten, plate I figure 3',
    artist: 'Karl Brunner von Wattenwyl',
    year: 1897,
    source:
      'https://commons.wikimedia.org/wiki/File:Betrachtungen_uber_die_Farbenpracht_der_Insekten_(Plate_I)_(9237127969).jpg',
    licence: 'Public domain (PD-old-70-expired)',
  },
  parts: [
    // The legs first, so they pass under the body. Short and unremarkable: a
    // shield bug walks on plants and does nothing else with its legs, and the
    // red-and-black banding the animal has on them is colour rather than shape.
    {
      id: 'hindleg-femur',
      rank: 'structure',
      fill: 'pigment-deep',
      d: 'M269.63 677.1 C280.35 691.31 314.51 702.54 336.46 715.26 C357.91 727.7 384.11 750.06 399.87 752.6 C408.33 753.97 417.89 752.33 420.6 748.13 C423.32 743.93 420.87 734.55 416.13 727.4 C407.28 714.02 376.26 698.67 355.54 684.74 C334.36 670.49 307.99 645.83 290.37 642.9 C279.71 641.12 266.35 643.93 262.9 649.63 C259.44 655.34 263.14 668.49 269.63 677.1 Z',
    },
    {
      id: 'hindleg-tibia',
      rank: 'structure',
      fill: 'pigment-deep',
      d: 'M394.05 738.86 C385.66 755.51 390.72 804.54 387.58 836.55 C384.53 867.69 371.53 912.55 375.62 928.42 C377.26 934.77 380.96 939.85 384.42 940.38 C387.88 940.91 392.92 937.16 396.38 931.58 C405.06 917.56 408.18 870.74 412.42 839.45 C416.77 807.29 427.56 759.04 421.95 741.14 C419.44 733.13 413.79 726.43 409.14 726.05 C404.49 725.67 397.82 731.37 394.05 738.86 Z',
    },
    {
      id: 'hindleg-tarsus',
      rank: 'detail',
      fill: 'pigment-deep',
      d: 'M377.06 928.93 C372.14 937.99 369.76 969.69 372.55 979.11 C373.83 983.43 376.62 987.15 379.11 987.45 C381.59 987.74 385.18 984.79 387.45 980.89 C392.39 972.41 397.57 941.04 394.94 931.07 C393.61 926.06 390.05 921.42 387.07 921.06 C384.09 920.71 379.54 924.37 377.06 928.93 Z',
    },
    {
      id: 'hindleg-tarsus',
      rank: 'detail',
      fill: 'pigment-deep',
      d: 'M370.53 987.35 C366.38 995.54 364.78 1025.06 367.52 1033.44 C368.75 1037.17 371.28 1040.29 373.44 1040.48 C375.6 1040.66 378.62 1038.03 380.48 1034.56 C384.63 1026.79 388.14 997.43 385.47 988.65 C384.19 984.44 381.14 980.74 378.65 980.53 C376.16 980.31 372.51 983.43 370.53 987.35 Z',
    },
    {
      id: 'hindleg-tarsus',
      rank: 'detail',
      fill: 'ink',
      d: 'M366.56 1039.11 C363.2 1045.63 363.86 1070.46 365.52 1075.66 C366.04 1077.27 366.83 1078.36 367.66 1078.48 C368.48 1078.59 369.54 1077.76 370.48 1076.34 C373.49 1071.8 380.9 1048.09 379.44 1040.89 C378.71 1037.29 376.04 1033.86 373.89 1033.56 C371.75 1033.26 368.25 1035.83 366.56 1039.11 Z',
    },
    {
      id: 'midleg-femur',
      rank: 'structure',
      fill: 'pigment-deep',
      d: 'M294.73 449.43 C312.23 451.92 344.01 436.34 368.31 429.48 C392.31 422.7 426.92 418.38 439.64 408.55 C446.43 403.3 451.76 395.21 450.55 390.36 C449.34 385.51 440.82 380.88 432.36 379.45 C416.53 376.76 384.05 389.37 359.69 394.52 C335.02 399.74 299.66 400.33 285.27 410.57 C276.5 416.8 268.99 428.25 270.57 434.73 C272.14 441.2 284.07 447.92 294.73 449.43 Z',
    },
    {
      id: 'midleg-tibia',
      rank: 'structure',
      fill: 'pigment-deep',
      d: 'M422.49 397.66 C420.23 416.3 441.95 460.74 449.81 492.77 C457.68 524.82 460.23 575.63 469.67 589.9 C473.33 595.42 478.45 598.96 481.9 598.33 C485.34 597.69 488.87 592.57 490.33 586.1 C494.1 569.3 481 519.88 474.19 487.23 C467.39 454.62 460.95 405.39 449.51 390.34 C444.42 383.64 436.84 379.27 432.34 380.49 C427.84 381.71 423.5 389.32 422.49 397.66 Z',
    },
    {
      id: 'midleg-tarsus',
      rank: 'detail',
      fill: 'pigment-deep',
      d: 'M471.11 589.42 C468.86 599.53 475.31 630.87 480.59 639.18 C483.01 642.99 486.72 645.8 489.18 645.41 C491.65 645.01 494.3 641.19 495.41 636.82 C497.83 627.26 494.18 595.48 488.89 586.58 C486.23 582.12 481.54 578.64 478.58 579.11 C475.62 579.59 472.24 584.36 471.11 589.42 Z',
    },
    {
      id: 'midleg-tarsus',
      rank: 'detail',
      fill: 'pigment-deep',
      d: 'M482.56 646.97 C480.27 655.88 485.06 685.23 489.55 692.84 C491.55 696.23 494.69 698.73 496.84 698.45 C498.99 698.17 501.38 694.95 502.45 691.16 C504.84 682.65 501.94 653.05 497.44 645.03 C495.28 641.19 491.51 638.24 489.03 638.56 C486.55 638.89 483.66 642.71 482.56 646.97 Z',
    },
    {
      id: 'midleg-tarsus',
      rank: 'detail',
      fill: 'ink',
      d: 'M490.56 698.89 C489.1 706.09 496.51 729.8 499.52 734.34 C500.46 735.76 501.52 736.59 502.34 736.48 C503.17 736.36 503.96 735.27 504.48 733.66 C506.14 728.46 506.8 703.63 503.44 697.11 C501.75 693.83 498.25 691.26 496.11 691.56 C493.96 691.86 491.29 695.29 490.56 698.89 Z',
    },
    {
      id: 'foreleg-femur',
      rank: 'structure',
      fill: 'pigment-deep',
      d: 'M191.93 242.05 C212.21 236.72 244.32 202.76 269.14 182.14 C293.51 161.89 331.13 136.31 339.6 119.52 C343.62 111.56 344.72 102.24 341.52 98.4 C338.32 94.56 328.94 93.96 320.4 96.48 C302.48 101.74 272.01 135.11 246.86 153.86 C221.26 172.95 178.93 192.19 168.07 209.95 C162.19 219.55 159.97 232.58 163.95 237.93 C167.93 243.28 181.03 244.92 191.93 242.05 Z',
    },
    {
      id: 'foreleg-tibia',
      rank: 'structure',
      fill: 'pigment-deep',
      d: 'M341.16 116.45 C355.56 107.84 375.6 72.1 390.39 48.95 C404.82 26.36 427.17 -5.93 429.05 -20.68 C429.86 -27.05 428.34 -33.28 425.32 -35.05 C422.31 -36.82 416.11 -35.12 410.95 -31.32 C399.11 -22.62 384.74 13.48 369.61 35.05 C354.11 57.14 323.18 83.54 318.84 99.55 C316.71 107.41 317.83 116.34 321.55 119.16 C325.27 121.98 334.15 120.65 341.16 116.45 Z',
    },
    {
      id: 'foreleg-tarsus',
      rank: 'detail',
      fill: 'pigment-deep',
      d: 'M428.12 -22.12 C435.75 -29.18 448.38 -58.87 448.77 -68.76 C448.94 -73.27 447.49 -77.69 445.24 -78.77 C442.98 -79.84 438.64 -78.2 435.23 -75.24 C427.77 -68.73 412.59 -40.26 411.88 -29.88 C411.53 -24.7 413.41 -19.18 416.12 -17.88 C418.82 -16.59 424.31 -18.59 428.12 -22.12 Z',
    },
    {
      id: 'foreleg-tarsus',
      rank: 'detail',
      fill: 'pigment-deep',
      d: 'M451.74 -75.71 C458.71 -82 471.38 -110.14 471.84 -119.15 C472.04 -123.1 470.8 -126.89 468.85 -127.84 C466.91 -128.79 463.15 -127.44 460.16 -124.85 C453.34 -118.95 438.94 -91.66 438.26 -82.29 C437.94 -77.88 439.46 -73.36 441.71 -72.26 C443.96 -71.16 448.46 -72.75 451.74 -75.71 Z',
    },
    {
      id: 'foreleg-tarsus',
      rank: 'detail',
      fill: 'ink',
      d: 'M473.88 -125.23 C479.16 -130.57 486.29 -155.37 486.26 -160.94 C486.25 -162.64 485.82 -163.91 485.06 -164.26 C484.31 -164.62 483.06 -164.14 481.74 -163.06 C477.43 -159.54 462.87 -138.24 462.12 -130.77 C461.75 -127.08 463.27 -123.04 465.23 -122.12 C467.19 -121.2 471.28 -122.6 473.88 -125.23 Z',
    },
    // The abdomen. Almost circular from above, and drawn once because it
    // straddles the axis. Everything after this sits on top of it.
    {
      id: 'abdomen',
      rank: 'outline',
      fill: 'pigment',
      d: 'M0 336 C100 336 247.23 315.82 300 352 C331.55 373.64 334.33 415.64 344 450 C353.82 484.91 356.09 524.14 358 560 C359.82 594.06 359.09 627.3 356 660 C352.98 691.93 347.88 723.88 340 754 C332.38 783.13 323.15 811.83 310 838 C297.05 863.78 281.19 889.23 262 910 C243.09 930.47 220.6 947.85 196 962 C170.19 976.84 141 988.62 110 996 C76.12 1004.06 36.67 1006 0 1006 C-36.67 1006 -76.12 1004.06 -110 996 C-141 988.62 -170.19 976.84 -196 962 C-220.6 947.85 -243.09 930.47 -262 910 C-281.19 889.23 -297.05 863.78 -310 838 C-323.15 811.83 -332.38 783.13 -340 754 C-347.88 723.88 -352.98 691.93 -356 660 C-359.09 627.3 -359.82 594.06 -358 560 C-356.09 524.14 -353.82 484.91 -344 450 C-334.33 415.64 -331.55 373.64 -300 352 C-247.23 315.82 -100 336 0 336 Z',
      mirror: false,
    },
    // The connexivum: the rim of the abdomen that shows outside the wings,
    // banded black and red on the animal. Six short strokes marching down it —
    // one measurement at each end and a count, rather than six pairs of points
    // that would each be a chance to put one out of step.
    {
      id: 'abdomen-segment',
      rank: 'structure',
      fill: 'none',
      d: 'M296 420 C296 420 324 426 324 426',
      clipTo: 'abdomen',
    },
    {
      id: 'abdomen-segment',
      rank: 'structure',
      fill: 'none',
      d: 'M276.4 509.6 C276.4 509.6 305.6 518 305.6 518',
      clipTo: 'abdomen',
    },
    {
      id: 'abdomen-segment',
      rank: 'structure',
      fill: 'none',
      d: 'M256.8 599.2 C256.8 599.2 287.2 610 287.2 610',
      clipTo: 'abdomen',
    },
    {
      id: 'abdomen-segment',
      rank: 'structure',
      fill: 'none',
      d: 'M237.2 688.8 C237.2 688.8 268.8 702 268.8 702',
      clipTo: 'abdomen',
    },
    {
      id: 'abdomen-segment',
      rank: 'structure',
      fill: 'none',
      d: 'M217.6 778.4 C217.6 778.4 250.4 794 250.4 794',
      clipTo: 'abdomen',
    },
    {
      id: 'abdomen-segment',
      rank: 'structure',
      fill: 'none',
      d: 'M198 868 C198 868 232 886 232 886',
      clipTo: 'abdomen',
    },
    // One hemelytron — a forewing, hard at the base and membranous at the tip,
    // which is the character the order is named for.
    //
    // On this bug it is barely a wing at all in dorsal view: the scutellum takes
    // the middle of the animal and the corium is left as a strip down the side.
    // Authored as one closed shape whose inner edge follows the scutellum and
    // whose outer edge follows the abdomen.
    {
      id: 'forewing',
      rank: 'outline',
      fill: 'pigment',
      d: 'M250 358 C258.74 353.12 299.84 360.89 314 376 C331.03 394.17 329.99 438.01 334 470 C338.1 502.65 339.36 536.89 338 570 C336.65 602.89 332.87 636.52 326 668 C319.35 698.44 310.51 728.44 298 756 C285.73 783.04 270.08 808.94 252 832 C234.04 854.91 215.95 887.57 190 894 C160.27 901.36 88.95 882.38 80 860 C71.07 837.67 118.56 795.49 136 760 C154.76 721.83 173.5 680.48 188 638 C203.04 593.95 214.21 545.34 224 500 C233.34 456.73 241.18 393.14 246 372 C247.61 364.92 245.91 360.28 250 358 Z',
    },
    {
      id: 'wing-vein',
      rank: 'structure',
      fill: 'none',
      d: 'M300 400 C300 400 320.27 506.84 318 560 C315.71 613.51 304.08 670.72 286 720 C268.75 767.03 214 850 214 850',
      clipTo: 'forewing',
    },
    // The punctation, as three strokes. Brunner's figure is too small to carry
    // it and the animal's is dense and even; hatching is what an engraving has
    // for that.
    {
      id: 'hatching',
      rank: 'detail',
      fill: 'none',
      d: 'M252 430 C252 430 236.82 544.59 224 600 C211.38 654.56 176 760 176 760',
      clipTo: 'forewing',
    },
    {
      id: 'hatching',
      rank: 'detail',
      fill: 'none',
      d: 'M276 433 C276 433 267.62 545.27 256 600 C244.33 654.95 206 762 206 762',
      clipTo: 'forewing',
    },
    {
      id: 'hatching',
      rank: 'detail',
      fill: 'none',
      d: 'M300 436 C300 436 298.4 545.94 288 600 C277.36 655.3 236 764 236 764',
      clipTo: 'forewing',
    },
    // The scutellum, and it is most of the animal: from the pronotum's hind
    // margin almost to the tip of the abdomen. On the green shield bug this is a
    // triangle between the wings; here it *is* the back.
    {
      id: 'scutellum',
      rank: 'outline',
      fill: 'pigment',
      d: 'M0 352 C78.67 352 207.79 332.32 236 368 C257.21 394.83 223.4 455.56 214 500 C204.23 546.19 193.11 595.48 178 640 C163.52 682.64 144.93 724.31 126 762 C108.67 796.5 93.17 834.05 70 858 C50.02 878.66 23.33 902 0 902 C-23.33 902 -50.02 878.66 -70 858 C-93.17 834.05 -108.67 796.5 -126 762 C-144.93 724.31 -163.52 682.64 -178 640 C-193.11 595.48 -204.23 546.19 -214 500 C-223.4 455.56 -257.21 394.83 -236 368 C-207.79 332.32 -78.67 352 0 352 Z',
      mirror: false,
    },
    // The stripes on the scutellum: three a side, converging as the scutellum
    // narrows. Capsules clipped to it, so a stripe cannot end up beside the
    // animal, and mirrored, so there are six and they are symmetric.
    {
      id: 'marking',
      rank: 'structure',
      fill: 'pigment-deep',
      d: 'M33.01 385.5 C18.33 418.48 29.02 539.17 27.01 615.5 C25.02 691.16 8.23 808.16 21.01 841.5 C25.41 852.99 33.16 860.83 39.5 860.99 C45.83 861.16 53.98 853.75 58.99 842.5 C73.53 809.9 63 692.17 64.99 616.5 C67 540.17 83.93 420.19 70.99 386.5 C66.57 374.98 58.83 367.17 52.5 367.01 C46.16 366.84 38.02 374.24 33.01 385.5 Z',
      clipTo: 'scutellum',
    },
    {
      id: 'marking',
      rank: 'structure',
      fill: 'pigment-deep',
      d: 'M115.19 385.29 C97.78 414.61 94.69 525.38 85.18 593.37 C76.05 658.66 50.9 754.13 59.17 785.45 C62.25 797.11 69.17 805.98 75.45 806.83 C81.73 807.68 90.76 800.97 96.83 790.55 C113.12 762.57 113.7 663.86 122.82 598.63 C132.32 530.69 161.22 423.74 152.81 390.71 C149.8 378.9 142.98 370.1 136.71 369.19 C130.44 368.29 121.42 374.81 115.19 385.29 Z',
      clipTo: 'scutellum',
    },
    {
      id: 'marking',
      rank: 'structure',
      fill: 'pigment-deep',
      d: 'M187.76 388.68 C170.54 410.12 159.28 484.25 145.7 532.89 C131.89 582.37 101.94 655.23 105.64 683.1 C107.18 694.69 112.98 704.73 119.1 706.36 C125.22 707.99 135.26 702.17 142.36 692.9 C159.42 670.61 168.53 592.45 182.3 543.11 C195.84 494.61 227.22 426.61 224.24 399.32 C222.98 387.76 217.4 377.53 211.32 375.76 C205.24 373.99 195.04 379.61 187.76 388.68 Z',
      clipTo: 'scutellum',
    },
    {
      id: 'hatching',
      rank: 'detail',
      fill: 'none',
      d: 'M92 440 C92 440 70 620 70 620',
      clipTo: 'scutellum',
    },
    {
      id: 'hatching',
      rank: 'detail',
      fill: 'none',
      d: 'M112 450 C112 450 88 630 88 630',
      clipTo: 'scutellum',
    },
    // The pronotum: transverse, with the side margins drawn out into small
    // points, and the stripes running straight across it before they begin to
    // converge on the scutellum.
    {
      id: 'pronotum',
      rank: 'outline',
      fill: 'pigment',
      d: 'M0 126 C40 126 80.64 125.35 120 134 C160.69 142.94 205.19 160.77 240 180 C270.71 196.97 301.28 217.57 320 240 C335.33 258.37 348.4 281.02 350 300 C351.35 316.07 348.95 335.49 336 346 C314.18 363.7 249.74 355.06 200 358 C139.79 361.56 66.67 364 0 364 C-66.67 364 -139.79 361.56 -200 358 C-249.74 355.06 -314.18 363.7 -336 346 C-348.95 335.49 -351.35 316.07 -350 300 C-348.4 281.02 -335.33 258.37 -320 240 C-301.28 217.57 -270.71 196.97 -240 180 C-205.19 160.77 -160.69 142.94 -120 134 C-80.64 125.35 -40 126 0 126 Z',
      mirror: false,
    },
    {
      id: 'marking',
      rank: 'structure',
      fill: 'pigment-deep',
      d: 'M40 160 C32.62 177.81 39.65 220.66 40 250.21 C40.34 278.77 34.56 317.6 42.01 334.43 C46.1 343.68 54.43 352.14 60.43 351.99 C66.43 351.85 74.35 343 77.99 333.57 C84.61 316.46 76.34 278.2 76 249.79 C75.65 220.38 83.35 177.75 76 160 C72.08 150.55 64 142 58 142 C52 142 43.92 150.54 40 160 Z',
      clipTo: 'pronotum',
    },
    {
      id: 'marking',
      rank: 'structure',
      fill: 'pigment-deep',
      d: 'M134.09 179.84 C129.06 196.67 139.07 232.39 142.13 258.12 C145.11 283.23 143.61 317.72 152.16 332.41 C157.14 340.97 166.46 348.64 172.41 347.84 C178.36 347.03 185.31 337.15 187.84 327.59 C192.16 311.24 180.84 278.8 177.87 253.88 C174.84 228.34 178.21 191.55 169.91 176.16 C165.17 167.38 156.13 159.48 150.16 160.09 C144.19 160.71 136.96 170.26 134.09 179.84 Z',
      clipTo: 'pronotum',
    },
    {
      id: 'marking',
      rank: 'structure',
      fill: 'pigment-deep',
      d: 'M221.2 228.46 C220.85 242.31 234.7 263.7 241.22 280.51 C247.36 296.34 250.42 317.39 259.24 326.56 C265.56 333.14 276.97 338.95 282.56 336.76 C288.15 334.58 292.58 322.56 292.76 313.44 C293.01 300.74 280.91 283.29 274.78 267.49 C268.27 250.71 264.33 225.56 254.8 215.54 C248.36 208.76 237.14 203.05 231.54 205.2 C225.94 207.35 221.44 219.11 221.2 228.46 Z',
      clipTo: 'pronotum',
    },
    {
      id: 'hatching',
      rank: 'detail',
      fill: 'none',
      d: 'M96 250 C96 250 92 330 92 330',
      clipTo: 'pronotum',
    },
    {
      id: 'hatching',
      rank: 'detail',
      fill: 'none',
      d: 'M116 250 C116 250 114 330 114 330',
      clipTo: 'pronotum',
    },
    {
      id: 'head',
      rank: 'outline',
      fill: 'pigment',
      d: 'M0 0 C15.33 0 34.08 4.63 46 14 C58.29 23.66 65.37 42.24 72 58 C78.81 74.18 86.06 94.26 86 110 C85.95 123.11 85.21 137.78 76 146 C62.78 157.79 25.33 158 0 158 C-25.33 158 -62.78 157.79 -76 146 C-85.21 137.78 -85.95 123.11 -86 110 C-86.06 94.26 -78.81 74.18 -72 58 C-65.37 42.24 -58.29 23.66 -46 14 C-34.08 4.63 -15.33 0 0 0 Z',
      mirror: false,
    },
    // The stripes carry on across the head, which is what makes the animal read
    // as striped end to end rather than as a striped back with a plain head.
    {
      id: 'marking',
      rank: 'structure',
      fill: 'pigment-deep',
      d: 'M17 34 C12.53 44.78 16.65 67.87 17 84.28 C17.35 100.03 14.35 120.57 19.01 130.56 C21.95 136.86 28.24 143.18 32.56 142.99 C36.89 142.8 42.62 135.95 44.99 129.44 C48.73 119.16 43.34 99.28 43 83.72 C42.64 67.5 47.43 44.7 43 34 C40.31 27.49 34.33 21 30 21 C25.67 21 19.7 27.48 17 34 Z',
      clipTo: 'head',
    },
    {
      id: 'marking',
      rank: 'structure',
      fill: 'pigment-deep',
      d: 'M49 76 C46.29 82.53 48.65 93.82 49.01 102.46 C49.36 110.78 47.97 120.96 51.04 126.91 C53.48 131.66 59.26 137.27 62.91 136.96 C66.57 136.66 71.35 130.12 72.96 125.09 C74.95 118.88 71.32 109.56 70.99 101.54 C70.64 93.21 73.64 82.37 71 76 C68.94 71.03 63.67 65 60 65 C56.33 65 51.07 70.99 49 76 Z',
      clipTo: 'head',
    },
    {
      id: 'eye',
      rank: 'detail',
      fill: 'ink',
      d: 'M104 124 C104 133.94 94.15 142 82 142 C69.85 142 60 133.94 60 124 C60 114.06 69.85 106 82 106 C94.15 106 104 114.06 104 124 Z',
    },
    // The antenna: five joints, filiform, held forward. Banded black and red on
    // the animal, which the plate cannot say and the record does not need to.
    {
      id: 'antenna',
      rank: 'structure',
      fill: 'none',
      d: 'M86 120 C86 120 109.68 87.31 120 70 C130.35 52.64 148 16 148 16',
    },
    {
      id: 'antenna',
      rank: 'structure',
      fill: 'none',
      d: 'M148 16 C148 16 167.39 -34.21 176 -60 C184.74 -86.19 200 -140 200 -140',
    },
    {
      id: 'antenna',
      rank: 'detail',
      fill: 'pigment-deep',
      d: 'M214.33 -141.89 C222.95 -152.31 232.68 -190.26 231.49 -202.84 C230.92 -208.78 228.32 -214.43 225.16 -215.49 C222 -216.54 216.53 -213.58 212.51 -209.16 C204.01 -199.82 189.03 -163.61 189.67 -150.11 C190.01 -142.83 193.78 -135.04 197.89 -133.67 C202 -132.3 209.69 -136.27 214.33 -141.89 Z',
    },
    {
      id: 'antenna',
      rank: 'detail',
      fill: 'pigment-deep',
      d: 'M233.63 -209.3 C239.76 -218.11 243.29 -252.9 241.85 -260.92 C241.38 -263.56 240.36 -265.49 239.08 -265.85 C237.79 -266.21 235.92 -265.09 234.15 -263.08 C228.76 -256.97 213.7 -225.41 214.37 -214.7 C214.72 -209.12 218.09 -203.27 221.3 -202.37 C224.51 -201.47 230.44 -204.72 233.63 -209.3 Z',
    },
  ],
};
