// Generated from ../landmarks/gryllus-campestris.json by `npm run plate:build`.
//
// Do not edit this file. Edit the landmarks and build again; `npm run
// plate:verify` fails the check if the two drift apart.

import type { SpeciesPlate } from '@/lib/plate';

/**
 * *Gryllus campestris*, dorsal — the field cricket, male.
 *
 * The archive's first Orthoptera, and the first plate whose order had to be
 * added to `PLATE_ORDERS` and `REQUIRED_PARTS`. Traced from the Orthoptères
 * plate of the *Musée entomologique illustré* (1878), where the cricket is
 * named in the margin and shares the sheet with a mole cricket, two earwigs
 * and a cockroach. `references/gryllus-campestris.jpg` is the plate.
 *
 * ## The reference is not a dorsal figure, and that had to be worked round
 *
 * This is the only reference in the folder that is a *habitat scene* rather
 * than a specimen figure: the animals are drawn among bindweed and grass, lit,
 * and posed. The cricket is seen from above and a little behind — close to
 * dorsal, and not square to it.
 *
 * So what came off the plate is the arrangement: where the pronotum ends and
 * the tegmina begin, how far the hind femur reaches, how the antennae sweep
 * back, that the tegminal venation is coarse enough to count. The
 * *proportions* were then taken from the published measurements — 19 to 27 mm
 * long, about a third as wide as long — because a foreshortened figure cannot
 * give them and guessing from one would have made the animal too short. That
 * is a weaker provenance than the other fifteen plates have and it is recorded
 * here rather than left for somebody to notice.
 *
 * ## What the drawing has to get right
 *
 * The **tegmina**: leathery forewings lying flat over the abdomen, one
 * overlapping the other, with venation coarse enough to draw. They are the
 * reason `WING_COVERS` gained a `tegmina` state — a cricket's forewings are
 * not the hard cases of a beetle and not the clear membrane of a wasp, and
 * making the record answer either would have been making it lie.
 *
 * The **stridulatory field** on the tegmen — the harp and the oval mirror a
 * male rubs to sing — is drawn as one cell, because it is the reason this
 * plate commits to a sex and because a field cricket is far more often heard
 * than seen.
 *
 * Then the **hind femur**, which is a third of the animal and three times the
 * depth of any other limb here. Drawn at the ground beetle's proportions a
 * cricket cannot jump, and a saltatorial leg is the character that puts it in
 * this order at a glance.
 *
 * Then the **cerci**: the two long tails at the tip of the abdomen. They are
 * the part `REQUIRED_PARTS.orthoptera` asks for that no other order does, and
 * `cercus` had been sitting in `PLATE_PART_IDS` unused since the schema was
 * written, with a comment saying it was for a cricket's tails.
 *
 * ## Plate space
 *
 * y = 0 at the front of the head, y = 1000 at the tip of the abdomen. Pronotum
 * 210 to 420, tegmina 410 to 900. The cerci reach y = 1210 and the antennae
 * out to x = 520 and above y = -360.
 */
export const GRYLLUS_CAMPESTRIS_PLATE: SpeciesPlate = {
  species: 'gryllus-campestris',
  order: 'orthoptera',
  sex: 'male',
  hallmark:
    'the leathery tegmina with their coarse venation, the huge hind femora, and the pair of cerci',
  reference: {
    title: 'Musée entomologique illustré: Les insectes, Orthoptères plate I',
    artist: 'Jules Rothschild',
    year: 1878,
    source: 'https://commons.wikimedia.org/wiki/File:Les_insectes_(Pl._I)_(6008126611).jpg',
    licence: 'Public domain (PD-old-70-expired)',
  },
  parts: [
    // The legs first, so they pass under the body.
    //
    // The hind femur is the whole point of the order: 130 units deep against 44
    // for the fore femur, which is the ratio the measurements give and roughly
    // what the reference shows. Everything a cricket does that a beetle cannot
    // is in that shape.
    {
      id: 'hindleg-femur',
      rank: 'structure',
      fill: 'pigment-deep',
      d: 'M78.84 520.31 C97.68 553.38 153.84 575.15 191.08 603 C228.37 630.9 270.13 676.7 302.42 687.58 C322.71 694.41 348.38 696.77 357.58 687.58 C366.77 678.38 364.51 652.83 357.58 632.42 C346.32 599.28 301.68 552.47 268.92 517 C236.2 481.57 198.42 431.93 161.16 419.69 C131.52 409.95 83.41 412.07 69.69 428.84 C55.97 445.61 63.54 493.45 78.84 520.31 Z',
    },
    {
      id: 'hindleg-tibia',
      rank: 'structure',
      fill: 'pigment-deep',
      d: 'M310.13 671.59 C314.26 698.87 361.45 748.9 383.05 788.58 C403.99 827.07 421.36 890.12 438.24 905.96 C445.06 912.37 453.38 915.75 457.96 913.76 C462.55 911.78 465.77 903.42 465.76 894.04 C465.74 870.63 435.9 811.76 416.95 771.42 C397.43 729.85 371.82 665.61 349.87 648.41 C339.29 640.13 325.03 636.27 318.41 640.13 C311.79 644 308.13 658.34 310.13 671.59 Z',
    },
    {
      id: 'hindleg-tarsus',
      rank: 'detail',
      fill: 'pigment-deep',
      d: 'M439.93 904.83 C439.97 918.59 456.43 954.79 465.79 964.09 C470.38 968.64 476.68 971.58 480.09 970.21 C483.49 968.85 486.03 962.38 486.21 955.91 C486.58 942.73 473.53 905.17 464.07 895.17 C459.03 889.84 451.2 886.32 447.17 887.93 C443.15 889.54 439.91 897.49 439.93 904.83 Z',
    },
    {
      id: 'hindleg-tarsus',
      rank: 'detail',
      fill: 'pigment-deep',
      d: 'M467.72 969.9 C467.54 982.57 483.22 1018.59 491.59 1027.19 C495.37 1031.09 500.39 1033.48 503.19 1032.41 C506 1031.35 508.16 1026.23 508.41 1020.81 C508.97 1008.83 496.82 971.46 488.28 962.1 C484.01 957.41 477.53 954.41 474.1 955.72 C470.67 957.02 467.8 963.56 467.72 969.9 Z',
    },
    {
      id: 'hindleg-tarsus',
      rank: 'detail',
      fill: 'ink',
      d: 'M493.49 1032.93 C493.31 1044.56 512.76 1083.02 518.69 1089.14 C520.37 1090.88 522.04 1091.69 523.14 1091.31 C524.24 1090.93 525.05 1089.26 525.31 1086.86 C526.21 1078.38 517.82 1036.1 510.51 1027.07 C507.19 1022.96 501.9 1020.51 499.07 1021.49 C496.23 1022.47 493.58 1027.65 493.49 1032.93 Z',
    },
    {
      id: 'midleg-femur',
      rank: 'structure',
      fill: 'pigment-deep',
      d: 'M122.85 422.82 C141.39 427.67 176.23 414.73 202.4 410.86 C227.89 407.1 262.81 408.47 277.88 399.9 C286.59 394.95 294.53 386.08 293.9 380.12 C293.27 374.15 283.67 367.13 274.12 364.1 C257.53 358.83 223.41 367 197.6 369.14 C171.1 371.33 133.98 367.88 117.15 377.18 C106.47 383.07 96.23 395.25 97.18 402.85 C98.13 410.46 111.07 419.74 122.85 422.82 Z',
    },
    {
      id: 'midleg-tibia',
      rank: 'structure',
      fill: 'pigment-deep',
      d: 'M284.97 395.25 C300.94 391.74 326.63 366.47 346.26 351.31 C365.4 336.51 394.47 318.21 401.41 305.44 C404.79 299.22 405.91 291.73 403.44 288.59 C400.96 285.44 393.41 284.76 386.59 286.56 C372.66 290.26 349.4 315.16 329.74 328.69 C309.58 342.58 276.12 355.35 267.03 368.75 C262.01 376.14 259.76 386.56 262.75 390.97 C265.74 395.39 276.23 397.17 284.97 395.25 Z',
    },
    {
      id: 'midleg-tarsus',
      rank: 'detail',
      fill: 'pigment-deep',
      d: 'M401.46 304.08 C409.48 300.94 423.09 286.67 426.44 278.98 C428.51 274.25 429.13 267.88 426.98 265.56 C424.83 263.23 418.44 263.34 413.56 265.02 C405.63 267.75 390.32 280.17 386.54 287.92 C384.04 293.05 383.43 300.77 385.92 303.46 C388.4 306.16 396.15 306.17 401.46 304.08 Z',
    },
    {
      id: 'midleg-tarsus',
      rank: 'detail',
      fill: 'pigment-deep',
      d: 'M429.58 274.85 C437.08 271.74 450.55 257.01 453.54 249.77 C455.25 245.64 455.62 240.38 453.77 238.46 C451.92 236.54 446.66 236.69 442.46 238.23 C435.1 240.92 419.84 253.78 416.42 261.15 C414.29 265.73 413.95 272.29 416.15 274.58 C418.34 276.86 424.91 276.79 429.58 274.85 Z',
    },
    {
      id: 'midleg-tarsus',
      rank: 'detail',
      fill: 'ink',
      d: 'M456.77 245.54 C463.66 241.94 476.41 221.67 478.16 216.08 C478.76 214.17 478.8 212.53 478.08 211.84 C477.36 211.14 475.72 211.25 473.84 211.92 C468.32 213.89 448.56 227.42 445.23 234.46 C443.38 238.37 443.53 243.92 445.46 245.77 C447.38 247.61 452.92 247.55 456.77 245.54 Z',
    },
    {
      id: 'foreleg-femur',
      rank: 'structure',
      fill: 'pigment-deep',
      d: 'M120.29 270.57 C140.93 268.87 175.56 242.53 199.88 228.53 C221.25 216.23 249.13 204.72 258.87 191.66 C264.77 183.76 268.62 172.35 265.66 167.13 C262.7 161.91 250.9 159.35 241.13 160.34 C225.09 161.96 201.95 180.75 180.12 191.47 C155.26 203.68 113.35 214.06 99.71 229.43 C91.47 238.72 86 253.43 89.43 260.29 C92.86 267.14 107.87 271.59 120.29 270.57 Z',
    },
    {
      id: 'foreleg-tibia',
      rank: 'structure',
      fill: 'pigment-deep',
      d: 'M261.94 186.66 C276.64 179.32 296.17 148.62 311.01 128.65 C325.39 109.3 347.04 83.02 349.88 68.81 C351.26 61.88 350.11 54.39 346.81 52.12 C343.52 49.85 336.08 51.45 330.12 55.19 C318.05 62.76 304.05 93.26 288.99 111.35 C273.45 130.02 243.61 150.15 238.06 165.34 C235.01 173.73 235.37 184.38 239.34 187.94 C243.32 191.49 253.91 190.66 261.94 186.66 Z',
    },
    {
      id: 'foreleg-tarsus',
      rank: 'detail',
      fill: 'pigment-deep',
      d: 'M349.62 67.34 C357.01 61.25 367.41 39.86 368.3 30.61 C368.81 25.33 367.38 19.23 364.61 17.7 C361.85 16.16 355.91 18.16 351.7 21.39 C344.31 27.03 331.65 47.16 330.38 56.66 C329.61 62.5 331.45 69.84 334.66 71.62 C337.86 73.4 345.07 71.09 349.62 67.34 Z',
    },
    {
      id: 'foreleg-tarsus',
      rank: 'detail',
      fill: 'pigment-deep',
      d: 'M370.5 24.25 C377.19 18.22 386.7 -3.78 387.16 -12.42 C387.4 -17 385.96 -21.96 383.58 -23.16 C381.19 -24.35 376.37 -22.52 372.84 -19.58 C366.2 -14.03 354.31 6.78 353.5 15.75 C353.04 20.93 354.92 27.08 357.75 28.5 C360.58 29.91 366.63 27.73 370.5 24.25 Z',
    },
    {
      id: 'foreleg-tarsus',
      rank: 'detail',
      fill: 'ink',
      d: 'M389.16 -18.42 C395.15 -24.3 402.63 -50.41 402.68 -56.66 C402.7 -58.68 402.24 -60.24 401.34 -60.68 C400.45 -61.13 398.92 -60.57 397.32 -59.34 C392.35 -55.55 375.96 -33.9 374.84 -25.58 C374.26 -21.18 376.04 -16.04 378.42 -14.84 C380.81 -13.65 385.99 -15.32 389.16 -18.42 Z',
    },
    // The abdomen, drawn before the tegmina so they lie over it. Only its last
    // two segments and the cerci show on the finished plate, which is what a
    // cricket at rest looks like from above.
    {
      id: 'abdomen',
      rank: 'outline',
      fill: 'pigment',
      d: 'M0 396 C36.67 396 85.89 388.07 110 404 C129.78 417.07 137.11 444.9 144 470 C152 499.15 149.6 535.86 150 570 C150.42 605.78 148.33 643.36 146 680 C143.67 716.7 141.86 754.41 136 790 C130.35 824.34 124.87 861.67 112 890 C100.93 914.36 87.03 937.64 68 952 C49.47 965.98 22.67 976 0 976 C-22.67 976 -49.47 965.98 -68 952 C-87.03 937.64 -100.93 914.36 -112 890 C-124.87 861.67 -130.35 824.34 -136 790 C-141.86 754.41 -143.67 716.7 -146 680 C-148.33 643.36 -150.42 605.78 -150 570 C-149.6 535.86 -152 499.15 -144 470 C-137.11 444.9 -129.78 417.07 -110 404 C-85.89 388.07 -36.67 396 0 396 Z',
      mirror: false,
    },
    {
      id: 'abdomen-segment',
      rank: 'structure',
      fill: 'none',
      d: 'M-136 500 C-136 500 -45.33 500 0 500 C45.33 500 136 500 136 500',
      mirror: false,
      clipTo: 'abdomen',
    },
    {
      id: 'abdomen-segment',
      rank: 'structure',
      fill: 'none',
      d: 'M-124.5 600 C-124.5 600 -41.5 600 0 600 C41.5 600 124.5 600 124.5 600',
      mirror: false,
      clipTo: 'abdomen',
    },
    {
      id: 'abdomen-segment',
      rank: 'structure',
      fill: 'none',
      d: 'M-113 700 C-113 700 -37.67 700 0 700 C37.67 700 113 700 113 700',
      mirror: false,
      clipTo: 'abdomen',
    },
    {
      id: 'abdomen-segment',
      rank: 'structure',
      fill: 'none',
      d: 'M-101.5 800 C-101.5 800 -33.83 800 0 800 C33.83 800 101.5 800 101.5 800',
      mirror: false,
      clipTo: 'abdomen',
    },
    {
      id: 'abdomen-segment',
      rank: 'structure',
      fill: 'none',
      d: 'M-90 900 C-90 900 -30 900 0 900 C30 900 90 900 90 900',
      mirror: false,
      clipTo: 'abdomen',
    },
    // A cercus, in two joints. The pair of them is what `REQUIRED_PARTS` asks
    // this order for and no other, and they are longer than they look — nearly
    // a quarter of the animal past the tip of the abdomen.
    {
      id: 'cercus',
      rank: 'structure',
      fill: 'pigment-deep',
      d: 'M40.62 966.79 C42.94 991.31 94.53 1080.83 111.08 1094.53 C116.24 1098.79 121.55 1100.43 124.53 1098.92 C127.5 1097.41 129.32 1092.15 128.92 1085.47 C127.63 1064.03 85.8 969.55 67.38 953.21 C60.35 946.98 51.67 944.36 47.21 946.62 C42.75 948.89 39.74 957.44 40.62 966.79 Z',
    },
    {
      id: 'cercus',
      rank: 'detail',
      fill: 'pigment-deep',
      d: 'M112.96 1100.28 C114.42 1119.52 162.99 1203.03 172.84 1211.5 C174.79 1213.17 176.44 1213.66 177.5 1213.16 C178.55 1212.66 179.22 1211.07 179.16 1208.5 C178.85 1195.52 145 1105.03 131.04 1091.72 C126.37 1087.27 120.73 1085.54 117.72 1086.96 C114.71 1088.39 112.48 1093.84 112.96 1100.28 Z',
    },
    // One tegmen: a leathery forewing lying flat over the abdomen. Authored
    // from the midline out, so the renderer's reflection supplies the other —
    // which is a small lie, because on the animal one tegmen overlaps the other
    // and they are not symmetric. A plate that drew the overlap would have to
    // choose a side, and the character a reader is being shown is that the
    // covers are leathery and flat rather than which of them is on top.
    {
      id: 'forewing',
      rank: 'outline',
      fill: 'pigment',
      d: 'M0 406 C0 384.66 69.31 401.19 96 410 C118.4 417.4 139.62 429.72 152 448 C165.79 468.36 166.63 501.86 170 530 C173.49 559.14 172.93 589.54 172 620 C171.04 651.51 168.76 684.67 164 716 C159.34 746.65 153.81 778.89 144 806 C135.2 830.33 125.4 856.06 110 872 C96.47 886.01 78.06 894.31 60 900 C41.47 905.84 0 919.43 0 906 C0 867.31 0 454.68 0 406 Z',
    },
    // The venation, which on a tegmen is coarse enough to draw stroke for
    // stroke rather than suggested — five lengthwise, four across.
    {
      id: 'wing-vein',
      rank: 'structure',
      fill: 'none',
      d: 'M24 450 C24 450 24.11 581.76 26 650 C27.98 721.6 36 870 36 870',
      clipTo: 'forewing',
    },
    {
      id: 'wing-vein',
      rank: 'structure',
      fill: 'none',
      d: 'M52 455 C52 455 57.73 583.49 57.5 650 C57.26 719.68 50 864 50 864',
      clipTo: 'forewing',
    },
    {
      id: 'wing-vein',
      rank: 'structure',
      fill: 'none',
      d: 'M80 460 C80 460 91.34 585.33 89 650 C86.55 717.87 64 858 64 858',
      clipTo: 'forewing',
    },
    {
      id: 'wing-vein',
      rank: 'structure',
      fill: 'none',
      d: 'M108 465 C108 465 124.89 587.29 120.5 650 C115.86 716.17 78 852 78 852',
      clipTo: 'forewing',
    },
    {
      id: 'wing-vein',
      rank: 'structure',
      fill: 'none',
      d: 'M136 470 C136 470 158.34 589.35 152 650 C145.24 714.6 92 846 92 846',
      clipTo: 'forewing',
    },
    {
      id: 'wing-vein',
      rank: 'detail',
      fill: 'none',
      d: 'M40 500 C40 500 130 520 130 520',
      clipTo: 'forewing',
    },
    {
      id: 'wing-vein',
      rank: 'detail',
      fill: 'none',
      d: 'M42 606.67 C42 606.67 120 613.33 120 613.33',
      clipTo: 'forewing',
    },
    {
      id: 'wing-vein',
      rank: 'detail',
      fill: 'none',
      d: 'M44 713.33 C44 713.33 110 706.67 110 706.67',
      clipTo: 'forewing',
    },
    {
      id: 'wing-vein',
      rank: 'detail',
      fill: 'none',
      d: 'M46 820 C46 820 100 800 100 800',
      clipTo: 'forewing',
    },
    // The pale patch at the base of the tegmen — yellow on the animal, and the
    // one bright mark on a cricket that is otherwise glossy black.
    {
      id: 'marking',
      rank: 'structure',
      fill: 'surface',
      d: 'M143.39 452.95 C141.28 464.91 121.94 471.5 100.18 467.67 C78.42 463.83 62.5 451.02 64.61 439.05 C66.72 427.09 86.06 420.5 107.82 424.33 C129.58 428.17 145.5 440.98 143.39 452.95 Z',
      clipTo: 'forewing',
    },
    // The mirror: the oval cell in the stridulatory field that a male rubs to
    // sing, and the reason this plate commits to a sex. A field cricket is
    // heard far more often than it is seen, and this is the organ that does it.
    {
      id: 'marking',
      rank: 'structure',
      fill: 'none',
      d: 'M143.68 693.94 C146.22 718.1 122.46 740.41 90.6 743.76 C58.74 747.11 30.86 730.23 28.32 706.06 C25.78 681.9 49.54 659.59 81.4 656.24 C113.26 652.89 141.14 669.77 143.68 693.94 Z',
      clipTo: 'forewing',
    },
    // The pronotum: a transverse saddle with almost straight sides, and shorter
    // than it is wide. A cricket has no scutellum, which is why
    // `REQUIRED_PARTS.orthoptera` does not ask for one.
    {
      id: 'pronotum',
      rank: 'outline',
      fill: 'pigment-deep',
      d: 'M0 206 C30.67 206 63.78 204.81 92 208 C116.51 210.77 146.4 209.7 160 222 C171.57 232.47 172.16 252.27 175 270 C178.35 290.92 177.36 317.81 176 340 C174.75 360.29 178.81 385.65 168 398 C157.04 410.51 132.63 410.31 110 414 C79.37 419 36.67 420 0 420 C-36.67 420 -79.37 419 -110 414 C-132.63 410.31 -157.04 410.51 -168 398 C-178.81 385.65 -174.75 360.29 -176 340 C-177.36 317.81 -178.35 290.92 -175 270 C-172.16 252.27 -171.57 232.47 -160 222 C-146.4 209.7 -116.51 210.77 -92 208 C-63.78 204.81 -30.67 206 0 206 Z',
      mirror: false,
    },
    {
      id: 'hatching',
      rank: 'detail',
      fill: 'none',
      d: 'M40 250 C40 250 38 380 38 380',
      clipTo: 'pronotum',
    },
    {
      id: 'hatching',
      rank: 'detail',
      fill: 'none',
      d: 'M88 254 C88 254 89 379 89 379',
      clipTo: 'pronotum',
    },
    {
      id: 'hatching',
      rank: 'detail',
      fill: 'none',
      d: 'M136 258 C136 258 140 378 140 378',
      clipTo: 'pronotum',
    },
    // The head: large, rounded and as wide as the pronotum, which is a cricket
    // and not a grasshopper — a grasshopper's head is drawn out and slanted.
    {
      id: 'head',
      rank: 'outline',
      fill: 'pigment-deep',
      d: 'M0 -6 C23.33 -6 49.39 -4.69 70 4 C89.86 12.37 107.9 27.11 122 44 C137 61.97 149.85 87.88 156 110 C161.53 129.9 164.83 152.27 160 170 C155.46 186.68 144.05 203.72 130 214 C114.76 225.15 90.99 228 70 232 C47.77 236.24 23.33 238 0 238 C-23.33 238 -47.77 236.24 -70 232 C-90.99 228 -114.76 225.15 -130 214 C-144.05 203.72 -155.46 186.68 -160 170 C-164.83 152.27 -161.53 129.9 -156 110 C-149.85 87.88 -137 61.97 -122 44 C-107.9 27.11 -89.86 12.37 -70 4 C-49.39 -4.69 -23.33 -6 0 -6 Z',
      mirror: false,
    },
    {
      id: 'eye',
      rank: 'detail',
      fill: 'ink',
      d: 'M146 86 C146 100.36 132.57 112 116 112 C99.43 112 86 100.36 86 86 C86 71.64 99.43 60 116 60 C132.57 60 146 71.64 146 86 Z',
    },
    // The three ocelli, in a line across the face between the compound eyes:
    // one on the midline, drawn once, and a pair either side of it.
    {
      id: 'ocellus',
      rank: 'detail',
      fill: 'ink',
      d: 'M14 34 C14 40.63 7.73 46 0 46 C-7.73 46 -14 40.63 -14 34 C-14 27.37 -7.73 22 0 22 C7.73 22 14 27.37 14 34 Z',
      mirror: false,
    },
    {
      id: 'ocellus',
      rank: 'detail',
      fill: 'ink',
      d: 'M60 26 C60 32.63 53.73 38 46 38 C38.27 38 32 32.63 32 26 C32 19.37 38.27 14 46 14 C53.73 14 60 19.37 60 26 Z',
    },
    {
      id: 'mandible',
      rank: 'structure',
      fill: 'pigment-deep',
      d: 'M61.5 14.33 C71.51 7.6 85.89 -15.09 85.86 -28.15 C85.83 -39.36 72.56 -54.94 67.77 -59.35 C65.87 -61.09 63.91 -62.22 62.65 -61.77 C61.4 -61.32 60.68 -59.08 60.23 -56.65 C59.29 -51.57 65.15 -39.51 62.14 -31.85 C58.44 -22.43 37.85 -15.63 34.5 -6.33 C31.81 1.11 33.17 14.06 37.67 17.5 C42.17 20.95 54.49 19.04 61.5 14.33 Z',
    },
    // The antenna. Filiform and very long — as long as the body on the animal,
    // and about three quarters of it here, because the frame is measured from
    // the drawing and a full-length pair would leave the cricket small in the
    // middle of a mostly empty box.
    //
    // Three open strokes rather than a chain of joints: the segments are far too
    // fine to draw, and what has to read is the sweep.
    {
      id: 'antenna',
      rank: 'structure',
      fill: 'none',
      d: 'M92 40 C92 40 150.34 -13.68 180 -40 C209.68 -66.34 270 -118 270 -118',
    },
    {
      id: 'antenna',
      rank: 'structure',
      fill: 'none',
      d: 'M270 -118 C270 -118 330.93 -173.31 360 -200 C387.5 -225.25 440 -274 440 -274',
    },
    {
      id: 'antenna',
      rank: 'detail',
      fill: 'none',
      d: 'M440 -274 C440 -274 475.67 -312.94 490 -330 C501.51 -343.7 520 -368 520 -368',
    },
  ],
};
