// Generated from ../landmarks/ischnura-elegans.json by `npm run plate:build`.
//
// Do not edit this file. Edit the landmarks and build again; `npm run
// plate:verify` fails the check if the two drift apart.

import type { SpeciesPlate } from '@/lib/plate';

/**
 * *Ischnura elegans*, dorsal — the blue-tailed damselfly, male.
 *
 * The second plate from Lucas's *British Dragonflies* (1900), after the
 * southern hawker, and chosen for the contrast: the two animals are the same
 * order and nothing else. `references/ischnura-elegans.jpg` is plate XXIV,
 * where the damselfly is the lower pair and the upper pair is *Ischnura
 * pumilio*; the right-hand lower figure is the one traced.
 *
 * ## What the drawing has to get right
 *
 * The **build**. A damselfly is a hawker with everything taken away: an
 * abdomen thirty-eight units across in a body a thousand long, against the
 * hawker's seventy-eight, and wings that are narrow lenses on a stalk rather
 * than the hawker's broad triangles. `bodyShape` says `slender` for both,
 * which is as much as a closed union can say; the plates say the rest, and
 * side by side on the contact sheet they say it immediately.
 *
 * On the animals the ratio is nearer three to one than two — a hawker's
 * abdomen is a tenth of its length and a damselfly's a twenty-fifth. The
 * hawker's plate draws its own a little narrow, which is a note for whoever
 * redraws it rather than something to fix here by drawing this one wrong.
 *
 * Then the **stripes**, which are what the record's `markings` means here: two
 * pale antehumeral stripes down the thorax, running head to tail, the
 * character a reader is asked about. Drawn as capsules clipped to the thorax,
 * so they cannot slide off it.
 *
 * Then the **tail-light**. Segment eight is bright blue and segments seven and
 * nine are not, which is the whole of the English name and the quickest way to
 * tell this animal from the several other blue damselflies. Drawn as bare
 * paper on the midline, clipped to the abdomen, at the eighth of the ten
 * segments the ring lines mark out.
 *
 * ## Lucas draws one side at a time
 *
 * The same problem the hawker had, and the same answer. Lucas spreads each
 * figure's wings to one side and its legs to the other so the two do not
 * overlap on the page; the animal has both on both sides, so the wings are
 * measured off one side, the legs off the other, and each is authored on the
 * right half for the renderer to reflect.
 *
 * ## Plate space
 *
 * y = 0 at the front of the head, y = 1000 at the tip of the abdomen. The
 * thorax is 76 to 258 — a fifth of the animal — and everything after it is
 * abdomen. The four wings spring from the thorax and reach past x = 610; the legs are short and held forward, and only the fore tarsi pass above y = 0.
 */
export const ISCHNURA_ELEGANS_PLATE: SpeciesPlate = {
  species: 'ischnura-elegans',
  order: 'odonata',
  sex: 'male',
  hallmark:
    'the needle abdomen, the pale antehumeral stripes and the blue tail-light on the eighth segment',
  reference: {
    title: 'British Dragonflies (Odonata), plate XXIV, lower pair',
    artist: 'William John Lucas',
    year: 1900,
    source:
      'https://commons.wikimedia.org/wiki/File:British_dragonflies_(Plate_XXIV)_(6001792845).jpg',
    licence: 'Public domain (published 1900; author died 1932)',
  },
  parts: [
    // The legs first, so they pass under the wings and the body.
    //
    // Short, fine and held forward: a damselfly catches small flies in a basket
    // made of its own legs, which is why all six point ahead of the thorax
    // rather than out from it. The spines Lucas draws on each tibia are left
    // out — at eighty pixels they are a furred outline.
    {
      id: 'hindleg-femur',
      rank: 'structure',
      fill: 'pigment-deep',
      d: 'M20.62 202.47 C28.5 204.79 48.44 198.73 62.39 197.49 C76.32 196.24 97.44 198.25 104.24 194.99 C107.03 193.66 109.07 191.43 108.99 189.76 C108.92 188.1 106.67 186.07 103.76 185.01 C96.66 182.4 75.66 185.76 61.61 186.51 C47.53 187.27 26.71 185.75 19.38 189.53 C15.97 191.29 13.32 194.46 13.53 196.62 C13.73 198.77 16.93 201.39 20.62 202.47 Z',
    },
    {
      id: 'hindleg-tibia',
      rank: 'structure',
      fill: 'pigment-deep',
      d: 'M105.83 194.11 C112.77 193.89 129.92 183.19 141.66 177.64 C153.13 172.21 171.36 165.77 175.49 161.17 C176.99 159.5 177.66 157.57 177.17 156.51 C176.67 155.45 174.75 154.74 172.51 154.83 C166.34 155.08 149.92 165.25 138.34 170.36 C126.48 175.6 106.98 180.89 102.17 185.89 C100.24 187.9 99.28 190.46 99.89 191.83 C100.5 193.2 103.04 194.2 105.83 194.11 Z',
    },
    {
      id: 'hindleg-tarsus',
      rank: 'detail',
      fill: 'pigment-deep',
      d: 'M175.46 160.62 C179.37 160.13 190.93 153.14 193.21 150.19 C194.16 148.96 194.59 147.51 194.19 146.79 C193.78 146.06 192.33 145.66 190.79 145.81 C187.07 146.2 175.03 152.32 172.54 155.38 C171.41 156.76 170.89 158.58 171.38 159.46 C171.86 160.33 173.68 160.85 175.46 160.62 Z',
    },
    {
      id: 'hindleg-tarsus',
      rank: 'detail',
      fill: 'pigment-deep',
      d: 'M195.29 148.14 C199.22 147.47 212.83 138.03 214.77 135.29 C215.36 134.46 215.54 133.66 215.29 133.23 C215.03 132.8 214.23 132.59 213.23 132.71 C209.9 133.14 195.16 140.7 192.71 143.86 C191.76 145.08 191.43 146.57 191.86 147.29 C192.29 148 193.76 148.41 195.29 148.14 Z',
    },
    {
      id: 'midleg-femur',
      rank: 'structure',
      fill: 'pigment-deep',
      d: 'M20.31 146.07 C28.88 146.22 48.13 134.46 61.89 129.17 C75.24 124.03 96.03 119.8 101.65 114.72 C103.95 112.64 105.27 109.92 104.72 108.35 C104.17 106.78 101.44 105.47 98.35 105.28 C90.77 104.81 71.68 114.14 58.11 118.83 C44.14 123.67 22 128.1 15.69 133.93 C12.83 136.56 11.15 140.29 11.93 142.31 C12.7 144.34 16.44 146.01 20.31 146.07 Z',
    },
    {
      id: 'midleg-tibia',
      rank: 'structure',
      fill: 'pigment-deep',
      d: 'M102.7 113.6 C109.48 111.82 124.1 97.39 134.45 89.16 C144.59 81.1 161.2 70.25 164.19 64.73 C165.26 62.76 165.46 60.72 164.73 59.81 C164 58.9 161.98 58.66 159.81 59.27 C153.79 60.97 139.86 75.06 129.55 82.84 C119.03 90.77 100.9 100.4 97.3 106.4 C95.86 108.8 95.5 111.5 96.4 112.7 C97.3 113.9 100 114.31 102.7 113.6 Z',
    },
    {
      id: 'midleg-tarsus',
      rank: 'detail',
      fill: 'pigment-deep',
      d: 'M164.12 64.12 C167.98 62.47 178.29 51.45 179.77 47.77 C180.35 46.31 180.36 44.82 179.77 44.23 C179.18 43.64 177.69 43.65 176.23 44.23 C172.55 45.71 161.53 56.02 159.88 59.88 C159.17 61.55 159.17 63.41 159.88 64.12 C160.59 64.83 162.45 64.83 164.12 64.12 Z',
    },
    {
      id: 'midleg-tarsus',
      rank: 'detail',
      fill: 'pigment-deep',
      d: 'M181.77 43.77 C185.64 42.08 197.77 28.36 199.06 25.06 C199.43 24.11 199.41 23.29 199.06 22.94 C198.71 22.59 197.89 22.57 196.94 22.94 C193.64 24.23 179.92 36.36 178.23 40.23 C177.6 41.67 177.64 43.18 178.23 43.77 C178.82 44.36 180.33 44.4 181.77 43.77 Z',
    },
    {
      id: 'foreleg-femur',
      rank: 'structure',
      fill: 'pigment-deep',
      d: 'M19.9 93.2 C28.79 90.83 46.4 72.21 59.26 62.43 C71.38 53.21 90.86 42.73 94.93 36.05 C96.55 33.39 97.03 30.42 96.05 29.07 C95.08 27.72 92.11 27.24 89.07 27.95 C81.45 29.71 65.17 44.72 52.74 53.57 C39.55 62.96 16.87 74.92 12.1 82.8 C10.06 86.18 9.5 90.17 10.8 91.9 C12.1 93.63 16.09 94.22 19.9 93.2 Z',
    },
    {
      id: 'foreleg-tibia',
      rank: 'structure',
      fill: 'pigment-deep',
      d: 'M95.18 35.18 C101.61 32.47 114.22 16.38 122.93 6.72 C131.34 -2.6 144.79 -15.89 146.66 -21.72 C147.34 -23.85 147.16 -25.9 146.28 -26.66 C145.39 -27.42 143.34 -27.28 141.34 -26.28 C135.89 -23.56 125.65 -7.74 117.07 1.28 C108.17 10.63 91.52 22.42 88.82 28.82 C87.73 31.39 87.76 34.12 88.82 35.18 C89.88 36.24 92.61 36.27 95.18 35.18 Z',
    },
    {
      id: 'foreleg-tarsus',
      rank: 'detail',
      fill: 'pigment-deep',
      d: 'M146.46 -22.28 C150.15 -24.69 159.19 -38.49 160.05 -42.57 C160.37 -44.12 160.12 -45.57 159.43 -46.05 C158.75 -46.53 157.3 -46.27 155.95 -45.43 C152.42 -43.23 142.54 -30.01 141.54 -25.72 C141.13 -23.93 141.46 -22.12 142.28 -21.54 C143.1 -20.97 144.92 -21.28 146.46 -22.28 Z',
    },
    {
      id: 'foreleg-tarsus',
      rank: 'detail',
      fill: 'pigment-deep',
      d: 'M162.08 -46.61 C165.84 -49.22 176.57 -67.41 177.25 -71.17 C177.43 -72.19 177.25 -72.97 176.83 -73.25 C176.42 -73.53 175.62 -73.39 174.75 -72.83 C171.54 -70.76 158.89 -53.86 157.92 -49.39 C157.58 -47.82 157.92 -46.38 158.61 -45.92 C159.31 -45.46 160.77 -45.7 162.08 -46.61 Z',
    },
    // The hind wing. Narrow, stalked at the base and rounded at the tip — a
    // lens rather than the hawker’s triangle, and the shape that separates the
    // damselflies from the dragonflies at a glance.
    //
    // `membrane`, so what is behind it shows through. Four of these overlap each
    // other and the abdomen, and the point of a damselfly’s wing is that it is
    // a window.
    {
      id: 'hindwing',
      rank: 'outline',
      fill: 'pigment',
      d: 'M22 252 C29.05 239.04 77.51 231.88 110 224 C148.82 214.59 195.8 208.58 240 202 C285.74 195.19 335.12 189.5 380 184 C421.53 178.91 464.3 174.37 500 170 C528.8 166.47 556.99 159.6 578 160 C592.31 160.27 609.9 159.34 614 166 C617.93 172.38 612.24 189.99 604 198 C592.4 209.27 563.39 210.43 540 216 C512.23 222.61 480.31 227.72 448 234 C412.04 240.99 373.11 248.56 334 256 C292.58 263.88 247.58 271.8 206 280 C166.34 287.82 122.11 307.98 90 304 C65.52 300.97 37.75 285.74 28 274 C22.39 267.24 18.5 258.44 22 252 Z',
      opacity: 'membrane',
    },
    // The venation, as four strokes laid from just inside the leading edge to
    // just inside the trailing one.
    //
    // Five, closer together, was the first pass, and at plate size they merged
    // into one dark line down the middle of the wing — which is worse than no
    // venation at all, because a wing with a spine through it is not a wing.
    // Lucas draws several hundred cells; four is what survives at eighty pixels.
    {
      id: 'wing-vein',
      rank: 'detail',
      fill: 'none',
      d: 'M70 248 C70 248 219.57 224.61 300 212 C388.75 198.08 580 168 580 168',
      clipTo: 'hindwing',
    },
    {
      id: 'wing-vein',
      rank: 'detail',
      fill: 'none',
      d: 'M70 260.67 C70 260.67 219.7 241.51 300 228.67 C388.89 214.45 580 178 580 178',
      clipTo: 'hindwing',
    },
    {
      id: 'wing-vein',
      rank: 'detail',
      fill: 'none',
      d: 'M70 273.33 C70 273.33 219.84 258.4 300 245.33 C389.03 230.82 580 188 580 188',
      clipTo: 'hindwing',
    },
    {
      id: 'wing-vein',
      rank: 'detail',
      fill: 'none',
      d: 'M70 286 C70 286 219.98 275.27 300 262 C389.17 247.21 580 198 580 198',
      clipTo: 'hindwing',
    },
    // The pterostigma: the one opaque cell near the leading edge, three
    // quarters of the way out. Small, and drawn because it is the only mark on
    // an otherwise clear wing.
    {
      id: 'wing-marking',
      rank: 'structure',
      fill: 'pigment-deep',
      d: 'M559.77 182.66 C560.46 187.58 550.38 193.07 537.25 194.91 C524.13 196.76 512.93 194.26 512.23 189.34 C511.54 184.42 521.62 178.93 534.75 177.09 C547.87 175.24 559.07 177.74 559.77 182.66 Z',
      clipTo: 'hindwing',
    },
    // The fore wing, and where it is attached matters as much as its shape.
    //
    // Both wings spring from the thorax — 76 to 258 in plate space — and hold
    // out to the side, angled a little towards the head. The first pass had
    // them leaving the animal at y = 470, which is a third of the way down the
    // abdomen, and it read as a dragonfly with its wings on backwards. Lucas
    // draws all four bases inside the length of the synthorax and that is where
    // they are now.
    {
      id: 'forewing',
      rank: 'outline',
      fill: 'pigment',
      d: 'M22 186 C29.05 173.04 77.51 165.88 110 158 C148.82 148.59 195.8 142.58 240 136 C285.74 129.19 335.12 123.5 380 118 C421.53 112.91 464.3 108.37 500 104 C528.8 100.47 556.99 93.6 578 94 C592.31 94.27 609.9 93.34 614 100 C617.93 106.38 612.24 123.99 604 132 C592.4 143.27 563.39 144.43 540 150 C512.23 156.61 480.31 161.72 448 168 C412.04 174.99 373.11 182.56 334 190 C292.58 197.88 247.58 205.8 206 214 C166.34 221.82 122.11 241.98 90 238 C65.52 234.97 37.75 219.74 28 208 C22.39 201.24 18.5 192.44 22 186 Z',
      opacity: 'membrane',
    },
    {
      id: 'wing-vein',
      rank: 'detail',
      fill: 'none',
      d: 'M70 182 C70 182 219.57 158.61 300 146 C388.75 132.08 580 102 580 102',
      clipTo: 'forewing',
    },
    {
      id: 'wing-vein',
      rank: 'detail',
      fill: 'none',
      d: 'M70 194.67 C70 194.67 219.7 175.51 300 162.67 C388.89 148.45 580 112 580 112',
      clipTo: 'forewing',
    },
    {
      id: 'wing-vein',
      rank: 'detail',
      fill: 'none',
      d: 'M70 207.33 C70 207.33 219.84 192.4 300 179.33 C389.03 164.82 580 122 580 122',
      clipTo: 'forewing',
    },
    {
      id: 'wing-vein',
      rank: 'detail',
      fill: 'none',
      d: 'M70 220 C70 220 219.98 209.27 300 196 C389.17 181.21 580 132 580 132',
      clipTo: 'forewing',
    },
    {
      id: 'wing-marking',
      rank: 'structure',
      fill: 'pigment-deep',
      d: 'M559.77 116.66 C560.46 121.58 550.38 127.07 537.25 128.91 C524.13 130.76 512.93 128.26 512.23 123.34 C511.54 118.42 521.62 112.93 534.75 111.09 C547.87 109.24 559.07 111.74 559.77 116.66 Z',
      clipTo: 'forewing',
    },
    // The abdomen: ten segments and almost nothing across them. Thirty units
    // wide against the hawker's hundred and sixty, and the slight swelling
    // towards the tip is the eighth and ninth segments, which is where the blue
    // is.
    {
      id: 'abdomen',
      rank: 'outline',
      fill: 'pigment',
      d: 'M0 250 C4 250 9.1 252.74 12 258 C18.92 270.56 13.59 306.05 14 340 C14.68 395.6 14.17 486.67 14 560 C13.83 633.33 12.62 717.7 13 780 C13.28 826.02 14.02 870.72 15 900 C15.56 916.91 17.04 927.02 17 940 C16.97 952.32 19.42 968.27 15 976 C11.88 981.47 5 986 0 986 C-5 986 -11.88 981.47 -15 976 C-19.42 968.27 -16.97 952.32 -17 940 C-17.04 927.02 -15.56 916.91 -15 900 C-14.02 870.72 -13.28 826.02 -13 780 C-12.62 717.7 -13.83 633.33 -14 560 C-14.17 486.67 -14.68 395.6 -14 340 C-13.59 306.05 -18.92 270.56 -12 258 C-9.1 252.74 -4 250 0 250 Z',
      mirror: false,
    },
    // The segment rings, as eight strokes each crossing the axis.
    //
    // This is the case the fan validator allows on the midline: both guides are
    // centred on x = 0, so every stroke straddles it and `mirror: false` is
    // true of each one. Authored on the right half instead, they would be eight
    // half-rings sitting off the axis and the validator would say so.
    {
      id: 'abdomen-segment',
      rank: 'structure',
      fill: 'none',
      d: 'M-11 320 C-11 320 -3.67 320 0 320 C3.67 320 11 320 11 320',
      mirror: false,
      clipTo: 'abdomen',
    },
    {
      id: 'abdomen-segment',
      rank: 'structure',
      fill: 'none',
      d: 'M-11 408.57 C-11 408.57 -3.67 408.57 0 408.57 C3.67 408.57 11 408.57 11 408.57',
      mirror: false,
      clipTo: 'abdomen',
    },
    {
      id: 'abdomen-segment',
      rank: 'structure',
      fill: 'none',
      d: 'M-11 497.14 C-11 497.14 -3.67 497.14 0 497.14 C3.67 497.14 11 497.14 11 497.14',
      mirror: false,
      clipTo: 'abdomen',
    },
    {
      id: 'abdomen-segment',
      rank: 'structure',
      fill: 'none',
      d: 'M-11 585.71 C-11 585.71 -3.67 585.71 0 585.71 C3.67 585.71 11 585.71 11 585.71',
      mirror: false,
      clipTo: 'abdomen',
    },
    {
      id: 'abdomen-segment',
      rank: 'structure',
      fill: 'none',
      d: 'M-11 674.29 C-11 674.29 -3.67 674.29 0 674.29 C3.67 674.29 11 674.29 11 674.29',
      mirror: false,
      clipTo: 'abdomen',
    },
    {
      id: 'abdomen-segment',
      rank: 'structure',
      fill: 'none',
      d: 'M-11 762.86 C-11 762.86 -3.67 762.86 0 762.86 C3.67 762.86 11 762.86 11 762.86',
      mirror: false,
      clipTo: 'abdomen',
    },
    {
      id: 'abdomen-segment',
      rank: 'structure',
      fill: 'none',
      d: 'M-11 851.43 C-11 851.43 -3.67 851.43 0 851.43 C3.67 851.43 11 851.43 11 851.43',
      mirror: false,
      clipTo: 'abdomen',
    },
    {
      id: 'abdomen-segment',
      rank: 'structure',
      fill: 'none',
      d: 'M-11 940 C-11 940 -3.67 940 0 940 C3.67 940 11 940 11 940',
      mirror: false,
      clipTo: 'abdomen',
    },
    // The tail-light. Segment eight, and only segment eight: bare paper on the
    // axis, clipped to the abdomen so it cannot reach past the animal's own
    // edge.
    {
      id: 'marking',
      rank: 'structure',
      fill: 'surface',
      d: 'M-9 834 C-11.79 840.73 -9 854.17 -9 864 C-9 873.49 -11.66 885.58 -9 892 C-7.21 896.33 -3 901 0 901 C3 901 7.21 896.33 9 892 C11.66 885.58 9 873.49 9 864 C9 854.17 11.79 840.73 9 834 C7.18 829.61 3 825 0 825 C-3 825 -7.18 829.61 -9 834 Z',
      mirror: false,
      clipTo: 'abdomen',
    },
    // The claspers at the tip of the abdomen, which is how a male damselfly
    // holds a female behind the head. Small, and the reason this plate commits
    // to a sex.
    {
      id: 'cercus',
      rank: 'detail',
      fill: 'pigment-deep',
      d: 'M3.65 983.16 C3.11 989 11.18 1009.04 14.07 1012.52 C14.94 1013.56 15.87 1014.1 16.52 1013.93 C17.16 1013.76 17.7 1012.82 17.93 1011.48 C18.71 1007.04 15.72 985.64 12.35 980.84 C10.82 978.67 8.29 977.27 6.84 977.65 C5.39 978.04 3.9 980.52 3.65 983.16 Z',
    },
    // The synthorax: the box the four wings and the six legs all hang off, and
    // a fifth of the animal's length.
    {
      id: 'thorax',
      rank: 'outline',
      fill: 'pigment',
      d: 'M0 76 C8.67 76 20 74.53 26 80 C33.51 86.85 33.93 105.2 36 120 C38.5 137.86 38.82 160.94 38 180 C37.25 197.46 36.61 217.1 32 230 C28.68 239.28 23.94 247.36 18 252 C12.93 255.96 6 258 0 258 C-6 258 -12.93 255.96 -18 252 C-23.94 247.36 -28.68 239.28 -32 230 C-36.61 217.1 -37.25 197.46 -38 180 C-38.82 160.94 -38.5 137.86 -36 120 C-33.93 105.2 -33.51 86.85 -26 80 C-20 74.53 -8.67 76 0 76 Z',
      mirror: false,
    },
    // The antehumeral stripes, which is what `markings: 'stripes'` means on
    // this record: two pale lines running head to tail down the thorax, with
    // the darker humeral stripe outside each. Clipped to the thorax, so a
    // stripe cannot end up beside the animal.
    {
      id: 'marking',
      rank: 'structure',
      fill: 'surface',
      d: 'M9.5 96.05 C6.09 104.61 9.99 144.41 10.5 168.08 C11 191.08 8.85 227.98 12.5 236.1 C13.49 238.29 14.94 239.53 16.1 239.5 C17.27 239.46 18.65 238.14 19.5 235.9 C22.66 227.58 18 190.91 17.5 167.92 C16.99 144.28 20.14 104.41 16.5 95.95 C15.54 93.73 14.12 92.48 12.95 92.5 C11.78 92.52 10.39 93.8 9.5 96.05 Z',
      clipTo: 'thorax',
    },
    {
      id: 'marking',
      rank: 'detail',
      fill: 'pigment-deep',
      d: 'M22.5 104.04 C19.79 110.89 23.17 145.37 23.5 166.04 C23.83 186.71 21.57 221.29 24.5 228.04 C25.2 229.65 26.21 230.51 27.04 230.5 C27.87 230.49 28.85 229.59 29.5 227.96 C32.21 221.11 28.83 186.63 28.5 165.96 C28.17 145.29 30.43 110.71 27.5 103.96 C26.8 102.35 25.79 101.49 24.96 101.5 C24.13 101.51 23.15 102.41 22.5 104.04 Z',
      clipTo: 'thorax',
    },
    // The head. Transverse and mostly eye — the central part is narrow and the
    // two compound eyes are the whole of the width, which is why the head
    // outline here is narrower than the animal is across.
    {
      id: 'head',
      rank: 'outline',
      fill: 'pigment-deep',
      d: 'M0 -4 C7.33 -4 17 -4.44 22 0 C27.51 4.89 28.94 16.92 30 26 C31.11 35.54 31 47.91 28 56 C25.55 62.6 20.98 68.69 16 72 C11.48 75 5.33 76 0 76 C-5.33 76 -11.48 75 -16 72 C-20.98 68.69 -25.55 62.6 -28 56 C-31 47.91 -31.11 35.54 -30 26 C-28.94 16.92 -27.51 4.89 -22 0 C-17 -4.44 -7.33 -4 0 -4 Z',
      mirror: false,
    },
    // A compound eye. Set well apart, which is the character that separates a
    // damselfly's head from a hawker's — a hawker's eyes meet on top of its
    // head and these do not come close.
    {
      id: 'compound-eye',
      rank: 'structure',
      fill: 'pigment',
      d: 'M58 24 C58 36.15 49.05 46 38 46 C26.95 46 18 36.15 18 24 C18 11.85 26.95 2 38 2 C49.05 2 58 11.85 58 24 Z',
    },
    {
      id: 'ocellus',
      rank: 'detail',
      fill: 'ink',
      d: 'M18 6 C18 8.21 15.76 10 13 10 C10.24 10 8 8.21 8 6 C8 3.79 10.24 2 13 2 C15.76 2 18 3.79 18 6 Z',
    },
    // The antenna: two short bristles, which is all an Odonata has and the
    // reason `REQUIRED_PARTS` does not ask this order for them. Drawn anyway,
    // because the record says `setaceous` and this is the drawing of that word.
    {
      id: 'antenna',
      rank: 'detail',
      fill: 'pigment-deep',
      d: 'M19.32 -0.89 C22.76 -5.12 27.84 -27.48 27.42 -31.53 C27.32 -32.57 26.95 -33.26 26.47 -33.42 C26 -33.58 25.29 -33.25 24.58 -32.47 C21.82 -29.49 12.46 -8.56 12.68 -3.11 C12.76 -0.95 13.79 0.95 14.89 1.32 C16 1.69 17.96 0.78 19.32 -0.89 Z',
    },
  ],
};
