// Generated from ../landmarks/palomena-prasina.json by `npm run plate:build`.
//
// Do not edit this file. Edit the landmarks and build again; `npm run
// plate:verify` fails the check if the two drift apart.

import type { SpeciesPlate } from '@/lib/plate';

/**
 * *Palomena prasina*, dorsal — the green shield bug.
 *
 * Traced from figure 1 of Robert Morgan's plate 3 for Edward Saunders's *The
 * Hemiptera Heteroptera of the British Islands* (1892), where it is captioned
 * under its old name *Pentatoma prasina*;
 * `references/palomena-prasina.jpg` is the plate and `references/SOURCES.md`
 * has the provenance.
 *
 * ## The first true bug in the collection
 *
 * Which is why the outline matters more here than the pattern. A shield bug is
 * recognised as a shape before it is recognised as a species: a broad pentagon
 * with the widest point behind the middle, a pronotum whose lateral angles are
 * rounded rather than spined, and a scutellum — the triangle between the folded
 * wings — running a third of the way down the back. `REQUIRED_PARTS.hemiptera`
 * asks for that scutellum for exactly this reason.
 *
 * ## Half a wing is a window and half is not
 *
 * A hemelytron is hard at the base and membranous at the tip, which is what the
 * suborder is named for. The membranes cross over each other on the midline and
 * reach past the end of the abdomen, and in the lithograph they are the one pale
 * thing on a green animal. They are drawn as a `surface` fill — bare paper —
 * rather than with `opacity: 'membrane'`: what is behind them here is the other
 * wing and the tip of the abdomen, and the reference does not show either
 * through. The dragonfly is the plate that needs a real window.
 *
 * ## No hindwings
 *
 * They are folded underneath and nothing of them shows from above, so none are
 * drawn and `REQUIRED_PARTS.hemiptera` does not ask for them.
 *
 * ## Plate space
 *
 * y = 0 at the front of the head, y = 1000 at the tip of the abdomen — which for
 * this animal is the tip of the folded wing membranes, because they overhang it.
 * The antennae reach to about y = -250 and the legs out to x = 455, both well
 * outside the body's own box, which is what `plateViewBox` measures for.
 */
export const PALOMENA_PRASINA_PLATE: SpeciesPlate = {
  species: 'palomena-prasina',
  order: 'hemiptera',
  sex: 'unsexed',
  hallmark:
    'the shield outline, with a scutellum a third of its length and pale wing tips crossed over the abdomen',
  reference: {
    title:
      'Pentatoma prasina, from The Hemiptera Heteroptera of the British Islands, plate 3, fig. 1',
    artist: 'Robert Morgan',
    year: 1892,
    source:
      'https://commons.wikimedia.org/wiki/File:SaundersHemipteraHeteropteraBritishIslandsPlate3.jpg',
    licence: 'Public domain (PD-old-70-1923)',
  },
  parts: [
    // Legs first, so they pass under the body.
    //
    // Femora and tibiae are capsules measured across at about six and four per
    // cent of the width across the wings, which is the proportion CLAUDE.md
    // records and the reference bears out: a shield bug's legs are slender and
    // the animal reads as moulded rather than engraved when they are not.
    {
      id: 'hindleg-femur',
      rank: 'structure',
      fill: 'pigment-deep',
      d: 'M235.92 655.54 C246.29 668.93 280.03 679.87 301.42 692.09 C322.2 703.97 347.5 725.49 362.51 727.83 C370.45 729.06 379.33 727.43 381.83 723.49 C384.32 719.55 382.01 710.83 377.49 704.17 C368.92 691.53 338.83 677.01 318.58 663.91 C297.73 650.42 270.93 626.94 254.08 624.46 C244.31 623.02 232.49 625.74 229.46 630.92 C226.43 636.1 229.87 647.74 235.92 655.54 Z',
    },
    {
      id: 'hindleg-tibia',
      rank: 'structure',
      fill: 'pigment-deep',
      d: 'M358.13 714.27 C349.27 729.4 350.57 778.8 345.65 810.21 C340.88 840.76 326.07 885.19 329.17 900.23 C330.33 905.85 333.29 910.24 336.23 910.83 C339.18 911.41 343.6 908.5 346.83 903.77 C355.51 891.02 360.57 844.35 366.35 813.79 C372.29 782.37 386.06 734.82 381.87 717.73 C380.13 710.59 375.69 704.7 371.73 704.13 C367.77 703.55 361.84 707.93 358.13 714.27 Z',
    },
    {
      id: 'hindleg-tarsus',
      rank: 'detail',
      fill: 'pigment-deep',
      d: 'M330.56 901.07 C325.97 909.34 323.05 940.46 325.55 949.19 C326.64 953 329.04 956.18 331.19 956.45 C333.34 956.72 336.46 954.23 338.45 950.81 C343.02 942.96 347.86 912.08 345.44 902.93 C344.31 898.65 341.41 894.87 338.93 894.56 C336.45 894.25 332.71 897.2 330.56 901.07 Z',
    },
    {
      id: 'hindleg-tarsus',
      rank: 'detail',
      fill: 'pigment-deep',
      d: 'M323.53 957.41 C319.67 964.97 318.03 993.81 320.52 1001.5 C321.57 1004.73 323.68 1007.31 325.5 1007.48 C327.33 1007.64 329.87 1005.48 331.48 1002.5 C335.31 995.39 338.91 966.72 336.47 958.59 C335.36 954.88 332.75 951.72 330.59 951.53 C328.43 951.33 325.29 953.96 323.53 957.41 Z',
    },
    {
      id: 'hindleg-tarsus',
      rank: 'detail',
      fill: 'ink',
      d: 'M319.52 1007.49 C316.74 1013.28 317.23 1034.66 319.01 1039.72 C319.66 1041.56 320.72 1042.89 321.72 1042.99 C322.72 1043.08 324.01 1041.96 324.99 1040.28 C327.68 1035.64 332.13 1014.73 330.48 1008.51 C329.66 1005.46 327.34 1002.7 325.51 1002.52 C323.69 1002.35 320.89 1004.64 319.52 1007.49 Z',
    },
    {
      id: 'midleg-femur',
      rank: 'structure',
      fill: 'pigment-deep',
      d: 'M260.07 437.27 C277.4 438.97 310.22 421.62 334.59 413.85 C358.11 406.35 391.89 401.29 403.85 391.46 C410.08 386.34 414.74 378.64 413.46 374.15 C412.18 369.67 404.16 365.6 396.15 364.54 C380.8 362.51 349.34 375.91 325.41 382.15 C300.62 388.61 263.61 391.92 249.93 402.73 C242.13 408.89 236.04 419.31 237.73 425.07 C239.42 430.82 250.17 436.3 260.07 437.27 Z',
    },
    {
      id: 'midleg-tibia',
      rank: 'structure',
      fill: 'pigment-deep',
      d: 'M388.37 380.97 C386.02 398.32 406.58 442.95 413.73 474.18 C420.81 505.14 422.65 554.27 431.13 567.51 C434.23 572.36 438.55 575.38 441.51 574.87 C444.47 574.37 447.55 570.1 448.87 564.49 C452.51 549.1 440.44 501.26 434.27 469.82 C428.05 438.11 422.08 389.21 411.63 375.03 C407.27 369.11 400.91 365.38 397.03 366.37 C393.16 367.36 389.36 373.69 388.37 380.97 Z',
    },
    {
      id: 'midleg-tarsus',
      rank: 'detail',
      fill: 'pigment-deep',
      d: 'M432.56 566.93 C430.14 576.08 434.98 606.96 439.55 614.81 C441.54 618.23 444.66 620.72 446.81 620.45 C448.96 620.18 451.36 617 452.45 613.19 C454.95 604.46 452.03 573.34 447.44 565.07 C445.29 561.2 441.55 558.25 439.07 558.56 C436.59 558.87 433.69 562.65 432.56 566.93 Z',
    },
    {
      id: 'midleg-tarsus',
      rank: 'detail',
      fill: 'pigment-deep',
      d: 'M441.53 622.59 C439.09 630.72 442.69 659.39 446.52 666.5 C448.13 669.48 450.67 671.64 452.5 671.48 C454.32 671.31 456.43 668.73 457.48 665.5 C459.97 657.81 458.33 628.97 454.47 621.41 C452.71 617.96 449.57 615.33 447.41 615.53 C445.25 615.72 442.64 618.88 441.53 622.59 Z',
    },
    {
      id: 'midleg-tarsus',
      rank: 'detail',
      fill: 'ink',
      d: 'M447.51 672.34 C445.67 678.49 449.46 699.47 452.01 704.19 C452.93 705.9 454.19 707.06 455.19 706.99 C456.19 706.93 457.29 705.63 457.99 703.81 C459.93 698.82 461.08 677.53 458.49 671.66 C457.21 668.77 454.49 666.4 452.66 666.51 C450.83 666.63 448.42 669.32 447.51 672.34 Z',
    },
    {
      id: 'foreleg-femur',
      rank: 'structure',
      fill: 'pigment-deep',
      d: 'M161.24 232.06 C180.53 226.3 212.12 191.75 235.76 170.51 C258.82 149.79 294.19 122.77 301.51 106.28 C304.91 98.62 305.45 89.92 302.28 86.49 C299.11 83.07 290.37 82.94 282.49 85.72 C265.63 91.7 237.86 126.03 214.24 145.49 C190 165.46 148.52 186.54 138.76 203.94 C133.71 212.93 132.2 224.56 135.94 229.24 C139.69 233.93 151.35 235.01 161.24 232.06 Z',
    },
    {
      id: 'foreleg-tibia',
      rank: 'structure',
      fill: 'pigment-deep',
      d: 'M301.7 103.06 C315.07 94.7 334.69 58.71 348.84 35.66 C362.67 13.13 384.36 -19.75 385.86 -33.61 C386.46 -39.19 385.01 -44.39 382.39 -45.86 C379.77 -47.32 374.57 -45.82 370.14 -42.39 C359.24 -33.94 345.59 2.69 331.16 24.34 C316.38 46.5 286.09 73.81 282.3 88.94 C280.56 95.87 281.71 103.35 284.94 105.7 C288.18 108.06 295.63 106.85 301.7 103.06 Z',
    },
    {
      id: 'foreleg-tarsus',
      rank: 'detail',
      fill: 'pigment-deep',
      d: 'M384.83 -34.9 C391.67 -41.42 403.7 -70.23 403.92 -79.31 C404.01 -83.27 402.66 -87.02 400.69 -87.92 C398.72 -88.81 395 -87.36 392.08 -84.69 C385.38 -78.56 371.59 -50.55 371.17 -41.1 C370.98 -36.68 372.62 -32.21 374.9 -31.17 C377.17 -30.14 381.62 -31.84 384.83 -34.9 Z',
    },
    {
      id: 'foreleg-tarsus',
      rank: 'detail',
      fill: 'pigment-deep',
      d: 'M406.87 -86.21 C413.11 -91.98 424.65 -118.55 424.97 -126.64 C425.1 -130.03 424.02 -133.18 422.36 -133.97 C420.7 -134.75 417.57 -133.6 415.03 -131.36 C408.97 -126 395.66 -100.27 395.13 -91.79 C394.89 -87.92 396.25 -84.06 398.21 -83.13 C400.17 -82.2 404.03 -83.58 406.87 -86.21 Z',
    },
    {
      id: 'foreleg-tarsus',
      rank: 'detail',
      fill: 'ink',
      d: 'M426.95 -132.61 C431.59 -137.08 438.6 -157.32 438.7 -162.7 C438.74 -164.64 438.2 -166.27 437.3 -166.7 C436.4 -167.14 434.8 -166.54 433.3 -165.3 C429.15 -161.89 417.66 -143.8 417.05 -137.39 C416.74 -134.25 417.96 -130.84 419.61 -130.05 C421.26 -129.25 424.68 -130.42 426.95 -132.61 Z',
    },
    // The abdomen, which shows only as a rim.
    //
    // Almost all of it is under the wings; what a reader sees is the connexivum,
    // the strip of abdominal margin standing out beyond them. Drawn whole
    // anyway, because the wings are placed against it and a rim authored as a
    // rim would have to be re-measured the first time a wing moved.
    {
      id: 'abdomen',
      rank: 'outline',
      fill: 'pigment',
      d: 'M0 236 C95.67 236 242.87 205.67 287 245 C316.74 271.5 304.21 333.33 306 374 C307.59 410.18 298.62 444.58 300 477 C301.25 506.23 309.26 536.35 312 560 C314.03 577.55 316.77 590.11 316 606 C315.16 623.33 309.74 642.39 306 660 C302.38 677.04 299.21 693.43 294 710 C288.62 727.1 280.94 743.96 274 761 C266.95 778.3 263.13 796.99 252 813 C239.48 831.01 217.56 847.12 200 862 C183.53 875.95 167.32 887.94 150 900 C132.35 912.29 116.76 926.13 95 935 C68.44 945.83 31.67 955 0 955 C-31.67 955 -68.44 945.83 -95 935 C-116.76 926.13 -132.35 912.29 -150 900 C-167.32 887.94 -183.53 875.95 -200 862 C-217.56 847.12 -239.48 831.01 -252 813 C-263.13 796.99 -266.95 778.3 -274 761 C-280.94 743.96 -288.62 727.1 -294 710 C-299.21 693.43 -302.38 677.04 -306 660 C-309.74 642.39 -315.16 623.33 -316 606 C-316.77 590.11 -314.03 577.55 -312 560 C-309.26 536.35 -301.25 506.23 -300 477 C-298.62 444.58 -307.59 410.18 -306 374 C-304.21 333.33 -316.74 271.5 -287 245 C-242.87 205.67 -95.67 236 0 236 Z',
      mirror: false,
    },
    // The connexivum, as five ticks rather than five bands.
    //
    // The lithograph alternates pale and dark along the abdominal margin. At
    // eighty pixels that is a dotted line and at six hundred it is five
    // segments; either way it is the segment boundaries that carry it, so the
    // boundaries are what is drawn.
    {
      id: 'abdomen-segment',
      rank: 'detail',
      fill: 'none',
      d: 'M304 392 C304 392 274 386 274 386',
    },
    {
      id: 'abdomen-segment',
      rank: 'detail',
      fill: 'none',
      d: 'M281.5 503.5 C281.5 503.5 253 494.5 253 494.5',
    },
    {
      id: 'abdomen-segment',
      rank: 'detail',
      fill: 'none',
      d: 'M259 615 C259 615 232 603 232 603',
    },
    {
      id: 'abdomen-segment',
      rank: 'detail',
      fill: 'none',
      d: 'M236.5 726.5 C236.5 726.5 211 711.5 211 711.5',
    },
    {
      id: 'abdomen-segment',
      rank: 'detail',
      fill: 'none',
      d: 'M214 838 C214 838 190 820 190 820',
    },
    // One hemelytron: hardened at the base, membranous at the tip.
    //
    // The inner edge runs down the side of the scutellum, then along the midline
    // where the two wings cross over each other. A landmark on the midline gets
    // a vertical tangent from the builder, so the seam between a wing and its
    // own reflection is a line rather than a pinch.
    {
      id: 'forewing',
      rank: 'outline',
      fill: 'pigment',
      d: 'M255 268 C265.08 270.28 268.17 341.92 272 380 C275.95 419.21 276.28 461.82 278 500 C279.57 534.85 283.67 570.31 282 600 C280.64 624.06 275.97 644.83 272 665 C268.49 682.84 265.09 698.08 260 715 C254.57 733.05 247.45 752.28 240 770 C232.74 787.25 225.82 804.18 216 820 C205.92 836.23 192.69 851.31 180 866 C167.35 880.64 153.99 894.67 140 908 C125.99 921.34 111.78 934.45 96 946 C79.83 957.84 60.96 969.39 44 978 C29.04 985.6 0 1002.65 0 996 C0 982.15 0 835.82 0 790 C0 760.59 41.17 754.77 60 730 C83.49 699.09 106.47 655.32 125 615 C143.95 573.75 159.23 527.34 172 485 C183.81 445.82 188.41 402.83 200 370 C209.23 343.84 221.5 320.45 232 302 C239.76 288.36 248.93 266.63 255 268 Z',
    },
    // The claval suture — the fold between the two hard parts of the wing.
    // One line, because at plate size it is one line.
    {
      id: 'wing-vein',
      rank: 'structure',
      fill: 'none',
      d: 'M216 356 C216 356 186.39 452.53 170 500 C153.71 547.19 135.2 595.02 118 640 C101.88 682.15 70 762 70 762',
      clipTo: 'forewing',
    },
    // The punctation, as hatching.
    //
    // The corium is densely pitted and the lithograph stipples it. Stipple is
    // not in this project's vocabulary — three line weights are — so it becomes
    // a fan of strokes running the length of the wing, which is what the
    // engraving convention does with a pitted surface.
    {
      id: 'hatching',
      rank: 'detail',
      fill: 'none',
      d: 'M196 430 C196 430 169.67 517.24 152 560 C133.84 603.94 88 690 88 690',
      clipTo: 'forewing',
    },
    {
      id: 'hatching',
      rank: 'detail',
      fill: 'none',
      d: 'M219.33 430 C219.33 430 203.7 517.09 191.33 560 C178.72 603.77 144 690 144 690',
      clipTo: 'forewing',
    },
    {
      id: 'hatching',
      rank: 'detail',
      fill: 'none',
      d: 'M242.67 430 C242.67 430 237.7 516.91 230.67 560 C223.55 603.58 200 690 200 690',
      clipTo: 'forewing',
    },
    {
      id: 'hatching',
      rank: 'detail',
      fill: 'none',
      d: 'M266 430 C266 430 271.66 516.72 270 560 C268.34 603.39 256 690 256 690',
      clipTo: 'forewing',
    },
    // The membrane: bare paper, not a window.
    //
    // `opacity: 'membrane'` would be the wrong tool. What is behind this wing
    // tip is the other wing tip and the end of the abdomen, and the reference
    // shows neither through it — it is opaque and pale. The dragonfly is the
    // plate where a wing has to be transparent.
    {
      id: 'wing-marking',
      rank: 'structure',
      fill: 'surface',
      d: 'M0 806 C0 794.2 51.87 814.99 74 824 C94.09 832.18 115.3 843.59 128 856 C137.85 865.62 149 877.71 148 888 C146.92 899.1 128.42 909.93 118 920 C107.74 929.91 97.86 939.55 86 948 C73.35 957.01 58.4 964.98 44 972 C29.73 978.96 0 996.53 0 990 C0 977.16 0 824.34 0 806 Z',
      clipTo: 'forewing',
    },
    // The scutellum, which is the order seen from above.
    //
    // A third of the length of the animal, with slightly hollowed sides and a
    // blunt tip. Drawn once, on the axis: it straddles the midline and is
    // symmetric in itself, so reflecting it would put a second copy a hair off
    // the first and show as a doubled line down the middle of the back.
    {
      id: 'scutellum',
      rank: 'outline',
      fill: 'pigment',
      d: 'M0 352 C66.67 352 178.45 335.93 200 366 C216.53 389.06 182.56 441.11 170 480 C156.35 522.28 138.54 568.77 120 610 C102.36 649.24 85.69 695.94 62 722 C43.88 741.93 20.67 762 0 762 C-20.67 762 -43.88 741.93 -62 722 C-85.69 695.94 -102.36 649.24 -120 610 C-138.54 568.77 -156.35 522.28 -170 480 C-182.56 441.11 -216.53 389.06 -200 366 C-178.45 335.93 -66.67 352 0 352 Z',
      mirror: false,
    },
    {
      id: 'hatching',
      rank: 'detail',
      fill: 'none',
      d: 'M14 430 C14 430 11.66 533.88 10 580 C8.58 619.51 5 690 5 690',
      clipTo: 'scutellum',
    },
    {
      id: 'hatching',
      rank: 'detail',
      fill: 'none',
      d: 'M61 430 C61 430 42.65 533.9 34 580 C26.58 619.53 12.5 690 12.5 690',
      clipTo: 'scutellum',
    },
    {
      id: 'hatching',
      rank: 'detail',
      fill: 'none',
      d: 'M108 430 C108 430 73.64 533.91 58 580 C44.58 619.54 20 690 20 690',
      clipTo: 'scutellum',
    },
    // The pronotum: broad, and rounded at the shoulders.
    //
    // The lateral angles are the character. *Palomena* has them rounded; the
    // genera a key separates it from have them drawn out into points, and a
    // plate that squares them off has drawn a different animal.
    {
      id: 'pronotum',
      rank: 'outline',
      fill: 'pigment',
      d: 'M0 150 C36.67 150 74.38 149.79 110 158 C146.07 166.31 184.61 182.47 215 200 C241.96 215.55 269.66 235.66 285 255 C296.46 269.44 304.22 285.15 306 300 C307.62 313.46 308.2 330.58 298 340 C280.6 356.07 223.55 350.94 180 354 C126.39 357.77 60 358 0 358 C-60 358 -126.39 357.77 -180 354 C-223.55 350.94 -280.6 356.07 -298 340 C-308.2 330.58 -307.62 313.46 -306 300 C-304.22 285.15 -296.46 269.44 -285 255 C-269.66 235.66 -241.96 215.55 -215 200 C-184.61 182.47 -146.07 166.31 -110 158 C-74.38 149.79 -36.67 150 0 150 Z',
      mirror: false,
    },
    {
      id: 'hatching',
      rank: 'detail',
      fill: 'none',
      d: 'M22 250 C22 250 20 320 20 320',
      clipTo: 'pronotum',
    },
    {
      id: 'hatching',
      rank: 'detail',
      fill: 'none',
      d: 'M96 250 C96 250 92 318.67 92 318.67',
      clipTo: 'pronotum',
    },
    {
      id: 'hatching',
      rank: 'detail',
      fill: 'none',
      d: 'M170 250 C170 250 164 317.33 164 317.33',
      clipTo: 'pronotum',
    },
    {
      id: 'hatching',
      rank: 'detail',
      fill: 'none',
      d: 'M244 250 C244 250 236 316 236 316',
      clipTo: 'pronotum',
    },
    // The head, drawn once on the axis for the same reason as the scutellum.
    // The two lobes in front of the eyes meet ahead of the clypeus, which is
    // the blunt front margin the outline ends in.
    {
      id: 'head',
      rank: 'outline',
      fill: 'pigment',
      d: 'M0 0 C14 0 31.74 6.2 42 16 C52.84 26.35 56.73 45.79 62 62 C67.54 79.03 72.95 99.05 74 116 C74.92 130.8 78.58 148.75 70 158 C58.87 170 23.33 170 0 170 C-23.33 170 -58.87 170 -70 158 C-78.58 148.75 -74.92 130.8 -74 116 C-72.95 99.05 -67.54 79.03 -62 62 C-56.73 45.79 -52.84 26.35 -42 16 C-31.74 6.2 -14 0 0 0 Z',
      mirror: false,
    },
    {
      id: 'eye',
      rank: 'detail',
      fill: 'ink',
      d: 'M97.78 132.27 C101.02 142.25 93 153.8 79.87 158.07 C66.74 162.34 53.47 157.71 50.22 147.73 C46.98 137.75 55 126.2 68.13 121.93 C81.26 117.66 94.53 122.29 97.78 132.27 Z',
    },
    // Five segments, drawn as three strokes and a tip.
    //
    // The joints are what a reader sees at plate size, not the count. The last
    // two segments are darker and thicker than the first three in the
    // lithograph, so the tip is a filled capsule rather than the end of a
    // tapering line.
    {
      id: 'antenna',
      rank: 'structure',
      fill: 'none',
      d: 'M100 128 C100 128 125.13 93.02 136 74 C147.2 54.41 166 12 166 12',
    },
    {
      id: 'antenna',
      rank: 'structure',
      fill: 'none',
      d: 'M166 12 C166 12 186.41 -42.25 196 -70 C205.76 -98.24 224 -156 224 -156',
    },
    {
      id: 'antenna',
      rank: 'detail',
      fill: 'pigment-deep',
      d: 'M232 -153.14 C239.54 -161.61 245.88 -191.74 251.11 -209.6 C255.72 -225.36 263.2 -246.87 262.29 -254.64 C261.95 -257.51 260.79 -259.83 259.36 -260.29 C257.94 -260.74 255.65 -259.52 253.71 -257.36 C248.49 -251.57 242.75 -229.66 236.89 -214.4 C230.25 -197.09 215.53 -170.15 216 -158.86 C216.2 -153.78 218.47 -148.95 221.14 -148 C223.81 -147.04 228.62 -149.34 232 -153.14 Z',
    },
  ],
};
