// Generated from ../landmarks/vespa-crabro.json by `npm run plate:build`.
//
// Do not edit this file. Edit the landmarks and build again; `npm run
// plate:verify` fails the check if the two drift apart.

import type { SpeciesPlate } from '@/lib/plate';

/**
 * *Vespa crabro*, male, dorsal — the European hornet.
 *
 * Traced from figure 1 of Robert Morgan's plate 20 for Edward Saunders's *The
 * Hymenoptera Aculeata of the British Islands* (1896);
 * `references/vespa-crabro.jpg` is the sheet and the hornet is the large figure
 * at the top. The plate's own caption names the sex, which is why this plate
 * does: a male hornet has longer antennae and one more antennal segment than a
 * worker, and both show from above.
 *
 * ## The waist is the order
 *
 * `REQUIRED_PARTS.hymenoptera` does not list a part for it, and deliberately:
 * the waist is the *gap* between the thorax and the abdomen rather than a thing
 * to draw. What that means for an author is that the two parts either side of
 * it have to be measured honestly — a thorax drawn a little long or an abdomen
 * a little forward closes the gap, and a wasp without a waist is a fly.
 *
 * ## Bands, and why they are markings rather than segments
 *
 * Both are drawn, and they are not the same thing. `abdomen-segment` is the
 * join between one tergite and the next — an anatomical line that would be
 * there on a plain brown wasp. The dark `marking` bands are the pattern, and on
 * *crabro* they are notched: each runs across the tergite and then sends a
 * point back down the midline. A key asks about the pattern; a reader counting
 * segments needs the lines.
 *
 * ## Wings
 *
 * Four, and all four declare `opacity: 'membrane'`. A hornet's wings are glass:
 * the hindwing lies under the forewing and the legs pass under both, and
 * painting them opaque would delete a leg apiece.
 *
 * ## Plate space
 *
 * y = 0 at the top of the head, y = 1000 at the tip of the abdomen. The wings
 * reach past x = 900 — nearly twice the length of the body either side — and
 * the antennae above y = -190.
 */
export const VESPA_CRABRO_PLATE: SpeciesPlate = {
  species: 'vespa-crabro',
  order: 'hymenoptera',
  sex: 'male',
  hallmark: 'the waist between thorax and abdomen, and the notched dark bands across the tergites',
  reference: {
    title: 'Vespa crabro, from The Hymenoptera Aculeata of the British Islands, plate 20, fig. 1',
    artist: 'Robert Morgan',
    year: 1896,
    source: 'https://commons.wikimedia.org/wiki/File:SaundersHymenopteraAculeataPlate20.jpg',
    licence: 'Public domain (PD-US-expired, PD-old-70)',
  },
  parts: [
    // Legs first, so they pass under the wings and the body.
    //
    // A hornet's legs are long and slender and the reference draws them almost
    // straight, so the femora are measured at the light end of the six per cent
    // CLAUDE.md records — heavier and the animal reads as a bee.
    {
      id: 'hindleg-femur',
      rank: 'structure',
      fill: 'pigment-deep',
      d: 'M126.88 450.85 C138.2 473.04 197.12 510.25 232.25 539.4 C267.03 568.27 315.15 618.26 336.61 624.93 C344.53 627.39 352.14 626.7 354.93 623.39 C357.73 620.08 357.14 612.47 353.39 605.07 C343.23 585.04 285.62 546.43 251.75 516.6 C217.53 486.47 172.69 433.16 149.12 425.15 C139.27 421.79 128.85 422.59 125.15 426.88 C121.44 431.16 122.14 441.58 126.88 450.85 Z',
    },
    {
      id: 'hindleg-tibia',
      rank: 'structure',
      fill: 'pigment-deep',
      d: 'M333.1 616.55 C326.47 641.53 350.33 734.16 357.57 793.18 C364.81 852.25 365.78 950.8 376.54 970.81 C379.33 976 382.99 978.73 385.81 978.46 C388.63 978.19 391.7 974.82 393.46 969.19 C400.25 947.49 384.53 850.14 378.43 790.82 C372.34 731.56 369.71 635.94 356.9 613.45 C352.95 606.52 347.42 602.58 343.45 603.1 C339.49 603.62 335.14 608.84 333.1 616.55 Z',
    },
    {
      id: 'hindleg-tarsus',
      rank: 'detail',
      fill: 'pigment-deep',
      d: 'M378.03 969.36 C372.32 980.38 368.46 1034.22 372.03 1045.45 C373.21 1049.2 375.46 1051.79 377.45 1051.97 C379.44 1052.16 382.12 1050.02 383.97 1046.55 C389.53 1036.16 395.57 982.52 391.97 970.64 C390.67 966.36 387.97 963.24 385.64 963.03 C383.32 962.82 380.09 965.39 378.03 969.36 Z',
    },
    {
      id: 'hindleg-tarsus',
      rank: 'detail',
      fill: 'pigment-deep',
      d: 'M370.04 1053.28 C364.84 1062.68 360.25 1109.69 363.04 1119.4 C363.95 1122.56 365.74 1124.76 367.4 1124.96 C369.05 1125.16 371.32 1123.46 372.96 1120.6 C377.99 1111.84 384.77 1065.09 381.96 1054.72 C380.95 1051.02 378.71 1048.28 376.72 1048.04 C374.74 1047.8 371.9 1049.92 370.04 1053.28 Z',
    },
    {
      id: 'hindleg-tarsus',
      rank: 'detail',
      fill: 'ink',
      d: 'M361.07 1127.18 C356.91 1134.23 353.92 1169.36 355.53 1175.59 C355.97 1177.27 356.77 1178.33 357.59 1178.47 C358.41 1178.6 359.51 1177.86 360.47 1176.41 C364.01 1171.04 372.57 1136.84 370.93 1128.82 C370.31 1125.77 368.47 1123.34 366.82 1123.07 C365.18 1122.79 362.65 1124.49 361.07 1127.18 Z',
    },
    {
      id: 'midleg-femur',
      rank: 'structure',
      fill: 'pigment-deep',
      d: 'M115.91 330.95 C125.06 352.89 176.98 391.15 207.39 420.61 C237.3 449.57 277.08 498.37 296.86 506.24 C304.48 509.28 312.2 509.22 315.24 506.14 C318.29 503.06 318.26 495.34 315.14 487.76 C307.05 468.09 257.53 429.25 228.61 399.39 C199.19 369.03 161.91 316.43 140.09 307.05 C130.63 302.98 120.07 302.93 116.05 306.91 C112.02 310.9 111.95 321.45 115.91 330.95 Z',
    },
    {
      id: 'midleg-tibia',
      rank: 'structure',
      fill: 'pigment-deep',
      d: 'M294.31 499.69 C290.7 521.87 317.29 592.13 327.73 638.19 C338.06 683.77 345.71 758.44 356.66 774.64 C359.88 779.4 363.86 781.89 366.64 781.34 C369.42 780.79 372.17 776.98 373.34 771.36 C377.33 752.18 357.48 679.74 348.27 633.81 C338.95 587.39 330.65 512.7 317.69 494.31 C313.23 487.97 307.21 484.41 303.31 485.31 C299.41 486.2 295.55 492.04 294.31 499.69 Z',
    },
    {
      id: 'midleg-tarsus',
      rank: 'detail',
      fill: 'pigment-deep',
      d: 'M358.05 773.83 C354.8 785.73 362.24 838.54 368.04 848.71 C369.99 852.12 372.73 854.2 374.71 853.96 C376.7 853.72 378.87 851.06 379.96 847.29 C383.19 836.03 377.92 782.96 371.95 772.17 C369.79 768.26 366.48 765.77 364.17 766.05 C361.85 766.33 359.23 769.53 358.05 773.83 Z',
    },
    {
      id: 'midleg-tarsus',
      rank: 'detail',
      fill: 'pigment-deep',
      d: 'M370.03 856.63 C367.07 866.95 373.14 913.7 378.03 922.53 C379.62 925.41 381.87 927.15 383.53 926.97 C385.18 926.8 387.02 924.62 387.97 921.47 C390.9 911.82 387.03 864.83 381.97 855.37 C380.16 851.98 377.36 849.82 375.37 850.03 C373.38 850.24 371.09 852.94 370.03 856.63 Z',
    },
    {
      id: 'midleg-tarsus',
      rank: 'detail',
      fill: 'ink',
      d: 'M380.03 930.52 C377.91 938.38 384.32 972.71 387.51 978.26 C388.38 979.76 389.43 980.57 390.26 980.49 C391.09 980.4 391.95 979.39 392.49 977.74 C394.47 971.65 393.67 936.74 389.97 929.48 C388.56 926.71 386.14 924.85 384.48 925.03 C382.82 925.2 380.84 927.51 380.03 930.52 Z',
    },
    {
      id: 'foreleg-femur',
      rank: 'structure',
      fill: 'pigment-deep',
      d: 'M119.72 188.32 C140.1 180.26 173.76 135.39 200.41 108.8 C226.88 82.39 271.37 47.71 279.08 29.31 C282.2 21.85 282.33 14.03 279.31 10.92 C276.28 7.82 268.46 7.76 260.92 10.69 C242.36 17.92 206.95 61.78 179.59 87.2 C152.07 112.78 105.34 143.74 96.28 163.68 C92.11 172.88 91.78 183.61 95.68 187.72 C99.59 191.82 110.32 192.03 119.72 188.32 Z',
    },
    {
      id: 'foreleg-tibia',
      rank: 'structure',
      fill: 'pigment-deep',
      d: 'M279.43 27.43 C293.33 19.47 314.02 -17.09 330.37 -39.66 C346.49 -61.91 373.76 -93.32 376.87 -107 C378.07 -112.25 377.29 -117.21 375 -118.87 C372.71 -120.54 367.74 -119.75 363.13 -117 C351.1 -109.84 330.59 -73.78 313.63 -52.34 C296.42 -30.58 265.04 -2.75 260.57 12.57 C258.56 19.47 259.43 26.95 262.57 29.43 C265.72 31.9 273.19 31 279.43 27.43 Z',
    },
    {
      id: 'foreleg-tarsus',
      rank: 'detail',
      fill: 'pigment-deep',
      d: 'M376.52 -109.44 C383.85 -117.17 397.86 -155.66 397.58 -165.81 C397.48 -169.62 396.06 -172.85 394.19 -173.58 C392.33 -174.32 389.08 -172.92 386.42 -170.19 C379.31 -162.94 363.38 -125.22 363.48 -114.56 C363.53 -110.24 365.27 -106.34 367.44 -105.48 C369.61 -104.63 373.54 -106.3 376.52 -109.44 Z',
    },
    {
      id: 'foreleg-tarsus',
      rank: 'detail',
      fill: 'pigment-deep',
      d: 'M399.67 -174.04 C406.38 -181.74 419.39 -222.78 418.73 -232.37 C418.5 -235.62 417.21 -238.18 415.63 -238.73 C414.05 -239.27 411.46 -238.05 409.27 -235.63 C402.84 -228.49 387.79 -188.15 388.33 -177.96 C388.53 -174.16 390.15 -170.98 392.04 -170.33 C393.93 -169.68 397.18 -171.18 399.67 -174.04 Z',
    },
    {
      id: 'foreleg-tarsus',
      rank: 'detail',
      fill: 'ink',
      d: 'M420.74 -240.42 C425.62 -246.38 432.97 -277.16 432.37 -283.21 C432.2 -284.92 431.58 -286.11 430.79 -286.37 C430 -286.64 428.79 -286.06 427.63 -284.79 C423.52 -280.31 410.93 -251.27 411.26 -243.58 C411.39 -240.51 412.84 -237.78 414.42 -237.26 C416 -236.73 418.8 -238.04 420.74 -240.42 Z',
    },
    // The hindwing, drawn before the forewing so the forewing lies over it.
    // It is about half the length and barely shows past the front one, which is
    // how a wasp at rest reads and why it is easy to leave out.
    {
      id: 'hindwing',
      rank: 'outline',
      fill: 'surface',
      d: 'M130 252 C141.69 233.35 245.34 253.29 300 262 C352.52 270.37 406.3 285.55 452 302 C491.76 316.31 538.18 333.31 560 352 C573.16 363.27 587.03 379.69 584 388 C580.74 396.93 556.37 399.99 536 402 C502.1 405.35 443.03 397.45 398 390 C353.73 382.67 308.14 370.52 268 358 C232.12 346.81 191.36 340.16 168 320 C148.07 302.79 122.09 264.61 130 252 Z',
      opacity: 'membrane',
    },
    {
      id: 'wing-vein',
      rank: 'detail',
      fill: 'none',
      d: 'M190 288 C190 288 291.16 299.83 340 310 C387.78 319.95 480 348 480 348',
      clipTo: 'hindwing',
    },
    // The forewing. Long, narrow, and folded back along the body in life — the
    // reference has it spread, which is what a pinned specimen looks like and
    // what a plate has to draw if the venation is to be visible at all.
    {
      id: 'forewing',
      rank: 'outline',
      fill: 'surface',
      d: 'M120 178 C141.34 136.43 236.59 137.39 300 120 C369.26 101.01 448.14 83.17 520 70 C587.99 57.54 659.15 47.99 720 42 C770.71 37.01 826.74 27.93 860 34 C879.71 37.6 902.29 44.11 905 54 C907.64 63.62 893.1 80.51 878 92 C851.21 112.38 788.94 123.62 740 142 C683.86 163.08 617.8 187.07 560 212 C504.65 235.87 450.56 263.94 400 288 C354.41 309.7 307.77 330.17 270 350 C239.77 365.87 212.06 404.54 190 396 C155.25 382.56 96.52 223.74 120 178 Z',
      opacity: 'membrane',
    },
    {
      id: 'wing-vein',
      rank: 'detail',
      fill: 'none',
      d: 'M200 172 C200 172 364.75 128.13 450 110 C537.96 91.3 720 62 720 62',
      clipTo: 'forewing',
    },
    {
      id: 'wing-vein',
      rank: 'detail',
      fill: 'none',
      d: 'M200 230 C200 230 351.87 194.81 430 175 C511.73 154.28 680 108 680 108',
      clipTo: 'forewing',
    },
    {
      id: 'wing-vein',
      rank: 'detail',
      fill: 'none',
      d: 'M210 300 C210 300 339.45 266.48 400 250 C455.69 234.84 560 205 560 205',
      clipTo: 'forewing',
    },
    {
      id: 'wing-vein',
      rank: 'detail',
      fill: 'none',
      d: 'M352 154 C352 154 364.67 196.51 368 218 C371.28 239.18 372 282 372 282',
      clipTo: 'forewing',
    },
    // The abdomen. Drawn once on the axis: it is one organ straddling the
    // midline and symmetric in itself, so reflecting it would show as a doubled
    // line down the back.
    {
      id: 'abdomen',
      rank: 'outline',
      fill: 'pigment',
      d: 'M0 470 C19.67 470 37.39 474.52 59 481 C87.32 489.5 134.93 497.94 154 521 C172.41 543.27 170.15 583.08 174 615 C177.91 647.4 178.98 681.09 177 714 C175.01 747.09 171.5 780.72 162 813 C152.16 846.44 135.84 883.59 118 911 C102.67 934.55 85.22 954.68 65 970 C45.67 984.64 21.67 1002 0 1002 C-21.67 1002 -45.67 984.64 -65 970 C-85.22 954.68 -102.67 934.55 -118 911 C-135.84 883.59 -152.16 846.44 -162 813 C-171.5 780.72 -175.01 747.09 -177 714 C-178.98 681.09 -177.91 647.4 -174 615 C-170.15 583.08 -172.41 543.27 -154 521 C-134.93 497.94 -87.32 489.5 -59 481 C-37.39 474.52 -19.67 470 0 470 Z',
      mirror: false,
    },
    // The joins between tergites — anatomy, not pattern. See the note at the
    // top of the file.
    {
      id: 'abdomen-segment',
      rank: 'detail',
      fill: 'none',
      d: 'M-150 578 C-150 578 -50 592 0 592 C50 592 150 578 150 578',
      mirror: false,
    },
    {
      id: 'abdomen-segment',
      rank: 'detail',
      fill: 'none',
      d: 'M-172 690 C-172 690 -57.33 704 0 704 C57.33 704 172 690 172 690',
      mirror: false,
    },
    {
      id: 'abdomen-segment',
      rank: 'detail',
      fill: 'none',
      d: 'M-150 800 C-150 800 -50 814 0 814 C50 814 150 800 150 800',
      mirror: false,
    },
    {
      id: 'abdomen-segment',
      rank: 'detail',
      fill: 'none',
      d: 'M-108 890 C-108 890 -36 902 0 902 C36 902 108 890 108 890',
      mirror: false,
    },
    // The notched bands, which are the pattern a key asks about.
    //
    // Each runs across a tergite and sends a point back down the midline, and
    // it is that notch rather than the band that separates *crabro* from the
    // yellowjackets it is drawn beside on the reference plate.
    {
      id: 'marking',
      rank: 'structure',
      fill: 'pigment-deep',
      d: 'M0 600 C32 600 69.11 590.81 96 594 C116.22 596.4 139.15 599.19 148 610 C155.6 619.29 158.36 644.5 152 650 C144.38 656.59 117.07 635.39 96 636 C68.19 636.81 32 666 0 666 C-32 666 -68.19 636.81 -96 636 C-117.07 635.39 -144.38 656.59 -152 650 C-158.36 644.5 -155.6 619.29 -148 610 C-139.15 599.19 -116.22 596.4 -96 594 C-69.11 590.81 -32 600 0 600 Z',
      mirror: false,
      clipTo: 'abdomen',
    },
    {
      id: 'marking',
      rank: 'structure',
      fill: 'pigment-deep',
      d: 'M0 710 C33.33 710 71.93 699.55 100 702 C120.93 703.82 145.32 705.34 154 716 C161.36 725.03 162.75 750.26 156 756 C147.93 762.86 121.2 742.95 100 744 C71.3 745.42 33.33 776 0 776 C-33.33 776 -71.3 745.42 -100 744 C-121.2 742.95 -147.93 762.86 -156 756 C-162.75 750.26 -161.36 725.03 -154 716 C-145.32 705.34 -120.93 703.82 -100 702 C-71.93 699.55 -33.33 710 0 710 Z',
      mirror: false,
      clipTo: 'abdomen',
    },
    {
      id: 'marking',
      rank: 'structure',
      fill: 'pigment-deep',
      d: 'M0 820 C27.33 820 59.42 809.45 82 812 C98.55 813.87 117.46 816.93 124 826 C129.73 833.95 129.92 855.28 124 860 C117.18 865.44 96.69 849.05 80 850 C57.13 851.3 26.67 878 0 878 C-26.67 878 -57.13 851.3 -80 850 C-96.69 849.05 -117.18 865.44 -124 860 C-129.92 855.28 -129.73 833.95 -124 826 C-117.46 816.93 -98.55 813.87 -82 812 C-59.42 809.45 -27.33 820 0 820 Z',
      mirror: false,
      clipTo: 'abdomen',
    },
    // The thorax: one box from above, because a wasp's plates are not
    // separable in dorsal view. `pronotum` is the id for a beetle, where the
    // front plate is always a distinct shield; here it is not.
    {
      id: 'thorax',
      rank: 'outline',
      fill: 'pigment',
      d: 'M0 136 C42 136 98.33 135.25 126 158 C151.82 179.24 161.19 226.76 166 262 C170.66 296.13 168.48 335.22 156 366 C143.64 396.48 118.77 429.4 92 446 C66.33 461.92 30.67 466 0 466 C-30.67 466 -66.33 461.92 -92 446 C-118.77 429.4 -143.64 396.48 -156 366 C-168.48 335.22 -170.66 296.13 -166 262 C-161.19 226.76 -151.82 179.24 -126 158 C-98.33 135.25 -42 136 0 136 Z',
      mirror: false,
    },
    {
      id: 'hatching',
      rank: 'detail',
      fill: 'none',
      d: 'M14 212 C14 212 12.97 271.37 12 302 C10.99 333.98 8 400 8 400',
      clipTo: 'thorax',
    },
    {
      id: 'hatching',
      rank: 'detail',
      fill: 'none',
      d: 'M61 212 C61 212 59.41 271.53 55 302 C50.35 334.15 33 400 33 400',
      clipTo: 'thorax',
    },
    {
      id: 'hatching',
      rank: 'detail',
      fill: 'none',
      d: 'M108 212 C108 212 105.66 271.9 98 302 C89.72 334.55 58 400 58 400',
      clipTo: 'thorax',
    },
    {
      id: 'head',
      rank: 'outline',
      fill: 'pigment',
      d: 'M0 -6 C19.33 -6 41.91 -4.08 58 6 C74.93 16.6 90.99 41.1 98 58 C103.36 70.92 103.95 83.12 103 96 C101.98 109.75 101.89 128.4 91 138 C75.19 151.94 30.33 152 0 152 C-30.33 152 -75.19 151.94 -91 138 C-101.89 128.4 -101.98 109.75 -103 96 C-103.95 83.12 -103.36 70.92 -98 58 C-90.99 41.1 -74.93 16.6 -58 6 C-41.91 -4.08 -19.33 -6 0 -6 Z',
      mirror: false,
    },
    // The compound eye, notched on its inner margin — which is a Vespidae
    // character and the reason the eye is drawn as a crescent rather than an
    // oval. `eye` rather than `compound-eye`: that id is reserved for a
    // dragonfly's, which wrap the head and meet on top of it.
    {
      id: 'eye',
      rank: 'structure',
      fill: 'ink',
      d: 'M105.61 76.51 C100.43 105.89 84.76 127.67 70.62 125.18 C56.48 122.69 49.22 96.86 54.39 67.49 C59.57 38.11 75.24 16.33 89.38 18.82 C103.52 21.31 110.78 47.14 105.61 76.51 Z',
    },
    // Three ocelli on the vertex, in the triangle every aculeate wasp has them
    // in. Two are a mirrored pair and the third sits on the axis.
    {
      id: 'ocellus',
      rank: 'detail',
      fill: 'ink',
      d: 'M36 34 C36 38.42 31.52 42 26 42 C20.48 42 16 38.42 16 34 C16 29.58 20.48 26 26 26 C31.52 26 36 29.58 36 34 Z',
    },
    {
      id: 'ocellus',
      rank: 'detail',
      fill: 'ink',
      d: 'M10 12 C10 16.42 5.52 20 0 20 C-5.52 20 -10 16.42 -10 12 C-10 7.58 -5.52 4 0 4 C5.52 4 10 7.58 10 12 Z',
      mirror: false,
    },
    // A male's antenna: thirteen segments, elbowed, and long enough to reach
    // well past the head. A worker's is shorter by a segment, so this is one of
    // the two places the plate commits to a sex.
    //
    // Two filled segments meeting at the bend, not a scape with two hairlines
    // trailing off it. Those were rank `structure`: 4.6 units across a frame
    // nearly two thousand wide, which is a fifth of a pixel at eighty — so
    // the animal lost its antennae at exactly the size the contact sheet
    // judges it at. A capsule is measured in plate units and cannot.
    {
      id: 'antenna',
      rank: 'structure',
      fill: 'pigment-deep',
      d: 'M45.63 59.81 C53.67 52.6 58.98 32.77 64.56 18.54 C70.27 3.99 80.02 -16.21 79.4 -26.58 C79.06 -32.24 76.55 -38.26 73.42 -39.4 C70.28 -40.54 64.48 -37.52 60.6 -33.42 C53.59 -26.01 49.9 -4.29 43.44 9.46 C37.12 22.89 23.3 37.65 22.37 48.19 C21.77 54.99 24.31 63.69 28.19 65.63 C32.06 67.57 40.51 64.4 45.63 59.81 Z',
    },
    // The flagellum: one capsule from the elbow to the tip, tapering to about
    // a third of the scape. Long, because a male hornet's is, and it is the
    // reason plate space starts at the head end rather than at the topmost ink.
    {
      id: 'antenna',
      rank: 'structure',
      fill: 'pigment-deep',
      d: 'M75.41 -21.59 C91.83 -24.72 130.21 -59.77 158.09 -77.12 C185.4 -94.12 215.54 -109.62 240.95 -124.77 C262.97 -137.91 296.2 -154.71 302.01 -162.54 C303.64 -164.74 304.13 -166.86 303.46 -168.01 C302.79 -169.16 300.71 -169.79 297.99 -169.46 C288.33 -168.3 257.67 -147.27 235.05 -135.23 C208.87 -121.29 178.03 -106.82 149.91 -90.88 C121.2 -74.6 74.3 -52.1 64.59 -38.41 C60.95 -33.27 59.79 -27.4 61.59 -24.59 C63.39 -21.79 69.22 -20.41 75.41 -21.59 Z',
    },
  ],
};
