/**
 * `npm run seo:build` — regenerate `public/robots.txt` and `public/sitemap.xml`.
 * `npm run seo:verify` — check the committed files have not drifted.
 *
 * Same shape and the same reasoning as the plate and sources builders: a
 * generated file that nothing checks is a file somebody edits by hand, and from
 * then on it is fiction. `seo:verify` runs inside `npm run check`, and compares
 * **bytes** — there is no clock and no randomness here, so byte equality is a
 * fair thing to demand.
 *
 * It matters more for a sitemap than for most generated files, because a
 * sitemap is the one document on the site that no human ever opens. A specimen
 * accessioned without its URL being listed is invisible, and nothing would look
 * broken.
 *
 * ## Where the URLs come from
 *
 * `ROUTES` below mirrors the tree in `src/app/router.tsx`, and the eighteen
 * specimen URLs and five journal URLs are read out of the data — so accessioning
 * a species or filing an entry updates the sitemap, and forgetting to rebuild
 * fails the check.
 *
 * The route list is the one part that is copied rather than derived. Reading
 * `router.tsx` would mean importing React, react-router and every route module
 * into a Node script; the list is six lines and `seo.test.ts` asserts it against
 * the live router, which is the cheaper half of the same guarantee.
 *
 * Both sets of slugs come from `scripts/site-paths.ts`, which reads them off
 * the filesystem and explains why that is the only way a Node script can get
 * at them. The prerenderer takes its route list from the same module, so a
 * specimen cannot end up in the sitemap without a file behind it.
 *
 * ## What is deliberately absent
 *
 * No `lastmod`, no `changefreq`, no `priority`. `lastmod` would have to come
 * from a clock or from git, and either makes the output non-deterministic and
 * the verify step a lie; Google ignores the other two outright. A sitemap that
 * carries three fields nobody reads and one that cannot be checked is worse
 * than a plain list of URLs, which is what this is.
 */

import { readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import process from 'node:process';

import { siteUrl } from '../../src/data/site.ts';
import { journalSlugs, ROOT, speciesSlugs } from '../site-paths.ts';

const PUBLIC = join(ROOT, 'public');

/**
 * The fixed routes, in the order `src/app/routes.tsx` declares them.
 *
 * `/` and `/catalogue` render the same component, and only `/` is listed:
 * two URLs for one page is the duplicate-content problem a sitemap should not
 * be creating. Both addresses get a *file* — see `scripts/site-paths.ts`, which
 * is answering a different question — and both carry the same canonical link,
 * `/catalogue`, because one component has one `routeMeta`. So a crawler that
 * follows `/` from here is told once, in the page, which of the two to index.
 *
 * `/404` is not listed either, for the obvious reason, and it is the one page
 * whose canonical is worth knowing about: it names `/404`, an address the site
 * does not really have. Harmless — the page is served with a 404 status and a
 * crawler discards the canonical along with the rest of it.
 *
 * `/lab/plates` is dev-only and never built. `*` is the 404, which must not be
 * in a sitemap at all.
 */
export const ROUTES: readonly string[] = [
  '/',
  '/key',
  '/calendar',
  '/about',
  '/journal',
  '/request',
];

export async function sitemapUrls(): Promise<readonly string[]> {
  return [
    ...ROUTES.map((path) => siteUrl(path)),
    ...(await speciesSlugs()).map((slug) => siteUrl(`/specimen/${slug}`)),
    ...(await journalSlugs()).map((slug) => siteUrl(`/journal/${slug}`)),
  ];
}

async function sitemap(): Promise<string> {
  const urls = (await sitemapUrls())
    .map((url) => `  <url>\n    <loc>${url}</loc>\n  </url>`)
    .join('\n');

  return `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${urls}\n</urlset>\n`;
}

function robots(): string {
  return `# Generated by \`npm run seo:build\`. Do not edit; \`npm run seo:verify\`
# fails the check if this file and src/data/site.ts drift apart.
#
# Everything here is public and static, so everything is crawlable. The two
# disallowed paths are not secrets — they are URLs that would waste a crawl:
#
#   /lab/       the plate contact sheet. Dev-only and never built, so this is a
#               belt-and-braces line rather than a live rule.
#   /*?k=       the identification key mid-answer. Every state of the key lives
#               at /key with its answers in the query string, and there are
#               hundreds of them; they are steps through one document, and the
#               page's own canonical link already says so.

User-agent: *
Allow: /
Disallow: /lab/
Disallow: /*?k=

Sitemap: ${siteUrl('/sitemap.xml')}
`;
}

async function main(): Promise<void> {
  const verify = process.argv.includes('--verify');
  const files: readonly (readonly [string, string])[] = [
    ['robots.txt', robots()],
    ['sitemap.xml', await sitemap()],
  ];
  const count = (await sitemapUrls()).length;

  for (const [name, expected] of files) {
    const path = join(PUBLIC, name);

    if (verify) {
      const actual = await readFile(path, 'utf8').catch(() => null);

      if (actual !== expected) {
        console.error(
          `seo:verify — public/${name} has drifted from src/data/site.ts.\n` +
            '  Run `npm run seo:build` and commit the result.',
        );
        process.exitCode = 1;

        return;
      }
    } else {
      await writeFile(path, expected, 'utf8');
    }
  }

  console.log(
    verify
      ? `seo:verify — robots.txt and sitemap.xml match (${String(count)} URLs)`
      : `seo:build — wrote public/robots.txt and public/sitemap.xml (${String(count)} URLs)`,
  );
}

await main().catch((error: unknown) => {
  console.error(error);
  process.exitCode = 1;
});
